/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  BadRequestErrorResponseContent,
  CreateBackupRequestContent,
  CreateBackupResponseContent,
  CreateBackupScheduleRequestContent,
  CreateBackupScheduleResponseContent,
  DeleteBackupRequestContent,
  DeleteBackupResponseContent,
  DeleteBackupScheduleRequestContent,
  DeleteBackupScheduleResponseContent,
  EditBackupScheduleRequestContent,
  EditBackupScheduleResponseContent,
  ForbiddenErrorResponseContent,
  InternalServiceErrorResponseContent,
  ListBackupSchedulesRequestContent,
  ListBackupSchedulesResponseContent,
  ListBackupsRequestContent,
  ListBackupsResponseContent,
  ResourceNotFoundErrorResponseContent,
  RestoreBackupRequestContent,
  RestoreBackupResponseContent,
  ServiceUnavailableErrorResponseContent,
  TooManyRequestsErrorResponseContent,
  UnauthorizedErrorResponseContent,
  ValidationErrorResponseContent,
} from '../models/index.js';
import {
    BadRequestErrorResponseContentFromJSON,
    BadRequestErrorResponseContentToJSON,
    CreateBackupRequestContentFromJSON,
    CreateBackupRequestContentToJSON,
    CreateBackupResponseContentFromJSON,
    CreateBackupResponseContentToJSON,
    CreateBackupScheduleRequestContentFromJSON,
    CreateBackupScheduleRequestContentToJSON,
    CreateBackupScheduleResponseContentFromJSON,
    CreateBackupScheduleResponseContentToJSON,
    DeleteBackupRequestContentFromJSON,
    DeleteBackupRequestContentToJSON,
    DeleteBackupResponseContentFromJSON,
    DeleteBackupResponseContentToJSON,
    DeleteBackupScheduleRequestContentFromJSON,
    DeleteBackupScheduleRequestContentToJSON,
    DeleteBackupScheduleResponseContentFromJSON,
    DeleteBackupScheduleResponseContentToJSON,
    EditBackupScheduleRequestContentFromJSON,
    EditBackupScheduleRequestContentToJSON,
    EditBackupScheduleResponseContentFromJSON,
    EditBackupScheduleResponseContentToJSON,
    ForbiddenErrorResponseContentFromJSON,
    ForbiddenErrorResponseContentToJSON,
    InternalServiceErrorResponseContentFromJSON,
    InternalServiceErrorResponseContentToJSON,
    ListBackupSchedulesRequestContentFromJSON,
    ListBackupSchedulesRequestContentToJSON,
    ListBackupSchedulesResponseContentFromJSON,
    ListBackupSchedulesResponseContentToJSON,
    ListBackupsRequestContentFromJSON,
    ListBackupsRequestContentToJSON,
    ListBackupsResponseContentFromJSON,
    ListBackupsResponseContentToJSON,
    ResourceNotFoundErrorResponseContentFromJSON,
    ResourceNotFoundErrorResponseContentToJSON,
    RestoreBackupRequestContentFromJSON,
    RestoreBackupRequestContentToJSON,
    RestoreBackupResponseContentFromJSON,
    RestoreBackupResponseContentToJSON,
    ServiceUnavailableErrorResponseContentFromJSON,
    ServiceUnavailableErrorResponseContentToJSON,
    TooManyRequestsErrorResponseContentFromJSON,
    TooManyRequestsErrorResponseContentToJSON,
    UnauthorizedErrorResponseContentFromJSON,
    UnauthorizedErrorResponseContentToJSON,
    ValidationErrorResponseContentFromJSON,
    ValidationErrorResponseContentToJSON,
} from '../models/index.js';

export interface CreateBackupRequest {
    createBackupRequestContent: CreateBackupRequestContent;
}

export interface CreateBackupScheduleRequest {
    createBackupScheduleRequestContent: CreateBackupScheduleRequestContent;
}

export interface DeleteBackupRequest {
    deleteBackupRequestContent: DeleteBackupRequestContent;
}

export interface DeleteBackupScheduleRequest {
    deleteBackupScheduleRequestContent: DeleteBackupScheduleRequestContent;
}

export interface EditBackupScheduleRequest {
    editBackupScheduleRequestContent: EditBackupScheduleRequestContent;
}

export interface ListBackupSchedulesRequest {
    listBackupSchedulesRequestContent: ListBackupSchedulesRequestContent;
}

export interface ListBackupsRequest {
    listBackupsRequestContent: ListBackupsRequestContent;
}

export interface RestoreBackupRequest {
    restoreBackupRequestContent: RestoreBackupRequestContent;
}

/**
 * 
 */
export class BackupsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createBackup without sending the request
     */
    async createBackupRequestOpts(requestParameters: CreateBackupRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createBackupRequestContent'] == null) {
            throw new runtime.RequiredError(
                'createBackupRequestContent',
                'Required parameter "createBackupRequestContent" was null or undefined when calling createBackup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vps/create-backup`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateBackupRequestContentToJSON(requestParameters['createBackupRequestContent']),
        };
    }

    /**
     * Creates a new backup for a VPS service
     */
    async createBackupRaw(requestParameters: CreateBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateBackupResponseContent>> {
        const requestOptions = await this.createBackupRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateBackupResponseContentFromJSON(jsonValue));
    }

    /**
     * Creates a new backup for a VPS service
     */
    async createBackup(requestParameters: CreateBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateBackupResponseContent> {
        const response = await this.createBackupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createBackupSchedule without sending the request
     */
    async createBackupScheduleRequestOpts(requestParameters: CreateBackupScheduleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createBackupScheduleRequestContent'] == null) {
            throw new runtime.RequiredError(
                'createBackupScheduleRequestContent',
                'Required parameter "createBackupScheduleRequestContent" was null or undefined when calling createBackupSchedule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vps/create-backup-schedule`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateBackupScheduleRequestContentToJSON(requestParameters['createBackupScheduleRequestContent']),
        };
    }

    /**
     * Creates a new backup schedule for a VPS service
     */
    async createBackupScheduleRaw(requestParameters: CreateBackupScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateBackupScheduleResponseContent>> {
        const requestOptions = await this.createBackupScheduleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateBackupScheduleResponseContentFromJSON(jsonValue));
    }

    /**
     * Creates a new backup schedule for a VPS service
     */
    async createBackupSchedule(requestParameters: CreateBackupScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateBackupScheduleResponseContent> {
        const response = await this.createBackupScheduleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteBackup without sending the request
     */
    async deleteBackupRequestOpts(requestParameters: DeleteBackupRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['deleteBackupRequestContent'] == null) {
            throw new runtime.RequiredError(
                'deleteBackupRequestContent',
                'Required parameter "deleteBackupRequestContent" was null or undefined when calling deleteBackup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vps/delete-backup`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteBackupRequestContentToJSON(requestParameters['deleteBackupRequestContent']),
        };
    }

    /**
     * Deletes a specific backup from a VPS service
     */
    async deleteBackupRaw(requestParameters: DeleteBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteBackupResponseContent>> {
        const requestOptions = await this.deleteBackupRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteBackupResponseContentFromJSON(jsonValue));
    }

    /**
     * Deletes a specific backup from a VPS service
     */
    async deleteBackup(requestParameters: DeleteBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteBackupResponseContent> {
        const response = await this.deleteBackupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteBackupSchedule without sending the request
     */
    async deleteBackupScheduleRequestOpts(requestParameters: DeleteBackupScheduleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['deleteBackupScheduleRequestContent'] == null) {
            throw new runtime.RequiredError(
                'deleteBackupScheduleRequestContent',
                'Required parameter "deleteBackupScheduleRequestContent" was null or undefined when calling deleteBackupSchedule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vps/delete-backup-schedule`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteBackupScheduleRequestContentToJSON(requestParameters['deleteBackupScheduleRequestContent']),
        };
    }

    /**
     * Deletes a backup schedule from a VPS service
     */
    async deleteBackupScheduleRaw(requestParameters: DeleteBackupScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteBackupScheduleResponseContent>> {
        const requestOptions = await this.deleteBackupScheduleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteBackupScheduleResponseContentFromJSON(jsonValue));
    }

    /**
     * Deletes a backup schedule from a VPS service
     */
    async deleteBackupSchedule(requestParameters: DeleteBackupScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteBackupScheduleResponseContent> {
        const response = await this.deleteBackupScheduleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for editBackupSchedule without sending the request
     */
    async editBackupScheduleRequestOpts(requestParameters: EditBackupScheduleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['editBackupScheduleRequestContent'] == null) {
            throw new runtime.RequiredError(
                'editBackupScheduleRequestContent',
                'Required parameter "editBackupScheduleRequestContent" was null or undefined when calling editBackupSchedule().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vps/edit-backup-schedule`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EditBackupScheduleRequestContentToJSON(requestParameters['editBackupScheduleRequestContent']),
        };
    }

    /**
     * Edits an existing backup schedule for a VPS service
     */
    async editBackupScheduleRaw(requestParameters: EditBackupScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EditBackupScheduleResponseContent>> {
        const requestOptions = await this.editBackupScheduleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EditBackupScheduleResponseContentFromJSON(jsonValue));
    }

    /**
     * Edits an existing backup schedule for a VPS service
     */
    async editBackupSchedule(requestParameters: EditBackupScheduleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EditBackupScheduleResponseContent> {
        const response = await this.editBackupScheduleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listBackupSchedules without sending the request
     */
    async listBackupSchedulesRequestOpts(requestParameters: ListBackupSchedulesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['listBackupSchedulesRequestContent'] == null) {
            throw new runtime.RequiredError(
                'listBackupSchedulesRequestContent',
                'Required parameter "listBackupSchedulesRequestContent" was null or undefined when calling listBackupSchedules().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vps/list-backup-schedules`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ListBackupSchedulesRequestContentToJSON(requestParameters['listBackupSchedulesRequestContent']),
        };
    }

    /**
     * Retrieves the list of backup schedules for a VPS service
     */
    async listBackupSchedulesRaw(requestParameters: ListBackupSchedulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListBackupSchedulesResponseContent>> {
        const requestOptions = await this.listBackupSchedulesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListBackupSchedulesResponseContentFromJSON(jsonValue));
    }

    /**
     * Retrieves the list of backup schedules for a VPS service
     */
    async listBackupSchedules(requestParameters: ListBackupSchedulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListBackupSchedulesResponseContent> {
        const response = await this.listBackupSchedulesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listBackups without sending the request
     */
    async listBackupsRequestOpts(requestParameters: ListBackupsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['listBackupsRequestContent'] == null) {
            throw new runtime.RequiredError(
                'listBackupsRequestContent',
                'Required parameter "listBackupsRequestContent" was null or undefined when calling listBackups().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vps/list-backups`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ListBackupsRequestContentToJSON(requestParameters['listBackupsRequestContent']),
        };
    }

    /**
     * Retrieves the list of backups for a VPS service including quota information and backup configuration options
     */
    async listBackupsRaw(requestParameters: ListBackupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListBackupsResponseContent>> {
        const requestOptions = await this.listBackupsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListBackupsResponseContentFromJSON(jsonValue));
    }

    /**
     * Retrieves the list of backups for a VPS service including quota information and backup configuration options
     */
    async listBackups(requestParameters: ListBackupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListBackupsResponseContent> {
        const response = await this.listBackupsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for restoreBackup without sending the request
     */
    async restoreBackupRequestOpts(requestParameters: RestoreBackupRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['restoreBackupRequestContent'] == null) {
            throw new runtime.RequiredError(
                'restoreBackupRequestContent',
                'Required parameter "restoreBackupRequestContent" was null or undefined when calling restoreBackup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vps/restore-backup`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RestoreBackupRequestContentToJSON(requestParameters['restoreBackupRequestContent']),
        };
    }

    /**
     * Restores a VPS from a backup with the specified backup identifier
     */
    async restoreBackupRaw(requestParameters: RestoreBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RestoreBackupResponseContent>> {
        const requestOptions = await this.restoreBackupRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RestoreBackupResponseContentFromJSON(jsonValue));
    }

    /**
     * Restores a VPS from a backup with the specified backup identifier
     */
    async restoreBackup(requestParameters: RestoreBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RestoreBackupResponseContent> {
        const response = await this.restoreBackupRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
