/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BadRequestErrorResponseContent,
  CreateRdnsRecordRequestContent,
  CreateRdnsRecordResponseContent,
  DeleteRdnsRecordRequestContent,
  DeleteRdnsRecordResponseContent,
  ForbiddenErrorResponseContent,
  InternalServiceErrorResponseContent,
  InvalidStateErrorResponseContent,
  ListRdnsRecordsResponseContent,
  ResourceNotFoundErrorResponseContent,
  ServiceUnavailableErrorResponseContent,
  TooManyRequestsErrorResponseContent,
  UnauthorizedErrorResponseContent,
  ValidationErrorResponseContent,
} from '../models/index';
import {
    BadRequestErrorResponseContentFromJSON,
    BadRequestErrorResponseContentToJSON,
    CreateRdnsRecordRequestContentFromJSON,
    CreateRdnsRecordRequestContentToJSON,
    CreateRdnsRecordResponseContentFromJSON,
    CreateRdnsRecordResponseContentToJSON,
    DeleteRdnsRecordRequestContentFromJSON,
    DeleteRdnsRecordRequestContentToJSON,
    DeleteRdnsRecordResponseContentFromJSON,
    DeleteRdnsRecordResponseContentToJSON,
    ForbiddenErrorResponseContentFromJSON,
    ForbiddenErrorResponseContentToJSON,
    InternalServiceErrorResponseContentFromJSON,
    InternalServiceErrorResponseContentToJSON,
    InvalidStateErrorResponseContentFromJSON,
    InvalidStateErrorResponseContentToJSON,
    ListRdnsRecordsResponseContentFromJSON,
    ListRdnsRecordsResponseContentToJSON,
    ResourceNotFoundErrorResponseContentFromJSON,
    ResourceNotFoundErrorResponseContentToJSON,
    ServiceUnavailableErrorResponseContentFromJSON,
    ServiceUnavailableErrorResponseContentToJSON,
    TooManyRequestsErrorResponseContentFromJSON,
    TooManyRequestsErrorResponseContentToJSON,
    UnauthorizedErrorResponseContentFromJSON,
    UnauthorizedErrorResponseContentToJSON,
    ValidationErrorResponseContentFromJSON,
    ValidationErrorResponseContentToJSON,
} from '../models/index';

export interface CreateRdnsRecordRequest {
    createRdnsRecordRequestContent: CreateRdnsRecordRequestContent;
}

export interface DeleteRdnsRecordRequest {
    deleteRdnsRecordRequestContent: DeleteRdnsRecordRequestContent;
}

/**
 * 
 */
export class DNSApi extends runtime.BaseAPI {

    /**
     * Creates request options for createRdnsRecord without sending the request
     */
    async createRdnsRecordRequestOpts(requestParameters: CreateRdnsRecordRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createRdnsRecordRequestContent'] == null) {
            throw new runtime.RequiredError(
                'createRdnsRecordRequestContent',
                'Required parameter "createRdnsRecordRequestContent" was null or undefined when calling createRdnsRecord().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/dns/create-rdns-record`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRdnsRecordRequestContentToJSON(requestParameters['createRdnsRecordRequestContent']),
        };
    }

    /**
     * Creates (or upserts) a PTR record for the authenticated client. If the client already owns a PTR for the same (serverid, ip) it is updated in place; if another client owns it a 409 is returned.
     */
    async createRdnsRecordRaw(requestParameters: CreateRdnsRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateRdnsRecordResponseContent>> {
        const requestOptions = await this.createRdnsRecordRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateRdnsRecordResponseContentFromJSON(jsonValue));
    }

    /**
     * Creates (or upserts) a PTR record for the authenticated client. If the client already owns a PTR for the same (serverid, ip) it is updated in place; if another client owns it a 409 is returned.
     */
    async createRdnsRecord(requestParameters: CreateRdnsRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateRdnsRecordResponseContent> {
        const response = await this.createRdnsRecordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteRdnsRecord without sending the request
     */
    async deleteRdnsRecordRequestOpts(requestParameters: DeleteRdnsRecordRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['deleteRdnsRecordRequestContent'] == null) {
            throw new runtime.RequiredError(
                'deleteRdnsRecordRequestContent',
                'Required parameter "deleteRdnsRecordRequestContent" was null or undefined when calling deleteRdnsRecord().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/dns/delete-rdns-record`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteRdnsRecordRequestContentToJSON(requestParameters['deleteRdnsRecordRequestContent']),
        };
    }

    /**
     * Deletes a PTR (rDNS) record owned by the authenticated client
     */
    async deleteRdnsRecordRaw(requestParameters: DeleteRdnsRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteRdnsRecordResponseContent>> {
        const requestOptions = await this.deleteRdnsRecordRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteRdnsRecordResponseContentFromJSON(jsonValue));
    }

    /**
     * Deletes a PTR (rDNS) record owned by the authenticated client
     */
    async deleteRdnsRecord(requestParameters: DeleteRdnsRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteRdnsRecordResponseContent> {
        const response = await this.deleteRdnsRecordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listRdnsRecords without sending the request
     */
    async listRdnsRecordsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/dns/list-rdns-records`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lists all rDNS (PTR) records and available services for the authenticated client
     */
    async listRdnsRecordsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListRdnsRecordsResponseContent>> {
        const requestOptions = await this.listRdnsRecordsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListRdnsRecordsResponseContentFromJSON(jsonValue));
    }

    /**
     * Lists all rDNS (PTR) records and available services for the authenticated client
     */
    async listRdnsRecords(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListRdnsRecordsResponseContent> {
        const response = await this.listRdnsRecordsRaw(initOverrides);
        return await response.value();
    }

}
