/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  BadRequestErrorResponseContent,
  CheckDomainAvailabilityRequestContent,
  CheckDomainAvailabilityResponseContent,
  ForbiddenErrorResponseContent,
  GetDomainContactsRequestContent,
  GetDomainContactsResponseContent,
  GetDomainRequestContent,
  GetDomainResponseContent,
  InternalServiceErrorResponseContent,
  ListDnssecRecordsRequestContent,
  ListDnssecRecordsResponseContent,
  ListDomainsRequiringDataResponseContent,
  ListDomainsResponseContent,
  ResourceNotFoundErrorResponseContent,
  SaveDomainRequiredDataRequestContent,
  SaveDomainRequiredDataResponseContent,
  ServiceUnavailableErrorResponseContent,
  SuggestDomainsRequestContent,
  SuggestDomainsResponseContent,
  TooManyRequestsErrorResponseContent,
  UnauthorizedErrorResponseContent,
  UpdateDomainContactsRequestContent,
  UpdateDomainContactsResponseContent,
  UpdateDomainNameserversRequestContent,
  UpdateDomainNameserversResponseContent,
  UpdateDomainSettingsRequestContent,
  UpdateDomainSettingsResponseContent,
  ValidationErrorResponseContent,
} from '../models/index.js';
import {
    BadRequestErrorResponseContentFromJSON,
    BadRequestErrorResponseContentToJSON,
    CheckDomainAvailabilityRequestContentFromJSON,
    CheckDomainAvailabilityRequestContentToJSON,
    CheckDomainAvailabilityResponseContentFromJSON,
    CheckDomainAvailabilityResponseContentToJSON,
    ForbiddenErrorResponseContentFromJSON,
    ForbiddenErrorResponseContentToJSON,
    GetDomainContactsRequestContentFromJSON,
    GetDomainContactsRequestContentToJSON,
    GetDomainContactsResponseContentFromJSON,
    GetDomainContactsResponseContentToJSON,
    GetDomainRequestContentFromJSON,
    GetDomainRequestContentToJSON,
    GetDomainResponseContentFromJSON,
    GetDomainResponseContentToJSON,
    InternalServiceErrorResponseContentFromJSON,
    InternalServiceErrorResponseContentToJSON,
    ListDnssecRecordsRequestContentFromJSON,
    ListDnssecRecordsRequestContentToJSON,
    ListDnssecRecordsResponseContentFromJSON,
    ListDnssecRecordsResponseContentToJSON,
    ListDomainsRequiringDataResponseContentFromJSON,
    ListDomainsRequiringDataResponseContentToJSON,
    ListDomainsResponseContentFromJSON,
    ListDomainsResponseContentToJSON,
    ResourceNotFoundErrorResponseContentFromJSON,
    ResourceNotFoundErrorResponseContentToJSON,
    SaveDomainRequiredDataRequestContentFromJSON,
    SaveDomainRequiredDataRequestContentToJSON,
    SaveDomainRequiredDataResponseContentFromJSON,
    SaveDomainRequiredDataResponseContentToJSON,
    ServiceUnavailableErrorResponseContentFromJSON,
    ServiceUnavailableErrorResponseContentToJSON,
    SuggestDomainsRequestContentFromJSON,
    SuggestDomainsRequestContentToJSON,
    SuggestDomainsResponseContentFromJSON,
    SuggestDomainsResponseContentToJSON,
    TooManyRequestsErrorResponseContentFromJSON,
    TooManyRequestsErrorResponseContentToJSON,
    UnauthorizedErrorResponseContentFromJSON,
    UnauthorizedErrorResponseContentToJSON,
    UpdateDomainContactsRequestContentFromJSON,
    UpdateDomainContactsRequestContentToJSON,
    UpdateDomainContactsResponseContentFromJSON,
    UpdateDomainContactsResponseContentToJSON,
    UpdateDomainNameserversRequestContentFromJSON,
    UpdateDomainNameserversRequestContentToJSON,
    UpdateDomainNameserversResponseContentFromJSON,
    UpdateDomainNameserversResponseContentToJSON,
    UpdateDomainSettingsRequestContentFromJSON,
    UpdateDomainSettingsRequestContentToJSON,
    UpdateDomainSettingsResponseContentFromJSON,
    UpdateDomainSettingsResponseContentToJSON,
    ValidationErrorResponseContentFromJSON,
    ValidationErrorResponseContentToJSON,
} from '../models/index.js';

export interface CheckDomainAvailabilityRequest {
    checkDomainAvailabilityRequestContent?: CheckDomainAvailabilityRequestContent;
}

export interface GetDomainRequest {
    getDomainRequestContent: GetDomainRequestContent;
}

export interface GetDomainContactsRequest {
    getDomainContactsRequestContent: GetDomainContactsRequestContent;
}

export interface ListDnssecRecordsRequest {
    listDnssecRecordsRequestContent: ListDnssecRecordsRequestContent;
}

export interface SaveDomainRequiredDataRequest {
    saveDomainRequiredDataRequestContent: SaveDomainRequiredDataRequestContent;
}

export interface SuggestDomainsRequest {
    suggestDomainsRequestContent: SuggestDomainsRequestContent;
}

export interface UpdateDomainContactsRequest {
    updateDomainContactsRequestContent: UpdateDomainContactsRequestContent;
}

export interface UpdateDomainNameserversRequest {
    updateDomainNameserversRequestContent: UpdateDomainNameserversRequestContent;
}

export interface UpdateDomainSettingsRequest {
    updateDomainSettingsRequestContent: UpdateDomainSettingsRequestContent;
}

/**
 * 
 */
export class DomainsApi extends runtime.BaseAPI {

    /**
     * Creates request options for checkDomainAvailability without sending the request
     */
    async checkDomainAvailabilityRequestOpts(requestParameters: CheckDomainAvailabilityRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/domain/check-availability`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CheckDomainAvailabilityRequestContentToJSON(requestParameters['checkDomainAvailabilityRequestContent']),
        };
    }

    /**
     * Checks domain name availability for a single domain or a comma-separated batch. Exactly one of domain or domains must be provided. Returns pricing, suggestions, and register_url scoped to the requested currency.
     */
    async checkDomainAvailabilityRaw(requestParameters: CheckDomainAvailabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CheckDomainAvailabilityResponseContent>> {
        const requestOptions = await this.checkDomainAvailabilityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CheckDomainAvailabilityResponseContentFromJSON(jsonValue));
    }

    /**
     * Checks domain name availability for a single domain or a comma-separated batch. Exactly one of domain or domains must be provided. Returns pricing, suggestions, and register_url scoped to the requested currency.
     */
    async checkDomainAvailability(requestParameters: CheckDomainAvailabilityRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CheckDomainAvailabilityResponseContent> {
        const response = await this.checkDomainAvailabilityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDomain without sending the request
     */
    async getDomainRequestOpts(requestParameters: GetDomainRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['getDomainRequestContent'] == null) {
            throw new runtime.RequiredError(
                'getDomainRequestContent',
                'Required parameter "getDomainRequestContent" was null or undefined when calling getDomain().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/domain/get-domain`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetDomainRequestContentToJSON(requestParameters['getDomainRequestContent']),
        };
    }

    /**
     * Gets details for an owned domain.
     */
    async getDomainRaw(requestParameters: GetDomainRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetDomainResponseContent>> {
        const requestOptions = await this.getDomainRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetDomainResponseContentFromJSON(jsonValue));
    }

    /**
     * Gets details for an owned domain.
     */
    async getDomain(requestParameters: GetDomainRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetDomainResponseContent> {
        const response = await this.getDomainRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDomainContacts without sending the request
     */
    async getDomainContactsRequestOpts(requestParameters: GetDomainContactsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['getDomainContactsRequestContent'] == null) {
            throw new runtime.RequiredError(
                'getDomainContactsRequestContent',
                'Required parameter "getDomainContactsRequestContent" was null or undefined when calling getDomainContacts().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/domain/get-domain-contacts`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetDomainContactsRequestContentToJSON(requestParameters['getDomainContactsRequestContent']),
        };
    }

    /**
     * Retrieves WHOIS contact information for an owned domain. Contact field names vary by TLD and registrar; use the returned structure when building custom contact update payloads.
     */
    async getDomainContactsRaw(requestParameters: GetDomainContactsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetDomainContactsResponseContent>> {
        const requestOptions = await this.getDomainContactsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetDomainContactsResponseContentFromJSON(jsonValue));
    }

    /**
     * Retrieves WHOIS contact information for an owned domain. Contact field names vary by TLD and registrar; use the returned structure when building custom contact update payloads.
     */
    async getDomainContacts(requestParameters: GetDomainContactsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetDomainContactsResponseContent> {
        const response = await this.getDomainContactsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listDnssecRecords without sending the request
     */
    async listDnssecRecordsRequestOpts(requestParameters: ListDnssecRecordsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['listDnssecRecordsRequestContent'] == null) {
            throw new runtime.RequiredError(
                'listDnssecRecordsRequestContent',
                'Required parameter "listDnssecRecordsRequestContent" was null or undefined when calling listDnssecRecords().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/domain/list-dnssec-records`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ListDnssecRecordsRequestContentToJSON(requestParameters['listDnssecRecordsRequestContent']),
        };
    }

    /**
     * Lists DNSSEC DS records configured for an owned domain.
     */
    async listDnssecRecordsRaw(requestParameters: ListDnssecRecordsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListDnssecRecordsResponseContent>> {
        const requestOptions = await this.listDnssecRecordsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListDnssecRecordsResponseContentFromJSON(jsonValue));
    }

    /**
     * Lists DNSSEC DS records configured for an owned domain.
     */
    async listDnssecRecords(requestParameters: ListDnssecRecordsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListDnssecRecordsResponseContent> {
        const response = await this.listDnssecRecordsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listDomains without sending the request
     */
    async listDomainsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/domain/list-domains`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all domains belonging to the authenticated client.
     */
    async listDomainsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListDomainsResponseContent>> {
        const requestOptions = await this.listDomainsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListDomainsResponseContentFromJSON(jsonValue));
    }

    /**
     * List all domains belonging to the authenticated client.
     */
    async listDomains(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListDomainsResponseContent> {
        const response = await this.listDomainsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listDomainsRequiringData without sending the request
     */
    async listDomainsRequiringDataRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/domain/list-domains-requiring-data`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lists domains belonging to the authenticated client that require additional registrar or contact data.
     */
    async listDomainsRequiringDataRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListDomainsRequiringDataResponseContent>> {
        const requestOptions = await this.listDomainsRequiringDataRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListDomainsRequiringDataResponseContentFromJSON(jsonValue));
    }

    /**
     * Lists domains belonging to the authenticated client that require additional registrar or contact data.
     */
    async listDomainsRequiringData(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListDomainsRequiringDataResponseContent> {
        const response = await this.listDomainsRequiringDataRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for saveDomainRequiredData without sending the request
     */
    async saveDomainRequiredDataRequestOpts(requestParameters: SaveDomainRequiredDataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['saveDomainRequiredDataRequestContent'] == null) {
            throw new runtime.RequiredError(
                'saveDomainRequiredDataRequestContent',
                'Required parameter "saveDomainRequiredDataRequestContent" was null or undefined when calling saveDomainRequiredData().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/domain/save-domain-required-data`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SaveDomainRequiredDataRequestContentToJSON(requestParameters['saveDomainRequiredDataRequestContent']),
        };
    }

    /**
     * Saves additional registrar field values for a pending domain. Keys must match additionalFields[].name from list-domains-requiring-data.
     */
    async saveDomainRequiredDataRaw(requestParameters: SaveDomainRequiredDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaveDomainRequiredDataResponseContent>> {
        const requestOptions = await this.saveDomainRequiredDataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SaveDomainRequiredDataResponseContentFromJSON(jsonValue));
    }

    /**
     * Saves additional registrar field values for a pending domain. Keys must match additionalFields[].name from list-domains-requiring-data.
     */
    async saveDomainRequiredData(requestParameters: SaveDomainRequiredDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaveDomainRequiredDataResponseContent> {
        const response = await this.saveDomainRequiredDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for suggestDomains without sending the request
     */
    async suggestDomainsRequestOpts(requestParameters: SuggestDomainsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['suggestDomainsRequestContent'] == null) {
            throw new runtime.RequiredError(
                'suggestDomainsRequestContent',
                'Required parameter "suggestDomainsRequestContent" was null or undefined when calling suggestDomains().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/domain/suggest`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SuggestDomainsRequestContentToJSON(requestParameters['suggestDomainsRequestContent']),
        };
    }

    /**
     * Generates AI-powered domain name suggestions from a natural-language description. Returns suggested domains with availability status and pricing.
     */
    async suggestDomainsRaw(requestParameters: SuggestDomainsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuggestDomainsResponseContent>> {
        const requestOptions = await this.suggestDomainsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuggestDomainsResponseContentFromJSON(jsonValue));
    }

    /**
     * Generates AI-powered domain name suggestions from a natural-language description. Returns suggested domains with availability status and pricing.
     */
    async suggestDomains(requestParameters: SuggestDomainsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuggestDomainsResponseContent> {
        const response = await this.suggestDomainsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateDomainContacts without sending the request
     */
    async updateDomainContactsRequestOpts(requestParameters: UpdateDomainContactsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['updateDomainContactsRequestContent'] == null) {
            throw new runtime.RequiredError(
                'updateDomainContactsRequestContent',
                'Required parameter "updateDomainContactsRequestContent" was null or undefined when calling updateDomainContacts().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/domain/update-domain-contacts`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateDomainContactsRequestContentToJSON(requestParameters['updateDomainContactsRequestContent']),
        };
    }

    /**
     * Updates WHOIS contact information for an owned domain. Each role (Registrant, Admin, Tech, Billing) uses a source type: owner (client profile), contact (saved WHMCS contact id), or custom (inline WHOIS fields). WHOIS values must be nested under fields; for owner and contact they are flattened upstream when present.
     */
    async updateDomainContactsRaw(requestParameters: UpdateDomainContactsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateDomainContactsResponseContent>> {
        const requestOptions = await this.updateDomainContactsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateDomainContactsResponseContentFromJSON(jsonValue));
    }

    /**
     * Updates WHOIS contact information for an owned domain. Each role (Registrant, Admin, Tech, Billing) uses a source type: owner (client profile), contact (saved WHMCS contact id), or custom (inline WHOIS fields). WHOIS values must be nested under fields; for owner and contact they are flattened upstream when present.
     */
    async updateDomainContacts(requestParameters: UpdateDomainContactsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateDomainContactsResponseContent> {
        const response = await this.updateDomainContactsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateDomainNameservers without sending the request
     */
    async updateDomainNameserversRequestOpts(requestParameters: UpdateDomainNameserversRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['updateDomainNameserversRequestContent'] == null) {
            throw new runtime.RequiredError(
                'updateDomainNameserversRequestContent',
                'Required parameter "updateDomainNameserversRequestContent" was null or undefined when calling updateDomainNameservers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/domain/update-nameservers`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateDomainNameserversRequestContentToJSON(requestParameters['updateDomainNameserversRequestContent']),
        };
    }

    /**
     * Updates nameservers for an owned domain. ns1 and ns2 are required; ns3 through ns5 are optional.
     */
    async updateDomainNameserversRaw(requestParameters: UpdateDomainNameserversRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateDomainNameserversResponseContent>> {
        const requestOptions = await this.updateDomainNameserversRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateDomainNameserversResponseContentFromJSON(jsonValue));
    }

    /**
     * Updates nameservers for an owned domain. ns1 and ns2 are required; ns3 through ns5 are optional.
     */
    async updateDomainNameservers(requestParameters: UpdateDomainNameserversRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateDomainNameserversResponseContent> {
        const response = await this.updateDomainNameserversRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateDomainSettings without sending the request
     */
    async updateDomainSettingsRequestOpts(requestParameters: UpdateDomainSettingsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['updateDomainSettingsRequestContent'] == null) {
            throw new runtime.RequiredError(
                'updateDomainSettingsRequestContent',
                'Required parameter "updateDomainSettingsRequestContent" was null or undefined when calling updateDomainSettings().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/domain/update-domain-settings`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateDomainSettingsRequestContentToJSON(requestParameters['updateDomainSettingsRequestContent']),
        };
    }

    /**
     * Updates a single domain setting (auto-renew, ID protection, or paid addons). One setting per request.
     */
    async updateDomainSettingsRaw(requestParameters: UpdateDomainSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateDomainSettingsResponseContent>> {
        const requestOptions = await this.updateDomainSettingsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateDomainSettingsResponseContentFromJSON(jsonValue));
    }

    /**
     * Updates a single domain setting (auto-renew, ID protection, or paid addons). One setting per request.
     */
    async updateDomainSettings(requestParameters: UpdateDomainSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateDomainSettingsResponseContent> {
        const response = await this.updateDomainSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
