/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  BadRequestErrorResponseContent,
  ChangePasswordRequestContent,
  ChangePasswordResponseContent,
  ForbiddenErrorResponseContent,
  GetPrivateSshKeyRequestContent,
  GetPrivateSshKeyResponseContent,
  GetPublicSshKeyRequestContent,
  GetPublicSshKeyResponseContent,
  InternalServiceErrorResponseContent,
  InvalidStateErrorResponseContent,
  ResourceNotFoundErrorResponseContent,
  ServiceUnavailableErrorResponseContent,
  TooManyRequestsErrorResponseContent,
  UnauthorizedErrorResponseContent,
  UpdateSshKeysRequestContent,
  UpdateSshKeysResponseContent,
  ValidationErrorResponseContent,
} from '../models/index.js';
import {
    BadRequestErrorResponseContentFromJSON,
    BadRequestErrorResponseContentToJSON,
    ChangePasswordRequestContentFromJSON,
    ChangePasswordRequestContentToJSON,
    ChangePasswordResponseContentFromJSON,
    ChangePasswordResponseContentToJSON,
    ForbiddenErrorResponseContentFromJSON,
    ForbiddenErrorResponseContentToJSON,
    GetPrivateSshKeyRequestContentFromJSON,
    GetPrivateSshKeyRequestContentToJSON,
    GetPrivateSshKeyResponseContentFromJSON,
    GetPrivateSshKeyResponseContentToJSON,
    GetPublicSshKeyRequestContentFromJSON,
    GetPublicSshKeyRequestContentToJSON,
    GetPublicSshKeyResponseContentFromJSON,
    GetPublicSshKeyResponseContentToJSON,
    InternalServiceErrorResponseContentFromJSON,
    InternalServiceErrorResponseContentToJSON,
    InvalidStateErrorResponseContentFromJSON,
    InvalidStateErrorResponseContentToJSON,
    ResourceNotFoundErrorResponseContentFromJSON,
    ResourceNotFoundErrorResponseContentToJSON,
    ServiceUnavailableErrorResponseContentFromJSON,
    ServiceUnavailableErrorResponseContentToJSON,
    TooManyRequestsErrorResponseContentFromJSON,
    TooManyRequestsErrorResponseContentToJSON,
    UnauthorizedErrorResponseContentFromJSON,
    UnauthorizedErrorResponseContentToJSON,
    UpdateSshKeysRequestContentFromJSON,
    UpdateSshKeysRequestContentToJSON,
    UpdateSshKeysResponseContentFromJSON,
    UpdateSshKeysResponseContentToJSON,
    ValidationErrorResponseContentFromJSON,
    ValidationErrorResponseContentToJSON,
} from '../models/index.js';

export interface ChangePasswordRequest {
    changePasswordRequestContent: ChangePasswordRequestContent;
}

export interface GetPrivateSshKeyRequest {
    getPrivateSshKeyRequestContent: GetPrivateSshKeyRequestContent;
}

export interface GetPublicSshKeyRequest {
    getPublicSshKeyRequestContent: GetPublicSshKeyRequestContent;
}

export interface UpdateSshKeysRequest {
    updateSshKeysRequestContent: UpdateSshKeysRequestContent;
}

/**
 * 
 */
export class SecurityApi extends runtime.BaseAPI {

    /**
     * Creates request options for changePassword without sending the request
     */
    async changePasswordRequestOpts(requestParameters: ChangePasswordRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['changePasswordRequestContent'] == null) {
            throw new runtime.RequiredError(
                'changePasswordRequestContent',
                'Required parameter "changePasswordRequestContent" was null or undefined when calling changePassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vps/change-password`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChangePasswordRequestContentToJSON(requestParameters['changePasswordRequestContent']),
        };
    }

    /**
     * Change the root password for a VPS service
     */
    async changePasswordRaw(requestParameters: ChangePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChangePasswordResponseContent>> {
        const requestOptions = await this.changePasswordRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChangePasswordResponseContentFromJSON(jsonValue));
    }

    /**
     * Change the root password for a VPS service
     */
    async changePassword(requestParameters: ChangePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChangePasswordResponseContent> {
        const response = await this.changePasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPrivateSshKey without sending the request
     */
    async getPrivateSshKeyRequestOpts(requestParameters: GetPrivateSshKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['getPrivateSshKeyRequestContent'] == null) {
            throw new runtime.RequiredError(
                'getPrivateSshKeyRequestContent',
                'Required parameter "getPrivateSshKeyRequestContent" was null or undefined when calling getPrivateSshKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vps/get-private-ssh-keys`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetPrivateSshKeyRequestContentToJSON(requestParameters['getPrivateSshKeyRequestContent']),
        };
    }

    /**
     * Retrieves the private SSH key configured for a VPS service
     */
    async getPrivateSshKeyRaw(requestParameters: GetPrivateSshKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPrivateSshKeyResponseContent>> {
        const requestOptions = await this.getPrivateSshKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPrivateSshKeyResponseContentFromJSON(jsonValue));
    }

    /**
     * Retrieves the private SSH key configured for a VPS service
     */
    async getPrivateSshKey(requestParameters: GetPrivateSshKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPrivateSshKeyResponseContent> {
        const response = await this.getPrivateSshKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPublicSshKey without sending the request
     */
    async getPublicSshKeyRequestOpts(requestParameters: GetPublicSshKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['getPublicSshKeyRequestContent'] == null) {
            throw new runtime.RequiredError(
                'getPublicSshKeyRequestContent',
                'Required parameter "getPublicSshKeyRequestContent" was null or undefined when calling getPublicSshKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vps/get-public-ssh-keys`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetPublicSshKeyRequestContentToJSON(requestParameters['getPublicSshKeyRequestContent']),
        };
    }

    /**
     * Retrieves the public SSH key configured for a VPS service
     */
    async getPublicSshKeyRaw(requestParameters: GetPublicSshKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPublicSshKeyResponseContent>> {
        const requestOptions = await this.getPublicSshKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPublicSshKeyResponseContentFromJSON(jsonValue));
    }

    /**
     * Retrieves the public SSH key configured for a VPS service
     */
    async getPublicSshKey(requestParameters: GetPublicSshKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPublicSshKeyResponseContent> {
        const response = await this.getPublicSshKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateSshKeys without sending the request
     */
    async updateSshKeysRequestOpts(requestParameters: UpdateSshKeysRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['updateSshKeysRequestContent'] == null) {
            throw new runtime.RequiredError(
                'updateSshKeysRequestContent',
                'Required parameter "updateSshKeysRequestContent" was null or undefined when calling updateSshKeys().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vps/update-ssh-keys`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSshKeysRequestContentToJSON(requestParameters['updateSshKeysRequestContent']),
        };
    }

    /**
     * Updates SSH public keys for a VPS service for root access.
     */
    async updateSshKeysRaw(requestParameters: UpdateSshKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateSshKeysResponseContent>> {
        const requestOptions = await this.updateSshKeysRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateSshKeysResponseContentFromJSON(jsonValue));
    }

    /**
     * Updates SSH public keys for a VPS service for root access.
     */
    async updateSshKeys(requestParameters: UpdateSshKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateSshKeysResponseContent> {
        const response = await this.updateSshKeysRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
