/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  BadRequestErrorResponseContent,
  ForbiddenErrorResponseContent,
  GetVpsConfigRequestContent,
  GetVpsConfigResponseContent,
  GetVpsDetailsRequestContent,
  GetVpsDetailsResponseContent,
  InternalServiceErrorResponseContent,
  InvalidStateErrorResponseContent,
  ListIsosRequestContent,
  ListIsosResponseContent,
  ListReinstallOsRequestContent,
  ListReinstallOsResponseContent,
  ListVpsServicesResponseContent,
  MountIsoRequestContent,
  MountIsoResponseContent,
  ResourceNotFoundErrorResponseContent,
  ServiceUnavailableErrorResponseContent,
  TooManyRequestsErrorResponseContent,
  TriggerReinstallRequestContent,
  TriggerReinstallResponseContent,
  UnauthorizedErrorResponseContent,
  UpdateVpsConfigRequestContent,
  UpdateVpsConfigResponseContent,
  ValidationErrorResponseContent,
} from '../models/index.js';
import {
    BadRequestErrorResponseContentFromJSON,
    BadRequestErrorResponseContentToJSON,
    ForbiddenErrorResponseContentFromJSON,
    ForbiddenErrorResponseContentToJSON,
    GetVpsConfigRequestContentFromJSON,
    GetVpsConfigRequestContentToJSON,
    GetVpsConfigResponseContentFromJSON,
    GetVpsConfigResponseContentToJSON,
    GetVpsDetailsRequestContentFromJSON,
    GetVpsDetailsRequestContentToJSON,
    GetVpsDetailsResponseContentFromJSON,
    GetVpsDetailsResponseContentToJSON,
    InternalServiceErrorResponseContentFromJSON,
    InternalServiceErrorResponseContentToJSON,
    InvalidStateErrorResponseContentFromJSON,
    InvalidStateErrorResponseContentToJSON,
    ListIsosRequestContentFromJSON,
    ListIsosRequestContentToJSON,
    ListIsosResponseContentFromJSON,
    ListIsosResponseContentToJSON,
    ListReinstallOsRequestContentFromJSON,
    ListReinstallOsRequestContentToJSON,
    ListReinstallOsResponseContentFromJSON,
    ListReinstallOsResponseContentToJSON,
    ListVpsServicesResponseContentFromJSON,
    ListVpsServicesResponseContentToJSON,
    MountIsoRequestContentFromJSON,
    MountIsoRequestContentToJSON,
    MountIsoResponseContentFromJSON,
    MountIsoResponseContentToJSON,
    ResourceNotFoundErrorResponseContentFromJSON,
    ResourceNotFoundErrorResponseContentToJSON,
    ServiceUnavailableErrorResponseContentFromJSON,
    ServiceUnavailableErrorResponseContentToJSON,
    TooManyRequestsErrorResponseContentFromJSON,
    TooManyRequestsErrorResponseContentToJSON,
    TriggerReinstallRequestContentFromJSON,
    TriggerReinstallRequestContentToJSON,
    TriggerReinstallResponseContentFromJSON,
    TriggerReinstallResponseContentToJSON,
    UnauthorizedErrorResponseContentFromJSON,
    UnauthorizedErrorResponseContentToJSON,
    UpdateVpsConfigRequestContentFromJSON,
    UpdateVpsConfigRequestContentToJSON,
    UpdateVpsConfigResponseContentFromJSON,
    UpdateVpsConfigResponseContentToJSON,
    ValidationErrorResponseContentFromJSON,
    ValidationErrorResponseContentToJSON,
} from '../models/index.js';

export interface GetVpsConfigRequest {
    getVpsConfigRequestContent: GetVpsConfigRequestContent;
}

export interface GetVpsDetailsRequest {
    getVpsDetailsRequestContent: GetVpsDetailsRequestContent;
}

export interface ListIsosRequest {
    listIsosRequestContent: ListIsosRequestContent;
}

export interface ListReinstallOsRequest {
    listReinstallOsRequestContent: ListReinstallOsRequestContent;
}

export interface MountIsoRequest {
    mountIsoRequestContent: MountIsoRequestContent;
}

export interface TriggerReinstallRequest {
    triggerReinstallRequestContent: TriggerReinstallRequestContent;
}

export interface UpdateVpsConfigRequest {
    updateVpsConfigRequestContent: UpdateVpsConfigRequestContent;
}

/**
 * 
 */
export class VPSManagementApi extends runtime.BaseAPI {

    /**
     * Creates request options for getVpsConfig without sending the request
     */
    async getVpsConfigRequestOpts(requestParameters: GetVpsConfigRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['getVpsConfigRequestContent'] == null) {
            throw new runtime.RequiredError(
                'getVpsConfigRequestContent',
                'Required parameter "getVpsConfigRequestContent" was null or undefined when calling getVpsConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vps/get-config`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetVpsConfigRequestContentToJSON(requestParameters['getVpsConfigRequestContent']),
        };
    }

    /**
     * Retrieves VPS configuration settings including name, hostname, auto-start, boot order, and CD-ROM
     */
    async getVpsConfigRaw(requestParameters: GetVpsConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetVpsConfigResponseContent>> {
        const requestOptions = await this.getVpsConfigRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetVpsConfigResponseContentFromJSON(jsonValue));
    }

    /**
     * Retrieves VPS configuration settings including name, hostname, auto-start, boot order, and CD-ROM
     */
    async getVpsConfig(requestParameters: GetVpsConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetVpsConfigResponseContent> {
        const response = await this.getVpsConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getVpsDetails without sending the request
     */
    async getVpsDetailsRequestOpts(requestParameters: GetVpsDetailsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['getVpsDetailsRequestContent'] == null) {
            throw new runtime.RequiredError(
                'getVpsDetailsRequestContent',
                'Required parameter "getVpsDetailsRequestContent" was null or undefined when calling getVpsDetails().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vps/get-details`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetVpsDetailsRequestContentToJSON(requestParameters['getVpsDetailsRequestContent']),
        };
    }

    /**
     * Gets detailed information about a VPS service including configuration, network settings, and statistics
     */
    async getVpsDetailsRaw(requestParameters: GetVpsDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetVpsDetailsResponseContent>> {
        const requestOptions = await this.getVpsDetailsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetVpsDetailsResponseContentFromJSON(jsonValue));
    }

    /**
     * Gets detailed information about a VPS service including configuration, network settings, and statistics
     */
    async getVpsDetails(requestParameters: GetVpsDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetVpsDetailsResponseContent> {
        const response = await this.getVpsDetailsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listIsos without sending the request
     */
    async listIsosRequestOpts(requestParameters: ListIsosRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['listIsosRequestContent'] == null) {
            throw new runtime.RequiredError(
                'listIsosRequestContent',
                'Required parameter "listIsosRequestContent" was null or undefined when calling listIsos().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vps/list-isos`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ListIsosRequestContentToJSON(requestParameters['listIsosRequestContent']),
        };
    }

    /**
     * Retrieves the list of available ISO images for a VPS service
     */
    async listIsosRaw(requestParameters: ListIsosRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListIsosResponseContent>> {
        const requestOptions = await this.listIsosRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListIsosResponseContentFromJSON(jsonValue));
    }

    /**
     * Retrieves the list of available ISO images for a VPS service
     */
    async listIsos(requestParameters: ListIsosRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListIsosResponseContent> {
        const response = await this.listIsosRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listReinstallOs without sending the request
     */
    async listReinstallOsRequestOpts(requestParameters: ListReinstallOsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['listReinstallOsRequestContent'] == null) {
            throw new runtime.RequiredError(
                'listReinstallOsRequestContent',
                'Required parameter "listReinstallOsRequestContent" was null or undefined when calling listReinstallOs().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vps/list-reinstall-images`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ListReinstallOsRequestContentToJSON(requestParameters['listReinstallOsRequestContent']),
        };
    }

    /**
     * Retrieves the list of available OS images for VPS reinstallation
     */
    async listReinstallOsRaw(requestParameters: ListReinstallOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListReinstallOsResponseContent>> {
        const requestOptions = await this.listReinstallOsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListReinstallOsResponseContentFromJSON(jsonValue));
    }

    /**
     * Retrieves the list of available OS images for VPS reinstallation
     */
    async listReinstallOs(requestParameters: ListReinstallOsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListReinstallOsResponseContent> {
        const response = await this.listReinstallOsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listVpsServices without sending the request
     */
    async listVpsServicesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vps/list-vps-services`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lists all VPS services accessible by the authenticated user
     */
    async listVpsServicesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListVpsServicesResponseContent>> {
        const requestOptions = await this.listVpsServicesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListVpsServicesResponseContentFromJSON(jsonValue));
    }

    /**
     * Lists all VPS services accessible by the authenticated user
     */
    async listVpsServices(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListVpsServicesResponseContent> {
        const response = await this.listVpsServicesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mountIso without sending the request
     */
    async mountIsoRequestOpts(requestParameters: MountIsoRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['mountIsoRequestContent'] == null) {
            throw new runtime.RequiredError(
                'mountIsoRequestContent',
                'Required parameter "mountIsoRequestContent" was null or undefined when calling mountIso().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vps/mount-iso`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MountIsoRequestContentToJSON(requestParameters['mountIsoRequestContent']),
        };
    }

    /**
     * Mounts an ISO image on a VPS service
     */
    async mountIsoRaw(requestParameters: MountIsoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MountIsoResponseContent>> {
        const requestOptions = await this.mountIsoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MountIsoResponseContentFromJSON(jsonValue));
    }

    /**
     * Mounts an ISO image on a VPS service
     */
    async mountIso(requestParameters: MountIsoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MountIsoResponseContent> {
        const response = await this.mountIsoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for triggerReinstall without sending the request
     */
    async triggerReinstallRequestOpts(requestParameters: TriggerReinstallRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['triggerReinstallRequestContent'] == null) {
            throw new runtime.RequiredError(
                'triggerReinstallRequestContent',
                'Required parameter "triggerReinstallRequestContent" was null or undefined when calling triggerReinstall().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vps/trigger-reinstall`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TriggerReinstallRequestContentToJSON(requestParameters['triggerReinstallRequestContent']),
        };
    }

    /**
     * Triggers a VPS reinstallation with the specified OS template
     */
    async triggerReinstallRaw(requestParameters: TriggerReinstallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TriggerReinstallResponseContent>> {
        const requestOptions = await this.triggerReinstallRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TriggerReinstallResponseContentFromJSON(jsonValue));
    }

    /**
     * Triggers a VPS reinstallation with the specified OS template
     */
    async triggerReinstall(requestParameters: TriggerReinstallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TriggerReinstallResponseContent> {
        const response = await this.triggerReinstallRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateVpsConfig without sending the request
     */
    async updateVpsConfigRequestOpts(requestParameters: UpdateVpsConfigRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['updateVpsConfigRequestContent'] == null) {
            throw new runtime.RequiredError(
                'updateVpsConfigRequestContent',
                'Required parameter "updateVpsConfigRequestContent" was null or undefined when calling updateVpsConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/vps/update-config`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateVpsConfigRequestContentToJSON(requestParameters['updateVpsConfigRequestContent']),
        };
    }

    /**
     * Updates VPS configuration settings such as name, hostname, auto-start, boot order, and CD-ROM
     */
    async updateVpsConfigRaw(requestParameters: UpdateVpsConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateVpsConfigResponseContent>> {
        const requestOptions = await this.updateVpsConfigRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateVpsConfigResponseContentFromJSON(jsonValue));
    }

    /**
     * Updates VPS configuration settings such as name, hostname, auto-start, boot order, and CD-ROM
     */
    async updateVpsConfig(requestParameters: UpdateVpsConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateVpsConfigResponseContent> {
        const response = await this.updateVpsConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
