/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { BackupCreationInfo } from './BackupCreationInfo.js';
import {
    BackupCreationInfoFromJSON,
    BackupCreationInfoFromJSONTyped,
    BackupCreationInfoToJSON,
    BackupCreationInfoToJSONTyped,
} from './BackupCreationInfo.js';

/**
 * Response data for backup creation operation
 * @export
 * @interface BackupCreateResponseData
 */
export interface BackupCreateResponseData {
    /**
     * Status message indicating the result
     * @type {string}
     * @memberof BackupCreateResponseData
     */
    message: string;
    /**
     * Task ID for the backup creation process
     * @type {number}
     * @memberof BackupCreateResponseData
     */
    taskId: number;
    /**
     * Whether a backup is currently being created
     * @type {boolean}
     * @memberof BackupCreateResponseData
     */
    backupIsCreating: boolean;
    /**
     * 
     * @type {BackupCreationInfo}
     * @memberof BackupCreateResponseData
     */
    backupCreation: BackupCreationInfo;
}

/**
 * Check if a given object implements the BackupCreateResponseData interface.
 */
export function instanceOfBackupCreateResponseData(value: object): value is BackupCreateResponseData {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    if (!('backupIsCreating' in value) || value['backupIsCreating'] === undefined) return false;
    if (!('backupCreation' in value) || value['backupCreation'] === undefined) return false;
    return true;
}

export function BackupCreateResponseDataFromJSON(json: any): BackupCreateResponseData {
    return BackupCreateResponseDataFromJSONTyped(json, false);
}

export function BackupCreateResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackupCreateResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'taskId': json['task_id'],
        'backupIsCreating': json['backup_is_creating'],
        'backupCreation': BackupCreationInfoFromJSON(json['backup_creation']),
    };
}

export function BackupCreateResponseDataToJSON(json: any): BackupCreateResponseData {
    return BackupCreateResponseDataToJSONTyped(json, false);
}

export function BackupCreateResponseDataToJSONTyped(value?: BackupCreateResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'task_id': value['taskId'],
        'backup_is_creating': value['backupIsCreating'],
        'backup_creation': BackupCreationInfoToJSON(value['backupCreation']),
    };
}

