/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BadRequestErrorResponseContent
 */
export interface BadRequestErrorResponseContent {
    /**
     * 
     * @type {string}
     * @memberof BadRequestErrorResponseContent
     */
    message: string;
    /**
     * Empty object for operations that don't return data
     * @type {object}
     * @memberof BadRequestErrorResponseContent
     */
    data: object;
}

/**
 * Check if a given object implements the BadRequestErrorResponseContent interface.
 */
export function instanceOfBadRequestErrorResponseContent(value: object): value is BadRequestErrorResponseContent {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function BadRequestErrorResponseContentFromJSON(json: any): BadRequestErrorResponseContent {
    return BadRequestErrorResponseContentFromJSONTyped(json, false);
}

export function BadRequestErrorResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): BadRequestErrorResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'data': json['data'],
    };
}

export function BadRequestErrorResponseContentToJSON(json: any): BadRequestErrorResponseContent {
    return BadRequestErrorResponseContentToJSONTyped(json, false);
}

export function BadRequestErrorResponseContentToJSONTyped(value?: BadRequestErrorResponseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'data': value['data'],
    };
}

