/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { VpsCancelType } from './VpsCancelType.js';
import {
    VpsCancelTypeFromJSON,
    VpsCancelTypeFromJSONTyped,
    VpsCancelTypeToJSON,
    VpsCancelTypeToJSONTyped,
} from './VpsCancelType.js';

/**
 * 
 * @export
 * @interface CancelVpsRequestContent
 */
export interface CancelVpsRequestContent {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof CancelVpsRequestContent
     */
    serviceId: string;
    /**
     * 
     * @type {VpsCancelType}
     * @memberof CancelVpsRequestContent
     */
    type?: VpsCancelType;
}



/**
 * Check if a given object implements the CancelVpsRequestContent interface.
 */
export function instanceOfCancelVpsRequestContent(value: object): value is CancelVpsRequestContent {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    return true;
}

export function CancelVpsRequestContentFromJSON(json: any): CancelVpsRequestContent {
    return CancelVpsRequestContentFromJSONTyped(json, false);
}

export function CancelVpsRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelVpsRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
        'type': json['type'] == null ? undefined : VpsCancelTypeFromJSON(json['type']),
    };
}

export function CancelVpsRequestContentToJSON(json: any): CancelVpsRequestContent {
    return CancelVpsRequestContentToJSONTyped(json, false);
}

export function CancelVpsRequestContentToJSONTyped(value?: CancelVpsRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
        'type': VpsCancelTypeToJSON(value['type']),
    };
}

