/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A plan (size tier) available for a product
 * @export
 * @interface CataloguePlan
 */
export interface CataloguePlan {
    /**
     * Plan identifier
     * @type {number}
     * @memberof CataloguePlan
     */
    id: number;
    /**
     * Plan display name (e.g. C1, C2)
     * @type {string}
     * @memberof CataloguePlan
     */
    name: string;
    /**
     * Number of vCPUs
     * @type {number}
     * @memberof CataloguePlan
     */
    cpu: number;
    /**
     * RAM in GB
     * @type {number}
     * @memberof CataloguePlan
     */
    ram: number;
    /**
     * Disk size in GB
     * @type {number}
     * @memberof CataloguePlan
     */
    disk: number;
    /**
     * Bandwidth allowance in GB
     * @type {number}
     * @memberof CataloguePlan
     */
    bandwidth: number;
    /**
     * Number of included backup slots
     * @type {number}
     * @memberof CataloguePlan
     */
    backups: number;
    /**
     * Number of included snapshot slots
     * @type {number}
     * @memberof CataloguePlan
     */
    snapshots: number;
    /**
     * Per-cycle pricing for this plan
     * @type {any}
     * @memberof CataloguePlan
     */
    pricing: any | null;
}

/**
 * Check if a given object implements the CataloguePlan interface.
 */
export function instanceOfCataloguePlan(value: object): value is CataloguePlan {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('cpu' in value) || value['cpu'] === undefined) return false;
    if (!('ram' in value) || value['ram'] === undefined) return false;
    if (!('disk' in value) || value['disk'] === undefined) return false;
    if (!('bandwidth' in value) || value['bandwidth'] === undefined) return false;
    if (!('backups' in value) || value['backups'] === undefined) return false;
    if (!('snapshots' in value) || value['snapshots'] === undefined) return false;
    if (!('pricing' in value) || value['pricing'] === undefined) return false;
    return true;
}

export function CataloguePlanFromJSON(json: any): CataloguePlan {
    return CataloguePlanFromJSONTyped(json, false);
}

export function CataloguePlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): CataloguePlan {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'cpu': json['cpu'],
        'ram': json['ram'],
        'disk': json['disk'],
        'bandwidth': json['bandwidth'],
        'backups': json['backups'],
        'snapshots': json['snapshots'],
        'pricing': json['pricing'],
    };
}

export function CataloguePlanToJSON(json: any): CataloguePlan {
    return CataloguePlanToJSONTyped(json, false);
}

export function CataloguePlanToJSONTyped(value?: CataloguePlan | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'cpu': value['cpu'],
        'ram': value['ram'],
        'disk': value['disk'],
        'bandwidth': value['bandwidth'],
        'backups': value['backups'],
        'snapshots': value['snapshots'],
        'pricing': value['pricing'],
    };
}

