/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CatalogueProduct } from './CatalogueProduct.js';
import {
    CatalogueProductFromJSON,
    CatalogueProductFromJSONTyped,
    CatalogueProductToJSON,
    CatalogueProductToJSONTyped,
} from './CatalogueProduct.js';

/**
 * A product group in the catalogue
 * @export
 * @interface CatalogueGroup
 */
export interface CatalogueGroup {
    /**
     * Group identifier
     * @type {number}
     * @memberof CatalogueGroup
     */
    id: number;
    /**
     * Group display name (e.g. Linux Cloud Servers)
     * @type {string}
     * @memberof CatalogueGroup
     */
    name: string;
    /**
     * Products within this group
     * @type {Array<CatalogueProduct>}
     * @memberof CatalogueGroup
     */
    products: Array<CatalogueProduct>;
}

/**
 * Check if a given object implements the CatalogueGroup interface.
 */
export function instanceOfCatalogueGroup(value: object): value is CatalogueGroup {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('products' in value) || value['products'] === undefined) return false;
    return true;
}

export function CatalogueGroupFromJSON(json: any): CatalogueGroup {
    return CatalogueGroupFromJSONTyped(json, false);
}

export function CatalogueGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogueGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'products': ((json['products'] as Array<any>).map(CatalogueProductFromJSON)),
    };
}

export function CatalogueGroupToJSON(json: any): CatalogueGroup {
    return CatalogueGroupToJSONTyped(json, false);
}

export function CatalogueGroupToJSONTyped(value?: CatalogueGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'products': ((value['products'] as Array<any>).map(CatalogueProductToJSON)),
    };
}

