/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CheckDomainAvailabilityRequestContent
 */
export interface CheckDomainAvailabilityRequestContent {
    /**
     * A single domain name to look up, e.g. "example.co.za". Required unless domains is provided.
     * @type {string}
     * @memberof CheckDomainAvailabilityRequestContent
     */
    domain?: string;
    /**
     * Comma-separated list of domain names for a batch check. Required unless domain is provided.
     * @type {string}
     * @memberof CheckDomainAvailabilityRequestContent
     */
    domains?: string;
    /**
     * Currency for pricing. Accepts ISO code, symbol, country name, or numeric ID. Defaults to ZAR.
     * @type {string}
     * @memberof CheckDomainAvailabilityRequestContent
     */
    currency?: string;
}

/**
 * Check if a given object implements the CheckDomainAvailabilityRequestContent interface.
 */
export function instanceOfCheckDomainAvailabilityRequestContent(value: object): value is CheckDomainAvailabilityRequestContent {
    return true;
}

export function CheckDomainAvailabilityRequestContentFromJSON(json: any): CheckDomainAvailabilityRequestContent {
    return CheckDomainAvailabilityRequestContentFromJSONTyped(json, false);
}

export function CheckDomainAvailabilityRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckDomainAvailabilityRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': json['domain'] == null ? undefined : json['domain'],
        'domains': json['domains'] == null ? undefined : json['domains'],
        'currency': json['currency'] == null ? undefined : json['currency'],
    };
}

export function CheckDomainAvailabilityRequestContentToJSON(json: any): CheckDomainAvailabilityRequestContent {
    return CheckDomainAvailabilityRequestContentToJSONTyped(json, false);
}

export function CheckDomainAvailabilityRequestContentToJSONTyped(value?: CheckDomainAvailabilityRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domain': value['domain'],
        'domains': value['domains'],
        'currency': value['currency'],
    };
}

