/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { OperationStatus } from './OperationStatus.js';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus.js';
import type { DomainSearchResponseData } from './DomainSearchResponseData.js';
import {
    DomainSearchResponseDataFromJSON,
    DomainSearchResponseDataFromJSONTyped,
    DomainSearchResponseDataToJSON,
    DomainSearchResponseDataToJSONTyped,
} from './DomainSearchResponseData.js';

/**
 * 
 * @export
 * @interface CheckDomainAvailabilityResponseContent
 */
export interface CheckDomainAvailabilityResponseContent {
    /**
     * 
     * @type {OperationStatus}
     * @memberof CheckDomainAvailabilityResponseContent
     */
    status: OperationStatus;
    /**
     * 
     * @type {DomainSearchResponseData}
     * @memberof CheckDomainAvailabilityResponseContent
     */
    data: DomainSearchResponseData;
}



/**
 * Check if a given object implements the CheckDomainAvailabilityResponseContent interface.
 */
export function instanceOfCheckDomainAvailabilityResponseContent(value: object): value is CheckDomainAvailabilityResponseContent {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CheckDomainAvailabilityResponseContentFromJSON(json: any): CheckDomainAvailabilityResponseContent {
    return CheckDomainAvailabilityResponseContentFromJSONTyped(json, false);
}

export function CheckDomainAvailabilityResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckDomainAvailabilityResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': DomainSearchResponseDataFromJSON(json['data']),
    };
}

export function CheckDomainAvailabilityResponseContentToJSON(json: any): CheckDomainAvailabilityResponseContent {
    return CheckDomainAvailabilityResponseContentToJSONTyped(json, false);
}

export function CheckDomainAvailabilityResponseContentToJSONTyped(value?: CheckDomainAvailabilityResponseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': DomainSearchResponseDataToJSON(value['data']),
    };
}

