/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Backup compression type enum
 * @export
 */
export const CompressionType = {
    _0: '0',
    Lzo: 'lzo',
    Gzip: 'gzip',
    Zstd: 'zstd'
} as const;
export type CompressionType = typeof CompressionType[keyof typeof CompressionType];


export function instanceOfCompressionType(value: any): boolean {
    for (const key in CompressionType) {
        if (Object.prototype.hasOwnProperty.call(CompressionType, key)) {
            if (CompressionType[key as keyof typeof CompressionType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CompressionTypeFromJSON(json: any): CompressionType {
    return CompressionTypeFromJSONTyped(json, false);
}

export function CompressionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompressionType {
    return json as CompressionType;
}

export function CompressionTypeToJSON(value?: CompressionType | null): any {
    return value as any;
}

export function CompressionTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): CompressionType {
    return value as CompressionType;
}

