/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateOrderProduct } from './CreateOrderProduct';
import {
    CreateOrderProductFromJSON,
    CreateOrderProductFromJSONTyped,
    CreateOrderProductToJSON,
    CreateOrderProductToJSONTyped,
} from './CreateOrderProduct';

/**
 * 
 * @export
 * @interface CreateOrderInput
 */
export interface CreateOrderInput {
    /**
     * Promotional code to apply to the order
     * @type {string}
     * @memberof CreateOrderInput
     */
    promo?: string;
    /**
     * List of products to order
     * @type {Array<CreateOrderProduct>}
     * @memberof CreateOrderInput
     */
    products: Array<CreateOrderProduct>;
}

/**
 * Check if a given object implements the CreateOrderInput interface.
 */
export function instanceOfCreateOrderInput(value: object): value is CreateOrderInput {
    if (!('products' in value) || value['products'] === undefined) return false;
    return true;
}

export function CreateOrderInputFromJSON(json: any): CreateOrderInput {
    return CreateOrderInputFromJSONTyped(json, false);
}

export function CreateOrderInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderInput {
    if (json == null) {
        return json;
    }
    return {
        
        'promo': json['promo'] == null ? undefined : json['promo'],
        'products': ((json['products'] as Array<any>).map(CreateOrderProductFromJSON)),
    };
}

export function CreateOrderInputToJSON(json: any): CreateOrderInput {
    return CreateOrderInputToJSONTyped(json, false);
}

export function CreateOrderInputToJSONTyped(value?: CreateOrderInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'promo': value['promo'],
        'products': ((value['products'] as Array<any>).map(CreateOrderProductToJSON)),
    };
}

