/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SnapshotCreateResponseData } from './SnapshotCreateResponseData.js';
import {
    SnapshotCreateResponseDataFromJSON,
    SnapshotCreateResponseDataFromJSONTyped,
    SnapshotCreateResponseDataToJSON,
    SnapshotCreateResponseDataToJSONTyped,
} from './SnapshotCreateResponseData.js';
import type { OperationStatus } from './OperationStatus.js';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus.js';

/**
 * 
 * @export
 * @interface CreateSnapshotResponseContent
 */
export interface CreateSnapshotResponseContent {
    /**
     * 
     * @type {OperationStatus}
     * @memberof CreateSnapshotResponseContent
     */
    status: OperationStatus;
    /**
     * 
     * @type {SnapshotCreateResponseData}
     * @memberof CreateSnapshotResponseContent
     */
    data: SnapshotCreateResponseData;
}



/**
 * Check if a given object implements the CreateSnapshotResponseContent interface.
 */
export function instanceOfCreateSnapshotResponseContent(value: object): value is CreateSnapshotResponseContent {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreateSnapshotResponseContentFromJSON(json: any): CreateSnapshotResponseContent {
    return CreateSnapshotResponseContentFromJSONTyped(json, false);
}

export function CreateSnapshotResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSnapshotResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': SnapshotCreateResponseDataFromJSON(json['data']),
    };
}

export function CreateSnapshotResponseContentToJSON(json: any): CreateSnapshotResponseContent {
    return CreateSnapshotResponseContentToJSONTyped(json, false);
}

export function CreateSnapshotResponseContentToJSONTyped(value?: CreateSnapshotResponseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': SnapshotCreateResponseDataToJSON(value['data']),
    };
}

