/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OperationStatus } from './OperationStatus';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus';
import type { CreateOrderResponseData } from './CreateOrderResponseData';
import {
    CreateOrderResponseDataFromJSON,
    CreateOrderResponseDataFromJSONTyped,
    CreateOrderResponseDataToJSON,
    CreateOrderResponseDataToJSONTyped,
} from './CreateOrderResponseData';

/**
 * 
 * @export
 * @interface CreateOrderOutput
 */
export interface CreateOrderOutput {
    /**
     * 
     * @type {OperationStatus}
     * @memberof CreateOrderOutput
     */
    status: OperationStatus;
    /**
     * 
     * @type {CreateOrderResponseData}
     * @memberof CreateOrderOutput
     */
    data: CreateOrderResponseData;
}



/**
 * Check if a given object implements the CreateOrderOutput interface.
 */
export function instanceOfCreateOrderOutput(value: object): value is CreateOrderOutput {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreateOrderOutputFromJSON(json: any): CreateOrderOutput {
    return CreateOrderOutputFromJSONTyped(json, false);
}

export function CreateOrderOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': CreateOrderResponseDataFromJSON(json['data']),
    };
}

export function CreateOrderOutputToJSON(json: any): CreateOrderOutput {
    return CreateOrderOutputToJSONTyped(json, false);
}

export function CreateOrderOutputToJSONTyped(value?: CreateOrderOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': CreateOrderResponseDataToJSON(value['data']),
    };
}

