/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRdnsRecordRequestContent
 */
export interface CreateRdnsRecordRequestContent {
    /**
     * Zone type: 0=OTHER, 1=DOMAIN, 2=HOSTING, 3=ADDON
     * @type {number}
     * @memberof CreateRdnsRecordRequestContent
     */
    type: number;
    /**
     * Related service id matching the zone type (tblhosting.id, tblhostingaddons.id or tbldomains.id)
     * @type {number}
     * @memberof CreateRdnsRecordRequestContent
     */
    relid: number;
    /**
     * IPv4 or IPv6 address the PTR record should point from
     * @type {string}
     * @memberof CreateRdnsRecordRequestContent
     */
    ip: string;
    /**
     * PTR target hostname
     * @type {string}
     * @memberof CreateRdnsRecordRequestContent
     */
    hostname: string;
    /**
     * Time-to-live in seconds. Defaults to 14400; clamped to [30, 86400]
     * @type {number}
     * @memberof CreateRdnsRecordRequestContent
     */
    ttl?: number;
}

/**
 * Check if a given object implements the CreateRdnsRecordRequestContent interface.
 */
export function instanceOfCreateRdnsRecordRequestContent(value: object): value is CreateRdnsRecordRequestContent {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('relid' in value) || value['relid'] === undefined) return false;
    if (!('ip' in value) || value['ip'] === undefined) return false;
    if (!('hostname' in value) || value['hostname'] === undefined) return false;
    return true;
}

export function CreateRdnsRecordRequestContentFromJSON(json: any): CreateRdnsRecordRequestContent {
    return CreateRdnsRecordRequestContentFromJSONTyped(json, false);
}

export function CreateRdnsRecordRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRdnsRecordRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'relid': json['relid'],
        'ip': json['ip'],
        'hostname': json['hostname'],
        'ttl': json['ttl'] == null ? undefined : json['ttl'],
    };
}

export function CreateRdnsRecordRequestContentToJSON(json: any): CreateRdnsRecordRequestContent {
    return CreateRdnsRecordRequestContentToJSONTyped(json, false);
}

export function CreateRdnsRecordRequestContentToJSONTyped(value?: CreateRdnsRecordRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'relid': value['relid'],
        'ip': value['ip'],
        'hostname': value['hostname'],
        'ttl': value['ttl'],
    };
}

