/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OperationStatus } from './OperationStatus';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus';
import type { PowerTaskCreateResponseData } from './PowerTaskCreateResponseData';
import {
    PowerTaskCreateResponseDataFromJSON,
    PowerTaskCreateResponseDataFromJSONTyped,
    PowerTaskCreateResponseDataToJSON,
    PowerTaskCreateResponseDataToJSONTyped,
} from './PowerTaskCreateResponseData';

/**
 * 
 * @export
 * @interface CreatePowerTaskOutput
 */
export interface CreatePowerTaskOutput {
    /**
     * 
     * @type {OperationStatus}
     * @memberof CreatePowerTaskOutput
     */
    status: OperationStatus;
    /**
     * 
     * @type {PowerTaskCreateResponseData}
     * @memberof CreatePowerTaskOutput
     */
    data: PowerTaskCreateResponseData;
}



/**
 * Check if a given object implements the CreatePowerTaskOutput interface.
 */
export function instanceOfCreatePowerTaskOutput(value: object): value is CreatePowerTaskOutput {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreatePowerTaskOutputFromJSON(json: any): CreatePowerTaskOutput {
    return CreatePowerTaskOutputFromJSONTyped(json, false);
}

export function CreatePowerTaskOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePowerTaskOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': PowerTaskCreateResponseDataFromJSON(json['data']),
    };
}

export function CreatePowerTaskOutputToJSON(json: any): CreatePowerTaskOutput {
    return CreatePowerTaskOutputToJSONTyped(json, false);
}

export function CreatePowerTaskOutputToJSONTyped(value?: CreatePowerTaskOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': PowerTaskCreateResponseDataToJSON(value['data']),
    };
}

