/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompressionType } from './CompressionType';
import {
    CompressionTypeFromJSON,
    CompressionTypeFromJSONTyped,
    CompressionTypeToJSON,
    CompressionTypeToJSONTyped,
} from './CompressionType';

/**
 * 
 * @export
 * @interface CreateBackupScheduleRequestContent
 */
export interface CreateBackupScheduleRequestContent {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof CreateBackupScheduleRequestContent
     */
    serviceId: string;
    /**
     * Time in HH:MM format (e.g., '03:00'). Hours must be between 00-23, minutes must be between 00-59
     * @type {string}
     * @memberof CreateBackupScheduleRequestContent
     */
    starttime: string;
    /**
     * Days of week when backup should run. Valid values: mon, tue, wed, thu, fri, sat, sun. Provide as an array of day names.
     * @type {Array<string>}
     * @memberof CreateBackupScheduleRequestContent
     */
    dow: Array<string>;
    /**
     * 
     * @type {CompressionType}
     * @memberof CreateBackupScheduleRequestContent
     */
    compress: CompressionType;
    /**
     * Backup mode. Valid values: 'snapshot', 'suspend', 'stop'
     * @type {string}
     * @memberof CreateBackupScheduleRequestContent
     */
    mode: string;
    /**
     * Email notification setting. Set to true to send notifications to client's email, false or omit to disable
     * @type {boolean}
     * @memberof CreateBackupScheduleRequestContent
     */
    mailto?: boolean;
}



/**
 * Check if a given object implements the CreateBackupScheduleRequestContent interface.
 */
export function instanceOfCreateBackupScheduleRequestContent(value: object): value is CreateBackupScheduleRequestContent {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('starttime' in value) || value['starttime'] === undefined) return false;
    if (!('dow' in value) || value['dow'] === undefined) return false;
    if (!('compress' in value) || value['compress'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    return true;
}

export function CreateBackupScheduleRequestContentFromJSON(json: any): CreateBackupScheduleRequestContent {
    return CreateBackupScheduleRequestContentFromJSONTyped(json, false);
}

export function CreateBackupScheduleRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBackupScheduleRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
        'starttime': json['starttime'],
        'dow': json['dow'],
        'compress': CompressionTypeFromJSON(json['compress']),
        'mode': json['mode'],
        'mailto': json['mailto'] == null ? undefined : json['mailto'],
    };
}

export function CreateBackupScheduleRequestContentToJSON(json: any): CreateBackupScheduleRequestContent {
    return CreateBackupScheduleRequestContentToJSONTyped(json, false);
}

export function CreateBackupScheduleRequestContentToJSONTyped(value?: CreateBackupScheduleRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
        'starttime': value['starttime'],
        'dow': value['dow'],
        'compress': CompressionTypeToJSON(value['compress']),
        'mode': value['mode'],
        'mailto': value['mailto'],
    };
}

