/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A domain line item returned in the order response
 * @export
 * @interface CreateOrderDomainItem
 */
export interface CreateOrderDomainItem {
    /**
     * Line item identifier
     * @type {number}
     * @memberof CreateOrderDomainItem
     */
    lineId: number;
    /**
     * Domain identifier
     * @type {number}
     * @memberof CreateOrderDomainItem
     */
    domainId: number;
    /**
     * Domain name
     * @type {string}
     * @memberof CreateOrderDomainItem
     */
    domain: string;
    /**
     * Domain operation type (e.g. register, transfer)
     * @type {string}
     * @memberof CreateOrderDomainItem
     */
    type: string;
    /**
     * Registration period in years
     * @type {number}
     * @memberof CreateOrderDomainItem
     */
    period: number;
    /**
     * Whether domain warranty is included
     * @type {boolean}
     * @memberof CreateOrderDomainItem
     */
    domainWarranty: boolean;
    /**
     * Whether auto-renewal is enabled
     * @type {boolean}
     * @memberof CreateOrderDomainItem
     */
    autorenew: boolean;
    /**
     * Line item amount charged (decimal string, e.g. "2333.33")
     * @type {string}
     * @memberof CreateOrderDomainItem
     */
    amount: string;
}

/**
 * Check if a given object implements the CreateOrderDomainItem interface.
 */
export function instanceOfCreateOrderDomainItem(value: object): value is CreateOrderDomainItem {
    if (!('lineId' in value) || value['lineId'] === undefined) return false;
    if (!('domainId' in value) || value['domainId'] === undefined) return false;
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('period' in value) || value['period'] === undefined) return false;
    if (!('domainWarranty' in value) || value['domainWarranty'] === undefined) return false;
    if (!('autorenew' in value) || value['autorenew'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function CreateOrderDomainItemFromJSON(json: any): CreateOrderDomainItem {
    return CreateOrderDomainItemFromJSONTyped(json, false);
}

export function CreateOrderDomainItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderDomainItem {
    if (json == null) {
        return json;
    }
    return {
        
        'lineId': json['line_id'],
        'domainId': json['domain_id'],
        'domain': json['domain'],
        'type': json['type'],
        'period': json['period'],
        'domainWarranty': json['domain_warranty'],
        'autorenew': json['autorenew'],
        'amount': json['amount'],
    };
}

export function CreateOrderDomainItemToJSON(json: any): CreateOrderDomainItem {
    return CreateOrderDomainItemToJSONTyped(json, false);
}

export function CreateOrderDomainItemToJSONTyped(value?: CreateOrderDomainItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'line_id': value['lineId'],
        'domain_id': value['domainId'],
        'domain': value['domain'],
        'type': value['type'],
        'period': value['period'],
        'domain_warranty': value['domainWarranty'],
        'autorenew': value['autorenew'],
        'amount': value['amount'],
    };
}

