/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSnapshotRequestContent
 */
export interface CreateSnapshotRequestContent {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof CreateSnapshotRequestContent
     */
    serviceId: string;
    /**
     * Name for the snapshot
     * @type {string}
     * @memberof CreateSnapshotRequestContent
     */
    snapname?: string;
    /**
     * Description for the snapshot
     * @type {string}
     * @memberof CreateSnapshotRequestContent
     */
    description?: string;
}

/**
 * Check if a given object implements the CreateSnapshotRequestContent interface.
 */
export function instanceOfCreateSnapshotRequestContent(value: object): value is CreateSnapshotRequestContent {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    return true;
}

export function CreateSnapshotRequestContentFromJSON(json: any): CreateSnapshotRequestContent {
    return CreateSnapshotRequestContentFromJSONTyped(json, false);
}

export function CreateSnapshotRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSnapshotRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
        'snapname': json['snapname'] == null ? undefined : json['snapname'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreateSnapshotRequestContentToJSON(json: any): CreateSnapshotRequestContent {
    return CreateSnapshotRequestContentToJSONTyped(json, false);
}

export function CreateSnapshotRequestContentToJSONTyped(value?: CreateSnapshotRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
        'snapname': value['snapname'],
        'description': value['description'],
    };
}

