/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SnapshotJobMutationResponseData } from './SnapshotJobMutationResponseData.js';
import {
    SnapshotJobMutationResponseDataFromJSON,
    SnapshotJobMutationResponseDataFromJSONTyped,
    SnapshotJobMutationResponseDataToJSON,
    SnapshotJobMutationResponseDataToJSONTyped,
} from './SnapshotJobMutationResponseData.js';
import type { OperationStatus } from './OperationStatus.js';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus.js';

/**
 * 
 * @export
 * @interface CreateSnapshotJobResponseContent
 */
export interface CreateSnapshotJobResponseContent {
    /**
     * 
     * @type {OperationStatus}
     * @memberof CreateSnapshotJobResponseContent
     */
    status: OperationStatus;
    /**
     * 
     * @type {SnapshotJobMutationResponseData}
     * @memberof CreateSnapshotJobResponseContent
     */
    data: SnapshotJobMutationResponseData;
}



/**
 * Check if a given object implements the CreateSnapshotJobResponseContent interface.
 */
export function instanceOfCreateSnapshotJobResponseContent(value: object): value is CreateSnapshotJobResponseContent {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreateSnapshotJobResponseContentFromJSON(json: any): CreateSnapshotJobResponseContent {
    return CreateSnapshotJobResponseContentFromJSONTyped(json, false);
}

export function CreateSnapshotJobResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSnapshotJobResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': SnapshotJobMutationResponseDataFromJSON(json['data']),
    };
}

export function CreateSnapshotJobResponseContentToJSON(json: any): CreateSnapshotJobResponseContent {
    return CreateSnapshotJobResponseContentToJSONTyped(json, false);
}

export function CreateSnapshotJobResponseContentToJSONTyped(value?: CreateSnapshotJobResponseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': SnapshotJobMutationResponseDataToJSON(value['data']),
    };
}

