/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A single product line item in a create order request
 * @export
 * @interface CreateOrderProduct
 */
export interface CreateOrderProduct {
    /**
     * WHMCS product ID
     * @type {number}
     * @memberof CreateOrderProduct
     */
    pid: number;
    /**
     * Billing cycle (e.g. monthly, annually)
     * @type {string}
     * @memberof CreateOrderProduct
     */
    billingCycle: string;
    /**
     * Plan ID for the selected product configuration
     * @type {number}
     * @memberof CreateOrderProduct
     */
    planId: number;
    /**
     * Hostname to assign to the service
     * @type {string}
     * @memberof CreateOrderProduct
     */
    hostname: string;
    /**
     * Configuration options as a free-form map
     * @type {any}
     * @memberof CreateOrderProduct
     */
    configOptions: any | null;
    /**
     * Additional data as a free-form map
     * @type {any}
     * @memberof CreateOrderProduct
     */
    additionalData?: any | null;
}

/**
 * Check if a given object implements the CreateOrderProduct interface.
 */
export function instanceOfCreateOrderProduct(value: object): value is CreateOrderProduct {
    if (!('pid' in value) || value['pid'] === undefined) return false;
    if (!('billingCycle' in value) || value['billingCycle'] === undefined) return false;
    if (!('planId' in value) || value['planId'] === undefined) return false;
    if (!('hostname' in value) || value['hostname'] === undefined) return false;
    if (!('configOptions' in value) || value['configOptions'] === undefined) return false;
    return true;
}

export function CreateOrderProductFromJSON(json: any): CreateOrderProduct {
    return CreateOrderProductFromJSONTyped(json, false);
}

export function CreateOrderProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderProduct {
    if (json == null) {
        return json;
    }
    return {
        
        'pid': json['pid'],
        'billingCycle': json['billing_cycle'],
        'planId': json['plan_id'],
        'hostname': json['hostname'],
        'configOptions': json['config_options'],
        'additionalData': json['additional_data'] == null ? undefined : json['additional_data'],
    };
}

export function CreateOrderProductToJSON(json: any): CreateOrderProduct {
    return CreateOrderProductToJSONTyped(json, false);
}

export function CreateOrderProductToJSONTyped(value?: CreateOrderProduct | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pid': value['pid'],
        'billing_cycle': value['billingCycle'],
        'plan_id': value['planId'],
        'hostname': value['hostname'],
        'config_options': value['configOptions'],
        'additional_data': value['additionalData'],
    };
}

