/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { OperationStatus } from './OperationStatus.js';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus.js';
import type { NotificationCreateResponseData } from './NotificationCreateResponseData.js';
import {
    NotificationCreateResponseDataFromJSON,
    NotificationCreateResponseDataFromJSONTyped,
    NotificationCreateResponseDataToJSON,
    NotificationCreateResponseDataToJSONTyped,
} from './NotificationCreateResponseData.js';

/**
 * 
 * @export
 * @interface CreateNotificationResponseContent
 */
export interface CreateNotificationResponseContent {
    /**
     * 
     * @type {OperationStatus}
     * @memberof CreateNotificationResponseContent
     */
    status: OperationStatus;
    /**
     * 
     * @type {NotificationCreateResponseData}
     * @memberof CreateNotificationResponseContent
     */
    data: NotificationCreateResponseData;
}



/**
 * Check if a given object implements the CreateNotificationResponseContent interface.
 */
export function instanceOfCreateNotificationResponseContent(value: object): value is CreateNotificationResponseContent {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreateNotificationResponseContentFromJSON(json: any): CreateNotificationResponseContent {
    return CreateNotificationResponseContentFromJSONTyped(json, false);
}

export function CreateNotificationResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNotificationResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': NotificationCreateResponseDataFromJSON(json['data']),
    };
}

export function CreateNotificationResponseContentToJSON(json: any): CreateNotificationResponseContent {
    return CreateNotificationResponseContentToJSONTyped(json, false);
}

export function CreateNotificationResponseContentToJSONTyped(value?: CreateNotificationResponseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': NotificationCreateResponseDataToJSON(value['data']),
    };
}

