/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderWarning } from './OrderWarning';
import {
    OrderWarningFromJSON,
    OrderWarningFromJSONTyped,
    OrderWarningToJSON,
    OrderWarningToJSONTyped,
} from './OrderWarning';
import type { CreateOrderItems } from './CreateOrderItems';
import {
    CreateOrderItemsFromJSON,
    CreateOrderItemsFromJSONTyped,
    CreateOrderItemsToJSON,
    CreateOrderItemsToJSONTyped,
} from './CreateOrderItems';
import type { CreateOrderTotal } from './CreateOrderTotal';
import {
    CreateOrderTotalFromJSON,
    CreateOrderTotalFromJSONTyped,
    CreateOrderTotalToJSON,
    CreateOrderTotalToJSONTyped,
} from './CreateOrderTotal';
import type { PaymentStatus } from './PaymentStatus';
import {
    PaymentStatusFromJSON,
    PaymentStatusFromJSONTyped,
    PaymentStatusToJSON,
    PaymentStatusToJSONTyped,
} from './PaymentStatus';
import type { PaymentError } from './PaymentError';
import {
    PaymentErrorFromJSON,
    PaymentErrorFromJSONTyped,
    PaymentErrorToJSON,
    PaymentErrorToJSONTyped,
} from './PaymentError';

/**
 * Response data for a successful or pending order
 * @export
 * @interface CreateOrderResponseData
 */
export interface CreateOrderResponseData {
    /**
     * Order identifier
     * @type {number}
     * @memberof CreateOrderResponseData
     */
    orderId: number;
    /**
     * Invoice identifier for this order
     * @type {number}
     * @memberof CreateOrderResponseData
     */
    invoiceId: number;
    /**
     * Human-readable order reference number
     * @type {string}
     * @memberof CreateOrderResponseData
     */
    orderNumber: string;
    /**
     * 
     * @type {CreateOrderTotal}
     * @memberof CreateOrderResponseData
     */
    total: CreateOrderTotal;
    /**
     * Promotional code that was applied
     * @type {string}
     * @memberof CreateOrderResponseData
     */
    promoApplied?: string;
    /**
     * Payment method used (e.g. stripe)
     * @type {string}
     * @memberof CreateOrderResponseData
     */
    paymentMethod: string;
    /**
     * 
     * @type {PaymentStatus}
     * @memberof CreateOrderResponseData
     */
    paymentStatus: PaymentStatus;
    /**
     * 
     * @type {CreateOrderItems}
     * @memberof CreateOrderResponseData
     */
    items: CreateOrderItems;
    /**
     * 
     * @type {PaymentError}
     * @memberof CreateOrderResponseData
     */
    paymentError?: PaymentError;
    /**
     * Warnings present when non-critical issues occurred (e.g. autorenew deferred)
     * @type {Array<OrderWarning>}
     * @memberof CreateOrderResponseData
     */
    warnings?: Array<OrderWarning>;
}



/**
 * Check if a given object implements the CreateOrderResponseData interface.
 */
export function instanceOfCreateOrderResponseData(value: object): value is CreateOrderResponseData {
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    if (!('invoiceId' in value) || value['invoiceId'] === undefined) return false;
    if (!('orderNumber' in value) || value['orderNumber'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('paymentMethod' in value) || value['paymentMethod'] === undefined) return false;
    if (!('paymentStatus' in value) || value['paymentStatus'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function CreateOrderResponseDataFromJSON(json: any): CreateOrderResponseData {
    return CreateOrderResponseDataFromJSONTyped(json, false);
}

export function CreateOrderResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['order_id'],
        'invoiceId': json['invoice_id'],
        'orderNumber': json['order_number'],
        'total': CreateOrderTotalFromJSON(json['total']),
        'promoApplied': json['promo_applied'] == null ? undefined : json['promo_applied'],
        'paymentMethod': json['payment_method'],
        'paymentStatus': PaymentStatusFromJSON(json['payment_status']),
        'items': CreateOrderItemsFromJSON(json['items']),
        'paymentError': json['payment_error'] == null ? undefined : PaymentErrorFromJSON(json['payment_error']),
        'warnings': json['warnings'] == null ? undefined : ((json['warnings'] as Array<any>).map(OrderWarningFromJSON)),
    };
}

export function CreateOrderResponseDataToJSON(json: any): CreateOrderResponseData {
    return CreateOrderResponseDataToJSONTyped(json, false);
}

export function CreateOrderResponseDataToJSONTyped(value?: CreateOrderResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'order_id': value['orderId'],
        'invoice_id': value['invoiceId'],
        'order_number': value['orderNumber'],
        'total': CreateOrderTotalToJSON(value['total']),
        'promo_applied': value['promoApplied'],
        'payment_method': value['paymentMethod'],
        'payment_status': PaymentStatusToJSON(value['paymentStatus']),
        'items': CreateOrderItemsToJSON(value['items']),
        'payment_error': PaymentErrorToJSON(value['paymentError']),
        'warnings': value['warnings'] == null ? undefined : ((value['warnings'] as Array<any>).map(OrderWarningToJSON)),
    };
}

