/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { VpsSimpleActionResponseData } from './VpsSimpleActionResponseData.js';
import {
    VpsSimpleActionResponseDataFromJSON,
    VpsSimpleActionResponseDataFromJSONTyped,
    VpsSimpleActionResponseDataToJSON,
    VpsSimpleActionResponseDataToJSONTyped,
} from './VpsSimpleActionResponseData.js';
import type { OperationStatus } from './OperationStatus.js';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus.js';

/**
 * 
 * @export
 * @interface DeleteNotificationResponseContent
 */
export interface DeleteNotificationResponseContent {
    /**
     * 
     * @type {OperationStatus}
     * @memberof DeleteNotificationResponseContent
     */
    status: OperationStatus;
    /**
     * 
     * @type {VpsSimpleActionResponseData}
     * @memberof DeleteNotificationResponseContent
     */
    data: VpsSimpleActionResponseData;
}



/**
 * Check if a given object implements the DeleteNotificationResponseContent interface.
 */
export function instanceOfDeleteNotificationResponseContent(value: object): value is DeleteNotificationResponseContent {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function DeleteNotificationResponseContentFromJSON(json: any): DeleteNotificationResponseContent {
    return DeleteNotificationResponseContentFromJSONTyped(json, false);
}

export function DeleteNotificationResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteNotificationResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': VpsSimpleActionResponseDataFromJSON(json['data']),
    };
}

export function DeleteNotificationResponseContentToJSON(json: any): DeleteNotificationResponseContent {
    return DeleteNotificationResponseContentToJSONTyped(json, false);
}

export function DeleteNotificationResponseContentToJSONTyped(value?: DeleteNotificationResponseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': VpsSimpleActionResponseDataToJSON(value['data']),
    };
}

