/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VpsSimpleActionResponseData } from './VpsSimpleActionResponseData';
import {
    VpsSimpleActionResponseDataFromJSON,
    VpsSimpleActionResponseDataFromJSONTyped,
    VpsSimpleActionResponseDataToJSON,
    VpsSimpleActionResponseDataToJSONTyped,
} from './VpsSimpleActionResponseData';
import type { OperationStatus } from './OperationStatus';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus';

/**
 * 
 * @export
 * @interface DeleteSnapshotOutput
 */
export interface DeleteSnapshotOutput {
    /**
     * 
     * @type {OperationStatus}
     * @memberof DeleteSnapshotOutput
     */
    status: OperationStatus;
    /**
     * 
     * @type {VpsSimpleActionResponseData}
     * @memberof DeleteSnapshotOutput
     */
    data: VpsSimpleActionResponseData;
}



/**
 * Check if a given object implements the DeleteSnapshotOutput interface.
 */
export function instanceOfDeleteSnapshotOutput(value: object): value is DeleteSnapshotOutput {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function DeleteSnapshotOutputFromJSON(json: any): DeleteSnapshotOutput {
    return DeleteSnapshotOutputFromJSONTyped(json, false);
}

export function DeleteSnapshotOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteSnapshotOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': VpsSimpleActionResponseDataFromJSON(json['data']),
    };
}

export function DeleteSnapshotOutputToJSON(json: any): DeleteSnapshotOutput {
    return DeleteSnapshotOutputToJSONTyped(json, false);
}

export function DeleteSnapshotOutputToJSONTyped(value?: DeleteSnapshotOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': VpsSimpleActionResponseDataToJSON(value['data']),
    };
}

