/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VpsSimpleActionResponseData } from './VpsSimpleActionResponseData';
import {
    VpsSimpleActionResponseDataFromJSON,
    VpsSimpleActionResponseDataFromJSONTyped,
    VpsSimpleActionResponseDataToJSON,
    VpsSimpleActionResponseDataToJSONTyped,
} from './VpsSimpleActionResponseData';
import type { OperationStatus } from './OperationStatus';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus';

/**
 * 
 * @export
 * @interface DeletePowerTaskOutput
 */
export interface DeletePowerTaskOutput {
    /**
     * 
     * @type {OperationStatus}
     * @memberof DeletePowerTaskOutput
     */
    status: OperationStatus;
    /**
     * 
     * @type {VpsSimpleActionResponseData}
     * @memberof DeletePowerTaskOutput
     */
    data: VpsSimpleActionResponseData;
}



/**
 * Check if a given object implements the DeletePowerTaskOutput interface.
 */
export function instanceOfDeletePowerTaskOutput(value: object): value is DeletePowerTaskOutput {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function DeletePowerTaskOutputFromJSON(json: any): DeletePowerTaskOutput {
    return DeletePowerTaskOutputFromJSONTyped(json, false);
}

export function DeletePowerTaskOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeletePowerTaskOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': VpsSimpleActionResponseDataFromJSON(json['data']),
    };
}

export function DeletePowerTaskOutputToJSON(json: any): DeletePowerTaskOutput {
    return DeletePowerTaskOutputToJSONTyped(json, false);
}

export function DeletePowerTaskOutputToJSONTyped(value?: DeletePowerTaskOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': VpsSimpleActionResponseDataToJSON(value['data']),
    };
}

