/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { VpsSimpleActionResponseData } from './VpsSimpleActionResponseData.js';
import {
    VpsSimpleActionResponseDataFromJSON,
    VpsSimpleActionResponseDataFromJSONTyped,
    VpsSimpleActionResponseDataToJSON,
    VpsSimpleActionResponseDataToJSONTyped,
} from './VpsSimpleActionResponseData.js';
import type { OperationStatus } from './OperationStatus.js';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus.js';

/**
 * 
 * @export
 * @interface DeleteFirewallRuleResponseContent
 */
export interface DeleteFirewallRuleResponseContent {
    /**
     * 
     * @type {OperationStatus}
     * @memberof DeleteFirewallRuleResponseContent
     */
    status: OperationStatus;
    /**
     * 
     * @type {VpsSimpleActionResponseData}
     * @memberof DeleteFirewallRuleResponseContent
     */
    data: VpsSimpleActionResponseData;
}



/**
 * Check if a given object implements the DeleteFirewallRuleResponseContent interface.
 */
export function instanceOfDeleteFirewallRuleResponseContent(value: object): value is DeleteFirewallRuleResponseContent {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function DeleteFirewallRuleResponseContentFromJSON(json: any): DeleteFirewallRuleResponseContent {
    return DeleteFirewallRuleResponseContentFromJSONTyped(json, false);
}

export function DeleteFirewallRuleResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteFirewallRuleResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': VpsSimpleActionResponseDataFromJSON(json['data']),
    };
}

export function DeleteFirewallRuleResponseContentToJSON(json: any): DeleteFirewallRuleResponseContent {
    return DeleteFirewallRuleResponseContentToJSONTyped(json, false);
}

export function DeleteFirewallRuleResponseContentToJSONTyped(value?: DeleteFirewallRuleResponseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': VpsSimpleActionResponseDataToJSON(value['data']),
    };
}

