/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * A DNS record within a zone.
 * 
 * Record values are normalized to a flat `content` string. Structured record types use
 * additional top-level fields; the proxy maps these to upstream `data` / `rdata_raw` shapes:
 * 
 * - **A / AAAA**: `content` is the IP address (`data.address`).
 * - **CNAME**: `content` is the target hostname (`data.cname`).
 * - **TXT**: `content` is the text value (`data.txtdata`).
 * - **NS**: `content` is the nameserver hostname (`data.nsdname`).
 * - **MX**: `content` is the mail exchange hostname; `priority` is the MX preference
 *   (`data.exchange`, `data.preference`).
 * - **SRV**: `content` is the target hostname; `priority`, `weight`, and `port` are the
 *   SRV parameters (`data.target`, `data.priority`, `data.weight`, `data.port`).
 * 
 * When upstream returns structured `rdata_raw` without a string `rdata` value, `content`
 * and the type-specific fields are derived from `rdata_raw`.
 * @export
 * @interface DnsRecordInfo
 */
export interface DnsRecordInfo {
    /**
     * Record identifier
     * @type {string}
     * @memberof DnsRecordInfo
     */
    id?: string;
    /**
     * Record host/name (e.g. @, www, mail)
     * @type {string}
     * @memberof DnsRecordInfo
     */
    name?: string;
    /**
     * Record type (e.g. A, AAAA, CNAME, MX, TXT, NS, SRV)
     * @type {string}
     * @memberof DnsRecordInfo
     */
    type?: string;
    /**
     * Primary record value: IP address (A/AAAA), hostname (CNAME/NS/MX/SRV), or text (TXT)
     * @type {string}
     * @memberof DnsRecordInfo
     */
    content?: string;
    /**
     * Time-to-live in seconds
     * @type {number}
     * @memberof DnsRecordInfo
     */
    ttl?: number;
    /**
     * MX preference when type is MX; SRV priority when type is SRV
     * @type {number}
     * @memberof DnsRecordInfo
     */
    priority?: number;
    /**
     * SRV weight when type is SRV
     * @type {number}
     * @memberof DnsRecordInfo
     */
    weight?: number;
    /**
     * SRV port when type is SRV
     * @type {number}
     * @memberof DnsRecordInfo
     */
    port?: number;
}

/**
 * Check if a given object implements the DnsRecordInfo interface.
 */
export function instanceOfDnsRecordInfo(value: object): value is DnsRecordInfo {
    return true;
}

export function DnsRecordInfoFromJSON(json: any): DnsRecordInfo {
    return DnsRecordInfoFromJSONTyped(json, false);
}

export function DnsRecordInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DnsRecordInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'content': json['content'] == null ? undefined : json['content'],
        'ttl': json['ttl'] == null ? undefined : json['ttl'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'port': json['port'] == null ? undefined : json['port'],
    };
}

export function DnsRecordInfoToJSON(json: any): DnsRecordInfo {
    return DnsRecordInfoToJSONTyped(json, false);
}

export function DnsRecordInfoToJSONTyped(value?: DnsRecordInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': value['type'],
        'content': value['content'],
        'ttl': value['ttl'],
        'priority': value['priority'],
        'weight': value['weight'],
        'port': value['port'],
    };
}

