/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { DomainAddonFeature } from './DomainAddonFeature.js';
import {
    DomainAddonFeatureFromJSON,
    DomainAddonFeatureFromJSONTyped,
    DomainAddonFeatureToJSON,
    DomainAddonFeatureToJSONTyped,
} from './DomainAddonFeature.js';

/**
 * Feature flags and priced addons available for a domain
 * @export
 * @interface DomainAvailableFeatures
 */
export interface DomainAvailableFeatures {
    /**
     * Whether EPP/auth code retrieval is available
     * @type {boolean}
     * @memberof DomainAvailableFeatures
     */
    eppcode?: boolean;
    /**
     * Whether DNSSEC management is available
     * @type {boolean}
     * @memberof DomainAvailableFeatures
     */
    dnssec?: boolean;
    /**
     * Whether private/custom nameservers are supported
     * @type {boolean}
     * @memberof DomainAvailableFeatures
     */
    privateNameservers?: boolean;
    /**
     * Whether domain redirect is available
     * @type {boolean}
     * @memberof DomainAvailableFeatures
     */
    redirector?: boolean;
    /**
     * 
     * @type {DomainAddonFeature}
     * @memberof DomainAvailableFeatures
     */
    dnsmanagement?: DomainAddonFeature;
    /**
     * 
     * @type {DomainAddonFeature}
     * @memberof DomainAvailableFeatures
     */
    emailforwarding?: DomainAddonFeature;
    /**
     * 
     * @type {DomainAddonFeature}
     * @memberof DomainAvailableFeatures
     */
    idprotection?: DomainAddonFeature;
}

/**
 * Check if a given object implements the DomainAvailableFeatures interface.
 */
export function instanceOfDomainAvailableFeatures(value: object): value is DomainAvailableFeatures {
    return true;
}

export function DomainAvailableFeaturesFromJSON(json: any): DomainAvailableFeatures {
    return DomainAvailableFeaturesFromJSONTyped(json, false);
}

export function DomainAvailableFeaturesFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainAvailableFeatures {
    if (json == null) {
        return json;
    }
    return {
        
        'eppcode': json['eppcode'] == null ? undefined : json['eppcode'],
        'dnssec': json['dnssec'] == null ? undefined : json['dnssec'],
        'privateNameservers': json['private_nameservers'] == null ? undefined : json['private_nameservers'],
        'redirector': json['redirector'] == null ? undefined : json['redirector'],
        'dnsmanagement': json['dnsmanagement'] == null ? undefined : DomainAddonFeatureFromJSON(json['dnsmanagement']),
        'emailforwarding': json['emailforwarding'] == null ? undefined : DomainAddonFeatureFromJSON(json['emailforwarding']),
        'idprotection': json['idprotection'] == null ? undefined : DomainAddonFeatureFromJSON(json['idprotection']),
    };
}

export function DomainAvailableFeaturesToJSON(json: any): DomainAvailableFeatures {
    return DomainAvailableFeaturesToJSONTyped(json, false);
}

export function DomainAvailableFeaturesToJSONTyped(value?: DomainAvailableFeatures | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eppcode': value['eppcode'],
        'dnssec': value['dnssec'],
        'private_nameservers': value['privateNameservers'],
        'redirector': value['redirector'],
        'dnsmanagement': DomainAddonFeatureToJSON(value['dnsmanagement']),
        'emailforwarding': DomainAddonFeatureToJSON(value['emailforwarding']),
        'idprotection': DomainAddonFeatureToJSON(value['idprotection']),
    };
}

