/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * A single period/price pair for domain pricing
 * @export
 * @interface DomainPricingEntry
 */
export interface DomainPricingEntry {
    /**
     * 
     * @type {number}
     * @memberof DomainPricingEntry
     */
    period: number;
    /**
     * Price as a decimal string with two decimal places
     * @type {string}
     * @memberof DomainPricingEntry
     */
    price: string;
}

/**
 * Check if a given object implements the DomainPricingEntry interface.
 */
export function instanceOfDomainPricingEntry(value: object): value is DomainPricingEntry {
    if (!('period' in value) || value['period'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function DomainPricingEntryFromJSON(json: any): DomainPricingEntry {
    return DomainPricingEntryFromJSONTyped(json, false);
}

export function DomainPricingEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainPricingEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'period': json['period'],
        'price': json['price'],
    };
}

export function DomainPricingEntryToJSON(json: any): DomainPricingEntry {
    return DomainPricingEntryToJSONTyped(json, false);
}

export function DomainPricingEntryToJSONTyped(value?: DomainPricingEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'period': value['period'],
        'price': value['price'],
    };
}

