/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * WHOIS contacts keyed by contact role
 * @export
 * @interface DomainContacts
 */
export interface DomainContacts {
    /**
     * WHOIS contact field values for one role; field names vary by TLD/registrar
     * @type {{ [key: string]: string; }}
     * @memberof DomainContacts
     */
    registrant?: { [key: string]: string; };
    /**
     * WHOIS contact field values for one role; field names vary by TLD/registrar
     * @type {{ [key: string]: string; }}
     * @memberof DomainContacts
     */
    admin?: { [key: string]: string; };
    /**
     * WHOIS contact field values for one role; field names vary by TLD/registrar
     * @type {{ [key: string]: string; }}
     * @memberof DomainContacts
     */
    tech?: { [key: string]: string; };
    /**
     * WHOIS contact field values for one role; field names vary by TLD/registrar
     * @type {{ [key: string]: string; }}
     * @memberof DomainContacts
     */
    billing?: { [key: string]: string; };
}

/**
 * Check if a given object implements the DomainContacts interface.
 */
export function instanceOfDomainContacts(value: object): value is DomainContacts {
    return true;
}

export function DomainContactsFromJSON(json: any): DomainContacts {
    return DomainContactsFromJSONTyped(json, false);
}

export function DomainContactsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainContacts {
    if (json == null) {
        return json;
    }
    return {
        
        'registrant': json['Registrant'] == null ? undefined : json['Registrant'],
        'admin': json['Admin'] == null ? undefined : json['Admin'],
        'tech': json['Tech'] == null ? undefined : json['Tech'],
        'billing': json['Billing'] == null ? undefined : json['Billing'],
    };
}

export function DomainContactsToJSON(json: any): DomainContacts {
    return DomainContactsToJSONTyped(json, false);
}

export function DomainContactsToJSONTyped(value?: DomainContacts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Registrant': value['registrant'],
        'Admin': value['admin'],
        'Tech': value['tech'],
        'Billing': value['billing'],
    };
}

