/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Firewall rule structure
 * @export
 * @interface FirewallRule
 */
export interface FirewallRule {
    /**
     * SHA1 digest of the rule
     * @type {string}
     * @memberof FirewallRule
     */
    digest: string;
    /**
     * Position/priority of the rule
     * @type {number}
     * @memberof FirewallRule
     */
    pos: number;
    /**
     * Rule type (in, out)
     * @type {string}
     * @memberof FirewallRule
     */
    type: string;
    /**
     * Action to perform (ACCEPT, REJECT, DROP)
     * @type {string}
     * @memberof FirewallRule
     */
    action: string;
    /**
     * Network interface name
     * @type {string}
     * @memberof FirewallRule
     */
    iface: string;
    /**
     * Whether the rule is enabled (1=enabled, 0=disabled)
     * @type {number}
     * @memberof FirewallRule
     */
    enable: number;
    /**
     * Comment/description for the rule
     * @type {string}
     * @memberof FirewallRule
     */
    comment?: string;
    /**
     * Source address/network
     * @type {string}
     * @memberof FirewallRule
     */
    source?: string;
    /**
     * Destination address/network
     * @type {string}
     * @memberof FirewallRule
     */
    dest?: string;
    /**
     * Protocol (tcp, udp, icmp, etc)
     * @type {string}
     * @memberof FirewallRule
     */
    proto?: string;
    /**
     * Destination port
     * @type {string}
     * @memberof FirewallRule
     */
    dport?: string;
    /**
     * Source port
     * @type {string}
     * @memberof FirewallRule
     */
    sport?: string;
    /**
     * Firewall macro name
     * @type {string}
     * @memberof FirewallRule
     */
    macro?: string;
    /**
     * Log level
     * @type {string}
     * @memberof FirewallRule
     */
    log?: string;
}

/**
 * Check if a given object implements the FirewallRule interface.
 */
export function instanceOfFirewallRule(value: object): value is FirewallRule {
    if (!('digest' in value) || value['digest'] === undefined) return false;
    if (!('pos' in value) || value['pos'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('iface' in value) || value['iface'] === undefined) return false;
    if (!('enable' in value) || value['enable'] === undefined) return false;
    return true;
}

export function FirewallRuleFromJSON(json: any): FirewallRule {
    return FirewallRuleFromJSONTyped(json, false);
}

export function FirewallRuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): FirewallRule {
    if (json == null) {
        return json;
    }
    return {
        
        'digest': json['digest'],
        'pos': json['pos'],
        'type': json['type'],
        'action': json['action'],
        'iface': json['iface'],
        'enable': json['enable'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'source': json['source'] == null ? undefined : json['source'],
        'dest': json['dest'] == null ? undefined : json['dest'],
        'proto': json['proto'] == null ? undefined : json['proto'],
        'dport': json['dport'] == null ? undefined : json['dport'],
        'sport': json['sport'] == null ? undefined : json['sport'],
        'macro': json['macro'] == null ? undefined : json['macro'],
        'log': json['log'] == null ? undefined : json['log'],
    };
}

export function FirewallRuleToJSON(json: any): FirewallRule {
    return FirewallRuleToJSONTyped(json, false);
}

export function FirewallRuleToJSONTyped(value?: FirewallRule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'digest': value['digest'],
        'pos': value['pos'],
        'type': value['type'],
        'action': value['action'],
        'iface': value['iface'],
        'enable': value['enable'],
        'comment': value['comment'],
        'source': value['source'],
        'dest': value['dest'],
        'proto': value['proto'],
        'dport': value['dport'],
        'sport': value['sport'],
        'macro': value['macro'],
        'log': value['log'],
    };
}

