/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { DomainContacts } from './DomainContacts.js';
import {
    DomainContactsFromJSON,
    DomainContactsFromJSONTyped,
    DomainContactsToJSON,
    DomainContactsToJSONTyped,
} from './DomainContacts.js';

/**
 * Domain contact information returned by get-domain-contacts
 * @export
 * @interface GetDomainContactsData
 */
export interface GetDomainContactsData {
    /**
     * Status message indicating the result
     * @type {string}
     * @memberof GetDomainContactsData
     */
    message: string;
    /**
     * Domain service id
     * @type {string}
     * @memberof GetDomainContactsData
     */
    domainId: string;
    /**
     * Fully qualified domain name
     * @type {string}
     * @memberof GetDomainContactsData
     */
    domain: string;
    /**
     * 
     * @type {DomainContacts}
     * @memberof GetDomainContactsData
     */
    contacts: DomainContacts;
}

/**
 * Check if a given object implements the GetDomainContactsData interface.
 */
export function instanceOfGetDomainContactsData(value: object): value is GetDomainContactsData {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('domainId' in value) || value['domainId'] === undefined) return false;
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('contacts' in value) || value['contacts'] === undefined) return false;
    return true;
}

export function GetDomainContactsDataFromJSON(json: any): GetDomainContactsData {
    return GetDomainContactsDataFromJSONTyped(json, false);
}

export function GetDomainContactsDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDomainContactsData {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'domainId': json['domain_id'],
        'domain': json['domain'],
        'contacts': DomainContactsFromJSON(json['contacts']),
    };
}

export function GetDomainContactsDataToJSON(json: any): GetDomainContactsData {
    return GetDomainContactsDataToJSONTyped(json, false);
}

export function GetDomainContactsDataToJSONTyped(value?: GetDomainContactsData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'domain_id': value['domainId'],
        'domain': value['domain'],
        'contacts': DomainContactsToJSON(value['contacts']),
    };
}

