/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GetDomainRequestContent
 */
export interface GetDomainRequestContent {
    /**
     * Domain service id - must be sent as a string
     * @type {string}
     * @memberof GetDomainRequestContent
     */
    domainId: string;
}

/**
 * Check if a given object implements the GetDomainRequestContent interface.
 */
export function instanceOfGetDomainRequestContent(value: object): value is GetDomainRequestContent {
    if (!('domainId' in value) || value['domainId'] === undefined) return false;
    return true;
}

export function GetDomainRequestContentFromJSON(json: any): GetDomainRequestContent {
    return GetDomainRequestContentFromJSONTyped(json, false);
}

export function GetDomainRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDomainRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'domainId': json['domain_id'],
    };
}

export function GetDomainRequestContentToJSON(json: any): GetDomainRequestContent {
    return GetDomainRequestContentToJSONTyped(json, false);
}

export function GetDomainRequestContentToJSONTyped(value?: GetDomainRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domain_id': value['domainId'],
    };
}

