/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { DomainInfo } from './DomainInfo.js';
import {
    DomainInfoFromJSON,
    DomainInfoFromJSONTyped,
    DomainInfoToJSON,
    DomainInfoToJSONTyped,
} from './DomainInfo.js';

/**
 * Response data for get-domain
 * @export
 * @interface GetDomainData
 */
export interface GetDomainData {
    /**
     * Status message indicating the result
     * @type {string}
     * @memberof GetDomainData
     */
    message: string;
    /**
     * 
     * @type {DomainInfo}
     * @memberof GetDomainData
     */
    domain: DomainInfo;
}

/**
 * Check if a given object implements the GetDomainData interface.
 */
export function instanceOfGetDomainData(value: object): value is GetDomainData {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('domain' in value) || value['domain'] === undefined) return false;
    return true;
}

export function GetDomainDataFromJSON(json: any): GetDomainData {
    return GetDomainDataFromJSONTyped(json, false);
}

export function GetDomainDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDomainData {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'domain': DomainInfoFromJSON(json['domain']),
    };
}

export function GetDomainDataToJSON(json: any): GetDomainData {
    return GetDomainDataToJSONTyped(json, false);
}

export function GetDomainDataToJSONTyped(value?: GetDomainData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'domain': DomainInfoToJSON(value['domain']),
    };
}

