/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GetEncryptedPasswordRequestContent
 */
export interface GetEncryptedPasswordRequestContent {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof GetEncryptedPasswordRequestContent
     */
    serviceId: string;
    /**
     * PEM-encoded RSA public key only (never the private key). Accepts SPKI (`-----BEGIN PUBLIC KEY-----`) or PKCS#1 (`-----BEGIN RSA PUBLIC KEY-----`). Must be exactly 4096-bit. Used with RSA-OAEP and SHA-256 to encrypt the password.
     * @type {string}
     * @memberof GetEncryptedPasswordRequestContent
     */
    publicKey: string;
}

/**
 * Check if a given object implements the GetEncryptedPasswordRequestContent interface.
 */
export function instanceOfGetEncryptedPasswordRequestContent(value: object): value is GetEncryptedPasswordRequestContent {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('publicKey' in value) || value['publicKey'] === undefined) return false;
    return true;
}

export function GetEncryptedPasswordRequestContentFromJSON(json: any): GetEncryptedPasswordRequestContent {
    return GetEncryptedPasswordRequestContentFromJSONTyped(json, false);
}

export function GetEncryptedPasswordRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEncryptedPasswordRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
        'publicKey': json['public_key'],
    };
}

export function GetEncryptedPasswordRequestContentToJSON(json: any): GetEncryptedPasswordRequestContent {
    return GetEncryptedPasswordRequestContentToJSONTyped(json, false);
}

export function GetEncryptedPasswordRequestContentToJSONTyped(value?: GetEncryptedPasswordRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
        'public_key': value['publicKey'],
    };
}

