/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetNoVncConsoleInput
 */
export interface GetNoVncConsoleInput {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof GetNoVncConsoleInput
     */
    serviceId: string;
}

/**
 * Check if a given object implements the GetNoVncConsoleInput interface.
 */
export function instanceOfGetNoVncConsoleInput(value: object): value is GetNoVncConsoleInput {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    return true;
}

export function GetNoVncConsoleInputFromJSON(json: any): GetNoVncConsoleInput {
    return GetNoVncConsoleInputFromJSONTyped(json, false);
}

export function GetNoVncConsoleInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNoVncConsoleInput {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
    };
}

export function GetNoVncConsoleInputToJSON(json: any): GetNoVncConsoleInput {
    return GetNoVncConsoleInputToJSONTyped(json, false);
}

export function GetNoVncConsoleInputToJSONTyped(value?: GetNoVncConsoleInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
    };
}

