/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetOsTemplateDetailsRequestContent
 */
export interface GetOsTemplateDetailsRequestContent {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof GetOsTemplateDetailsRequestContent
     */
    serviceId: string;
    /**
     * Image identifier for the OS template
     * @type {string}
     * @memberof GetOsTemplateDetailsRequestContent
     */
    imageId: string;
}

/**
 * Check if a given object implements the GetOsTemplateDetailsRequestContent interface.
 */
export function instanceOfGetOsTemplateDetailsRequestContent(value: object): value is GetOsTemplateDetailsRequestContent {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('imageId' in value) || value['imageId'] === undefined) return false;
    return true;
}

export function GetOsTemplateDetailsRequestContentFromJSON(json: any): GetOsTemplateDetailsRequestContent {
    return GetOsTemplateDetailsRequestContentFromJSONTyped(json, false);
}

export function GetOsTemplateDetailsRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOsTemplateDetailsRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
        'imageId': json['imageId'],
    };
}

export function GetOsTemplateDetailsRequestContentToJSON(json: any): GetOsTemplateDetailsRequestContent {
    return GetOsTemplateDetailsRequestContentToJSONTyped(json, false);
}

export function GetOsTemplateDetailsRequestContentToJSONTyped(value?: GetOsTemplateDetailsRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
        'imageId': value['imageId'],
    };
}

