/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OsImage } from './OsImage';
import {
    OsImageFromJSON,
    OsImageFromJSONTyped,
    OsImageToJSON,
    OsImageToJSONTyped,
} from './OsImage';

/**
 * Response data for get OS template details operation
 * @export
 * @interface GetOsTemplateDetailsResponseData
 */
export interface GetOsTemplateDetailsResponseData {
    /**
     * Status message indicating the result
     * @type {string}
     * @memberof GetOsTemplateDetailsResponseData
     */
    message: string;
    /**
     * 
     * @type {OsImage}
     * @memberof GetOsTemplateDetailsResponseData
     */
    image: OsImage;
}

/**
 * Check if a given object implements the GetOsTemplateDetailsResponseData interface.
 */
export function instanceOfGetOsTemplateDetailsResponseData(value: object): value is GetOsTemplateDetailsResponseData {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    return true;
}

export function GetOsTemplateDetailsResponseDataFromJSON(json: any): GetOsTemplateDetailsResponseData {
    return GetOsTemplateDetailsResponseDataFromJSONTyped(json, false);
}

export function GetOsTemplateDetailsResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOsTemplateDetailsResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'image': OsImageFromJSON(json['image']),
    };
}

export function GetOsTemplateDetailsResponseDataToJSON(json: any): GetOsTemplateDetailsResponseData {
    return GetOsTemplateDetailsResponseDataToJSONTyped(json, false);
}

export function GetOsTemplateDetailsResponseDataToJSONTyped(value?: GetOsTemplateDetailsResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'image': OsImageToJSON(value['image']),
    };
}

