/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetOsTemplateDetailsInput
 */
export interface GetOsTemplateDetailsInput {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof GetOsTemplateDetailsInput
     */
    serviceId: string;
    /**
     * Image identifier for the OS template
     * @type {string}
     * @memberof GetOsTemplateDetailsInput
     */
    imageId: string;
}

/**
 * Check if a given object implements the GetOsTemplateDetailsInput interface.
 */
export function instanceOfGetOsTemplateDetailsInput(value: object): value is GetOsTemplateDetailsInput {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('imageId' in value) || value['imageId'] === undefined) return false;
    return true;
}

export function GetOsTemplateDetailsInputFromJSON(json: any): GetOsTemplateDetailsInput {
    return GetOsTemplateDetailsInputFromJSONTyped(json, false);
}

export function GetOsTemplateDetailsInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOsTemplateDetailsInput {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
        'imageId': json['imageId'],
    };
}

export function GetOsTemplateDetailsInputToJSON(json: any): GetOsTemplateDetailsInput {
    return GetOsTemplateDetailsInputToJSONTyped(json, false);
}

export function GetOsTemplateDetailsInputToJSONTyped(value?: GetOsTemplateDetailsInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
        'imageId': value['imageId'],
    };
}

