/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPrivateSshKeyInput
 */
export interface GetPrivateSshKeyInput {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof GetPrivateSshKeyInput
     */
    serviceId: string;
}

/**
 * Check if a given object implements the GetPrivateSshKeyInput interface.
 */
export function instanceOfGetPrivateSshKeyInput(value: object): value is GetPrivateSshKeyInput {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    return true;
}

export function GetPrivateSshKeyInputFromJSON(json: any): GetPrivateSshKeyInput {
    return GetPrivateSshKeyInputFromJSONTyped(json, false);
}

export function GetPrivateSshKeyInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPrivateSshKeyInput {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
    };
}

export function GetPrivateSshKeyInputToJSON(json: any): GetPrivateSshKeyInput {
    return GetPrivateSshKeyInputToJSONTyped(json, false);
}

export function GetPrivateSshKeyInputToJSONTyped(value?: GetPrivateSshKeyInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
    };
}

