/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetVpsConfigInput
 */
export interface GetVpsConfigInput {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof GetVpsConfigInput
     */
    serviceId: string;
}

/**
 * Check if a given object implements the GetVpsConfigInput interface.
 */
export function instanceOfGetVpsConfigInput(value: object): value is GetVpsConfigInput {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    return true;
}

export function GetVpsConfigInputFromJSON(json: any): GetVpsConfigInput {
    return GetVpsConfigInputFromJSONTyped(json, false);
}

export function GetVpsConfigInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVpsConfigInput {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
    };
}

export function GetVpsConfigInputToJSON(json: any): GetVpsConfigInput {
    return GetVpsConfigInputToJSONTyped(json, false);
}

export function GetVpsConfigInputToJSONTyped(value?: GetVpsConfigInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
    };
}

