/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetVpsConfigRequestContent
 */
export interface GetVpsConfigRequestContent {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof GetVpsConfigRequestContent
     */
    serviceId: string;
}

/**
 * Check if a given object implements the GetVpsConfigRequestContent interface.
 */
export function instanceOfGetVpsConfigRequestContent(value: object): value is GetVpsConfigRequestContent {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    return true;
}

export function GetVpsConfigRequestContentFromJSON(json: any): GetVpsConfigRequestContent {
    return GetVpsConfigRequestContentFromJSONTyped(json, false);
}

export function GetVpsConfigRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVpsConfigRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
    };
}

export function GetVpsConfigRequestContentToJSON(json: any): GetVpsConfigRequestContent {
    return GetVpsConfigRequestContentToJSONTyped(json, false);
}

export function GetVpsConfigRequestContentToJSONTyped(value?: GetVpsConfigRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
    };
}

