/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternalServiceError
 */
export interface InternalServiceError {
    /**
     * 
     * @type {string}
     * @memberof InternalServiceError
     */
    message: string;
    /**
     * Empty object for operations that don't return data
     * @type {object}
     * @memberof InternalServiceError
     */
    data: object;
}

/**
 * Check if a given object implements the InternalServiceError interface.
 */
export function instanceOfInternalServiceError(value: object): value is InternalServiceError {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function InternalServiceErrorFromJSON(json: any): InternalServiceError {
    return InternalServiceErrorFromJSONTyped(json, false);
}

export function InternalServiceErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalServiceError {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'data': json['data'],
    };
}

export function InternalServiceErrorToJSON(json: any): InternalServiceError {
    return InternalServiceErrorToJSONTyped(json, false);
}

export function InternalServiceErrorToJSONTyped(value?: InternalServiceError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'data': value['data'],
    };
}

