/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListReinstallOsResponseData } from './ListReinstallOsResponseData';
import {
    ListReinstallOsResponseDataFromJSON,
    ListReinstallOsResponseDataFromJSONTyped,
    ListReinstallOsResponseDataToJSON,
    ListReinstallOsResponseDataToJSONTyped,
} from './ListReinstallOsResponseData';
import type { OperationStatus } from './OperationStatus';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus';

/**
 * 
 * @export
 * @interface ListReinstallOsOutput
 */
export interface ListReinstallOsOutput {
    /**
     * 
     * @type {OperationStatus}
     * @memberof ListReinstallOsOutput
     */
    status: OperationStatus;
    /**
     * 
     * @type {ListReinstallOsResponseData}
     * @memberof ListReinstallOsOutput
     */
    data: ListReinstallOsResponseData;
}



/**
 * Check if a given object implements the ListReinstallOsOutput interface.
 */
export function instanceOfListReinstallOsOutput(value: object): value is ListReinstallOsOutput {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListReinstallOsOutputFromJSON(json: any): ListReinstallOsOutput {
    return ListReinstallOsOutputFromJSONTyped(json, false);
}

export function ListReinstallOsOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListReinstallOsOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': ListReinstallOsResponseDataFromJSON(json['data']),
    };
}

export function ListReinstallOsOutputToJSON(json: any): ListReinstallOsOutput {
    return ListReinstallOsOutputToJSONTyped(json, false);
}

export function ListReinstallOsOutputToJSONTyped(value?: ListReinstallOsOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': ListReinstallOsResponseDataToJSON(value['data']),
    };
}

