/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ListOrdersResponseData } from './ListOrdersResponseData.js';
import {
    ListOrdersResponseDataFromJSON,
    ListOrdersResponseDataFromJSONTyped,
    ListOrdersResponseDataToJSON,
    ListOrdersResponseDataToJSONTyped,
} from './ListOrdersResponseData.js';
import type { OperationStatus } from './OperationStatus.js';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus.js';

/**
 * 
 * @export
 * @interface ListOrdersResponseContent
 */
export interface ListOrdersResponseContent {
    /**
     * 
     * @type {OperationStatus}
     * @memberof ListOrdersResponseContent
     */
    status: OperationStatus;
    /**
     * 
     * @type {ListOrdersResponseData}
     * @memberof ListOrdersResponseContent
     */
    data: ListOrdersResponseData;
}



/**
 * Check if a given object implements the ListOrdersResponseContent interface.
 */
export function instanceOfListOrdersResponseContent(value: object): value is ListOrdersResponseContent {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListOrdersResponseContentFromJSON(json: any): ListOrdersResponseContent {
    return ListOrdersResponseContentFromJSONTyped(json, false);
}

export function ListOrdersResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrdersResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': ListOrdersResponseDataFromJSON(json['data']),
    };
}

export function ListOrdersResponseContentToJSON(json: any): ListOrdersResponseContent {
    return ListOrdersResponseContentToJSONTyped(json, false);
}

export function ListOrdersResponseContentToJSONTyped(value?: ListOrdersResponseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': ListOrdersResponseDataToJSON(value['data']),
    };
}

