/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListNotificationsInput
 */
export interface ListNotificationsInput {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof ListNotificationsInput
     */
    serviceId: string;
}

/**
 * Check if a given object implements the ListNotificationsInput interface.
 */
export function instanceOfListNotificationsInput(value: object): value is ListNotificationsInput {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    return true;
}

export function ListNotificationsInputFromJSON(json: any): ListNotificationsInput {
    return ListNotificationsInputFromJSONTyped(json, false);
}

export function ListNotificationsInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListNotificationsInput {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
    };
}

export function ListNotificationsInputToJSON(json: any): ListNotificationsInput {
    return ListNotificationsInputToJSONTyped(json, false);
}

export function ListNotificationsInputToJSONTyped(value?: ListNotificationsInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
    };
}

