/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response data for reinstall list OS operation
 * @export
 * @interface ListReinstallOsResponseData
 */
export interface ListReinstallOsResponseData {
    /**
     * Status message indicating the result
     * @type {string}
     * @memberof ListReinstallOsResponseData
     */
    message: string;
    /**
     * List of available OS templates
     * @type {Array<string>}
     * @memberof ListReinstallOsResponseData
     */
    templates: Array<string>;
}

/**
 * Check if a given object implements the ListReinstallOsResponseData interface.
 */
export function instanceOfListReinstallOsResponseData(value: object): value is ListReinstallOsResponseData {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('templates' in value) || value['templates'] === undefined) return false;
    return true;
}

export function ListReinstallOsResponseDataFromJSON(json: any): ListReinstallOsResponseData {
    return ListReinstallOsResponseDataFromJSONTyped(json, false);
}

export function ListReinstallOsResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListReinstallOsResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'templates': json['templates'],
    };
}

export function ListReinstallOsResponseDataToJSON(json: any): ListReinstallOsResponseData {
    return ListReinstallOsResponseDataToJSONTyped(json, false);
}

export function ListReinstallOsResponseDataToJSONTyped(value?: ListReinstallOsResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'templates': value['templates'],
    };
}

