/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListBackupsInput
 */
export interface ListBackupsInput {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof ListBackupsInput
     */
    serviceId: string;
}

/**
 * Check if a given object implements the ListBackupsInput interface.
 */
export function instanceOfListBackupsInput(value: object): value is ListBackupsInput {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    return true;
}

export function ListBackupsInputFromJSON(json: any): ListBackupsInput {
    return ListBackupsInputFromJSONTyped(json, false);
}

export function ListBackupsInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListBackupsInput {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
    };
}

export function ListBackupsInputToJSON(json: any): ListBackupsInput {
    return ListBackupsInputToJSONTyped(json, false);
}

export function ListBackupsInputToJSONTyped(value?: ListBackupsInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
    };
}

