/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListReinstallOsResponseData } from './ListReinstallOsResponseData';
import {
    ListReinstallOsResponseDataFromJSON,
    ListReinstallOsResponseDataFromJSONTyped,
    ListReinstallOsResponseDataToJSON,
    ListReinstallOsResponseDataToJSONTyped,
} from './ListReinstallOsResponseData';
import type { OperationStatus } from './OperationStatus';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus';

/**
 * 
 * @export
 * @interface ListReinstallOsResponseContent
 */
export interface ListReinstallOsResponseContent {
    /**
     * 
     * @type {OperationStatus}
     * @memberof ListReinstallOsResponseContent
     */
    status: OperationStatus;
    /**
     * 
     * @type {ListReinstallOsResponseData}
     * @memberof ListReinstallOsResponseContent
     */
    data: ListReinstallOsResponseData;
}



/**
 * Check if a given object implements the ListReinstallOsResponseContent interface.
 */
export function instanceOfListReinstallOsResponseContent(value: object): value is ListReinstallOsResponseContent {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListReinstallOsResponseContentFromJSON(json: any): ListReinstallOsResponseContent {
    return ListReinstallOsResponseContentFromJSONTyped(json, false);
}

export function ListReinstallOsResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListReinstallOsResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': ListReinstallOsResponseDataFromJSON(json['data']),
    };
}

export function ListReinstallOsResponseContentToJSON(json: any): ListReinstallOsResponseContent {
    return ListReinstallOsResponseContentToJSONTyped(json, false);
}

export function ListReinstallOsResponseContentToJSONTyped(value?: ListReinstallOsResponseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': ListReinstallOsResponseDataToJSON(value['data']),
    };
}

