/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { DomainInfo } from './DomainInfo.js';
import {
    DomainInfoFromJSON,
    DomainInfoFromJSONTyped,
    DomainInfoToJSON,
    DomainInfoToJSONTyped,
} from './DomainInfo.js';

/**
 * List domains response data
 * @export
 * @interface ListDomainsData
 */
export interface ListDomainsData {
    /**
     * Status message indicating the result
     * @type {string}
     * @memberof ListDomainsData
     */
    message: string;
    /**
     * Domains owned by the authenticated client
     * @type {Array<DomainInfo>}
     * @memberof ListDomainsData
     */
    domains: Array<DomainInfo>;
    /**
     * Whether ID-protection warranty is enabled for the account
     * @type {boolean}
     * @memberof ListDomainsData
     */
    domainWarranty: boolean;
    /**
     * Domain warranty rename setting when configured
     * @type {string}
     * @memberof ListDomainsData
     */
    domainWarrantyRename?: string;
    /**
     * Whether domain evaluation is available for the account
     * @type {boolean}
     * @memberof ListDomainsData
     */
    domainEvaluationAvailable: boolean;
    /**
     * Total number of domains returned
     * @type {number}
     * @memberof ListDomainsData
     */
    totalCount: number;
}

/**
 * Check if a given object implements the ListDomainsData interface.
 */
export function instanceOfListDomainsData(value: object): value is ListDomainsData {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('domains' in value) || value['domains'] === undefined) return false;
    if (!('domainWarranty' in value) || value['domainWarranty'] === undefined) return false;
    if (!('domainEvaluationAvailable' in value) || value['domainEvaluationAvailable'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    return true;
}

export function ListDomainsDataFromJSON(json: any): ListDomainsData {
    return ListDomainsDataFromJSONTyped(json, false);
}

export function ListDomainsDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListDomainsData {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'domains': ((json['domains'] as Array<any>).map(DomainInfoFromJSON)),
        'domainWarranty': json['domain_warranty'],
        'domainWarrantyRename': json['domain_warranty_rename'] == null ? undefined : json['domain_warranty_rename'],
        'domainEvaluationAvailable': json['domain_evaluation_available'],
        'totalCount': json['total_count'],
    };
}

export function ListDomainsDataToJSON(json: any): ListDomainsData {
    return ListDomainsDataToJSONTyped(json, false);
}

export function ListDomainsDataToJSONTyped(value?: ListDomainsData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'domains': ((value['domains'] as Array<any>).map(DomainInfoToJSON)),
        'domain_warranty': value['domainWarranty'],
        'domain_warranty_rename': value['domainWarrantyRename'],
        'domain_evaluation_available': value['domainEvaluationAvailable'],
        'total_count': value['totalCount'],
    };
}

