/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ListPowerTasksRequestContent
 */
export interface ListPowerTasksRequestContent {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof ListPowerTasksRequestContent
     */
    serviceId: string;
}

/**
 * Check if a given object implements the ListPowerTasksRequestContent interface.
 */
export function instanceOfListPowerTasksRequestContent(value: object): value is ListPowerTasksRequestContent {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    return true;
}

export function ListPowerTasksRequestContentFromJSON(json: any): ListPowerTasksRequestContent {
    return ListPowerTasksRequestContentFromJSONTyped(json, false);
}

export function ListPowerTasksRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPowerTasksRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
    };
}

export function ListPowerTasksRequestContentToJSON(json: any): ListPowerTasksRequestContent {
    return ListPowerTasksRequestContentToJSONTyped(json, false);
}

export function ListPowerTasksRequestContentToJSONTyped(value?: ListPowerTasksRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
    };
}

