/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OperationStatus } from './OperationStatus';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus';
import type { FirewallListResponseData } from './FirewallListResponseData';
import {
    FirewallListResponseDataFromJSON,
    FirewallListResponseDataFromJSONTyped,
    FirewallListResponseDataToJSON,
    FirewallListResponseDataToJSONTyped,
} from './FirewallListResponseData';

/**
 * 
 * @export
 * @interface ListFirewallRulesOutput
 */
export interface ListFirewallRulesOutput {
    /**
     * 
     * @type {OperationStatus}
     * @memberof ListFirewallRulesOutput
     */
    status: OperationStatus;
    /**
     * 
     * @type {FirewallListResponseData}
     * @memberof ListFirewallRulesOutput
     */
    data: FirewallListResponseData;
}



/**
 * Check if a given object implements the ListFirewallRulesOutput interface.
 */
export function instanceOfListFirewallRulesOutput(value: object): value is ListFirewallRulesOutput {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListFirewallRulesOutputFromJSON(json: any): ListFirewallRulesOutput {
    return ListFirewallRulesOutputFromJSONTyped(json, false);
}

export function ListFirewallRulesOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListFirewallRulesOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': FirewallListResponseDataFromJSON(json['data']),
    };
}

export function ListFirewallRulesOutputToJSON(json: any): ListFirewallRulesOutput {
    return ListFirewallRulesOutputToJSONTyped(json, false);
}

export function ListFirewallRulesOutputToJSONTyped(value?: ListFirewallRulesOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': FirewallListResponseDataToJSON(value['data']),
    };
}

