/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListAllowedFeaturesRequestContent
 */
export interface ListAllowedFeaturesRequestContent {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof ListAllowedFeaturesRequestContent
     */
    serviceId: string;
}

/**
 * Check if a given object implements the ListAllowedFeaturesRequestContent interface.
 */
export function instanceOfListAllowedFeaturesRequestContent(value: object): value is ListAllowedFeaturesRequestContent {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    return true;
}

export function ListAllowedFeaturesRequestContentFromJSON(json: any): ListAllowedFeaturesRequestContent {
    return ListAllowedFeaturesRequestContentFromJSONTyped(json, false);
}

export function ListAllowedFeaturesRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAllowedFeaturesRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
    };
}

export function ListAllowedFeaturesRequestContentToJSON(json: any): ListAllowedFeaturesRequestContent {
    return ListAllowedFeaturesRequestContentToJSONTyped(json, false);
}

export function ListAllowedFeaturesRequestContentToJSONTyped(value?: ListAllowedFeaturesRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
    };
}

