/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { OperationStatus } from './OperationStatus.js';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus.js';
import type { ServiceSnapshotsResponseData } from './ServiceSnapshotsResponseData.js';
import {
    ServiceSnapshotsResponseDataFromJSON,
    ServiceSnapshotsResponseDataFromJSONTyped,
    ServiceSnapshotsResponseDataToJSON,
    ServiceSnapshotsResponseDataToJSONTyped,
} from './ServiceSnapshotsResponseData.js';

/**
 * 
 * @export
 * @interface ListSnapshotsResponseContent
 */
export interface ListSnapshotsResponseContent {
    /**
     * 
     * @type {OperationStatus}
     * @memberof ListSnapshotsResponseContent
     */
    status: OperationStatus;
    /**
     * 
     * @type {ServiceSnapshotsResponseData}
     * @memberof ListSnapshotsResponseContent
     */
    data: ServiceSnapshotsResponseData;
}



/**
 * Check if a given object implements the ListSnapshotsResponseContent interface.
 */
export function instanceOfListSnapshotsResponseContent(value: object): value is ListSnapshotsResponseContent {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListSnapshotsResponseContentFromJSON(json: any): ListSnapshotsResponseContent {
    return ListSnapshotsResponseContentFromJSONTyped(json, false);
}

export function ListSnapshotsResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSnapshotsResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': ServiceSnapshotsResponseDataFromJSON(json['data']),
    };
}

export function ListSnapshotsResponseContentToJSON(json: any): ListSnapshotsResponseContent {
    return ListSnapshotsResponseContentToJSONTyped(json, false);
}

export function ListSnapshotsResponseContentToJSONTyped(value?: ListSnapshotsResponseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': ServiceSnapshotsResponseDataToJSON(value['data']),
    };
}

