/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AllowedFeaturesResponseData } from './AllowedFeaturesResponseData';
import {
    AllowedFeaturesResponseDataFromJSON,
    AllowedFeaturesResponseDataFromJSONTyped,
    AllowedFeaturesResponseDataToJSON,
    AllowedFeaturesResponseDataToJSONTyped,
} from './AllowedFeaturesResponseData';
import type { OperationStatus } from './OperationStatus';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus';

/**
 * 
 * @export
 * @interface ListAllowedFeaturesResponseContent
 */
export interface ListAllowedFeaturesResponseContent {
    /**
     * 
     * @type {OperationStatus}
     * @memberof ListAllowedFeaturesResponseContent
     */
    status: OperationStatus;
    /**
     * 
     * @type {AllowedFeaturesResponseData}
     * @memberof ListAllowedFeaturesResponseContent
     */
    data: AllowedFeaturesResponseData;
}



/**
 * Check if a given object implements the ListAllowedFeaturesResponseContent interface.
 */
export function instanceOfListAllowedFeaturesResponseContent(value: object): value is ListAllowedFeaturesResponseContent {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListAllowedFeaturesResponseContentFromJSON(json: any): ListAllowedFeaturesResponseContent {
    return ListAllowedFeaturesResponseContentFromJSONTyped(json, false);
}

export function ListAllowedFeaturesResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAllowedFeaturesResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': AllowedFeaturesResponseDataFromJSON(json['data']),
    };
}

export function ListAllowedFeaturesResponseContentToJSON(json: any): ListAllowedFeaturesResponseContent {
    return ListAllowedFeaturesResponseContentToJSONTyped(json, false);
}

export function ListAllowedFeaturesResponseContentToJSONTyped(value?: ListAllowedFeaturesResponseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': AllowedFeaturesResponseDataToJSON(value['data']),
    };
}

