/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BackupScheduleListResponseData } from './BackupScheduleListResponseData';
import {
    BackupScheduleListResponseDataFromJSON,
    BackupScheduleListResponseDataFromJSONTyped,
    BackupScheduleListResponseDataToJSON,
    BackupScheduleListResponseDataToJSONTyped,
} from './BackupScheduleListResponseData';
import type { OperationStatus } from './OperationStatus';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus';

/**
 * 
 * @export
 * @interface ListBackupSchedulesResponseContent
 */
export interface ListBackupSchedulesResponseContent {
    /**
     * 
     * @type {OperationStatus}
     * @memberof ListBackupSchedulesResponseContent
     */
    status: OperationStatus;
    /**
     * 
     * @type {BackupScheduleListResponseData}
     * @memberof ListBackupSchedulesResponseContent
     */
    data: BackupScheduleListResponseData;
}



/**
 * Check if a given object implements the ListBackupSchedulesResponseContent interface.
 */
export function instanceOfListBackupSchedulesResponseContent(value: object): value is ListBackupSchedulesResponseContent {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListBackupSchedulesResponseContentFromJSON(json: any): ListBackupSchedulesResponseContent {
    return ListBackupSchedulesResponseContentFromJSONTyped(json, false);
}

export function ListBackupSchedulesResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListBackupSchedulesResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': BackupScheduleListResponseDataFromJSON(json['data']),
    };
}

export function ListBackupSchedulesResponseContentToJSON(json: any): ListBackupSchedulesResponseContent {
    return ListBackupSchedulesResponseContentToJSONTyped(json, false);
}

export function ListBackupSchedulesResponseContentToJSONTyped(value?: ListBackupSchedulesResponseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': BackupScheduleListResponseDataToJSON(value['data']),
    };
}

