/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListBackupsRequestContent
 */
export interface ListBackupsRequestContent {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof ListBackupsRequestContent
     */
    serviceId: string;
}

/**
 * Check if a given object implements the ListBackupsRequestContent interface.
 */
export function instanceOfListBackupsRequestContent(value: object): value is ListBackupsRequestContent {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    return true;
}

export function ListBackupsRequestContentFromJSON(json: any): ListBackupsRequestContent {
    return ListBackupsRequestContentFromJSONTyped(json, false);
}

export function ListBackupsRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListBackupsRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
    };
}

export function ListBackupsRequestContentToJSON(json: any): ListBackupsRequestContent {
    return ListBackupsRequestContentToJSONTyped(json, false);
}

export function ListBackupsRequestContentToJSONTyped(value?: ListBackupsRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
    };
}

