/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListFirewallRulesInput
 */
export interface ListFirewallRulesInput {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof ListFirewallRulesInput
     */
    serviceId: string;
}

/**
 * Check if a given object implements the ListFirewallRulesInput interface.
 */
export function instanceOfListFirewallRulesInput(value: object): value is ListFirewallRulesInput {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    return true;
}

export function ListFirewallRulesInputFromJSON(json: any): ListFirewallRulesInput {
    return ListFirewallRulesInputFromJSONTyped(json, false);
}

export function ListFirewallRulesInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListFirewallRulesInput {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
    };
}

export function ListFirewallRulesInputToJSON(json: any): ListFirewallRulesInput {
    return ListFirewallRulesInputToJSONTyped(json, false);
}

export function ListFirewallRulesInputToJSONTyped(value?: ListFirewallRulesInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
    };
}

