/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ListVpsServicesData } from './ListVpsServicesData.js';
import {
    ListVpsServicesDataFromJSON,
    ListVpsServicesDataFromJSONTyped,
    ListVpsServicesDataToJSON,
    ListVpsServicesDataToJSONTyped,
} from './ListVpsServicesData.js';
import type { OperationStatus } from './OperationStatus.js';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus.js';

/**
 * 
 * @export
 * @interface ListVpsServicesResponseContent
 */
export interface ListVpsServicesResponseContent {
    /**
     * 
     * @type {OperationStatus}
     * @memberof ListVpsServicesResponseContent
     */
    status: OperationStatus;
    /**
     * 
     * @type {ListVpsServicesData}
     * @memberof ListVpsServicesResponseContent
     */
    data: ListVpsServicesData;
}



/**
 * Check if a given object implements the ListVpsServicesResponseContent interface.
 */
export function instanceOfListVpsServicesResponseContent(value: object): value is ListVpsServicesResponseContent {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListVpsServicesResponseContentFromJSON(json: any): ListVpsServicesResponseContent {
    return ListVpsServicesResponseContentFromJSONTyped(json, false);
}

export function ListVpsServicesResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListVpsServicesResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': ListVpsServicesDataFromJSON(json['data']),
    };
}

export function ListVpsServicesResponseContentToJSON(json: any): ListVpsServicesResponseContent {
    return ListVpsServicesResponseContentToJSONTyped(json, false);
}

export function ListVpsServicesResponseContentToJSONTyped(value?: ListVpsServicesResponseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': ListVpsServicesDataToJSON(value['data']),
    };
}

