/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListRdnsResponseData } from './ListRdnsResponseData';
import {
    ListRdnsResponseDataFromJSON,
    ListRdnsResponseDataFromJSONTyped,
    ListRdnsResponseDataToJSON,
    ListRdnsResponseDataToJSONTyped,
} from './ListRdnsResponseData';
import type { OperationStatus } from './OperationStatus';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus';

/**
 * 
 * @export
 * @interface ListRdnsRecordsOutput
 */
export interface ListRdnsRecordsOutput {
    /**
     * 
     * @type {OperationStatus}
     * @memberof ListRdnsRecordsOutput
     */
    status: OperationStatus;
    /**
     * 
     * @type {ListRdnsResponseData}
     * @memberof ListRdnsRecordsOutput
     */
    data: ListRdnsResponseData;
}



/**
 * Check if a given object implements the ListRdnsRecordsOutput interface.
 */
export function instanceOfListRdnsRecordsOutput(value: object): value is ListRdnsRecordsOutput {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListRdnsRecordsOutputFromJSON(json: any): ListRdnsRecordsOutput {
    return ListRdnsRecordsOutputFromJSONTyped(json, false);
}

export function ListRdnsRecordsOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListRdnsRecordsOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': ListRdnsResponseDataFromJSON(json['data']),
    };
}

export function ListRdnsRecordsOutputToJSON(json: any): ListRdnsRecordsOutput {
    return ListRdnsRecordsOutputToJSONTyped(json, false);
}

export function ListRdnsRecordsOutputToJSONTyped(value?: ListRdnsRecordsOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': ListRdnsResponseDataToJSON(value['data']),
    };
}

