/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ListIsosRequestContent
 */
export interface ListIsosRequestContent {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof ListIsosRequestContent
     */
    serviceId: string;
}

/**
 * Check if a given object implements the ListIsosRequestContent interface.
 */
export function instanceOfListIsosRequestContent(value: object): value is ListIsosRequestContent {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    return true;
}

export function ListIsosRequestContentFromJSON(json: any): ListIsosRequestContent {
    return ListIsosRequestContentFromJSONTyped(json, false);
}

export function ListIsosRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListIsosRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
    };
}

export function ListIsosRequestContentToJSON(json: any): ListIsosRequestContent {
    return ListIsosRequestContentToJSONTyped(json, false);
}

export function ListIsosRequestContentToJSONTyped(value?: ListIsosRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
    };
}

