/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Notification } from './Notification';
import {
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
    NotificationToJSONTyped,
} from './Notification';

/**
 * Response data for notification creation operation
 * @export
 * @interface NotificationCreateResponseData
 */
export interface NotificationCreateResponseData {
    /**
     * Status message indicating the result
     * @type {string}
     * @memberof NotificationCreateResponseData
     */
    message: string;
    /**
     * 
     * @type {Notification}
     * @memberof NotificationCreateResponseData
     */
    notification: Notification;
}

/**
 * Check if a given object implements the NotificationCreateResponseData interface.
 */
export function instanceOfNotificationCreateResponseData(value: object): value is NotificationCreateResponseData {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('notification' in value) || value['notification'] === undefined) return false;
    return true;
}

export function NotificationCreateResponseDataFromJSON(json: any): NotificationCreateResponseData {
    return NotificationCreateResponseDataFromJSONTyped(json, false);
}

export function NotificationCreateResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationCreateResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'notification': NotificationFromJSON(json['notification']),
    };
}

export function NotificationCreateResponseDataToJSON(json: any): NotificationCreateResponseData {
    return NotificationCreateResponseDataToJSONTyped(json, false);
}

export function NotificationCreateResponseDataToJSONTyped(value?: NotificationCreateResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'notification': NotificationToJSON(value['notification']),
    };
}

