/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Details of the most recent payment attempt for an order
 * @export
 * @interface OrderLastAttempt
 */
export interface OrderLastAttempt {
    /**
     * Timestamp of the attempt (ISO 8601)
     * @type {string}
     * @memberof OrderLastAttempt
     */
    at: string;
    /**
     * Attempt status (e.g. paid, failed)
     * @type {string}
     * @memberof OrderLastAttempt
     */
    status: string;
    /**
     * Error code from the payment provider, if applicable
     * @type {string}
     * @memberof OrderLastAttempt
     */
    code?: string;
    /**
     * Human-readable message from the payment provider, if applicable
     * @type {string}
     * @memberof OrderLastAttempt
     */
    message?: string;
}

/**
 * Check if a given object implements the OrderLastAttempt interface.
 */
export function instanceOfOrderLastAttempt(value: object): value is OrderLastAttempt {
    if (!('at' in value) || value['at'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function OrderLastAttemptFromJSON(json: any): OrderLastAttempt {
    return OrderLastAttemptFromJSONTyped(json, false);
}

export function OrderLastAttemptFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderLastAttempt {
    if (json == null) {
        return json;
    }
    return {
        
        'at': json['at'],
        'status': json['status'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function OrderLastAttemptToJSON(json: any): OrderLastAttempt {
    return OrderLastAttemptToJSONTyped(json, false);
}

export function OrderLastAttemptToJSONTyped(value?: OrderLastAttempt | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'at': value['at'],
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
    };
}

