/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Encryption metadata for an RSA-OAEP encrypted password
 * @export
 * @interface PasswordEncryptionInfo
 */
export interface PasswordEncryptionInfo {
    /**
     * Asymmetric encryption algorithm. Always "RSA-OAEP".
     * @type {string}
     * @memberof PasswordEncryptionInfo
     */
    algorithm: string;
    /**
     * OAEP hash / MGF1 hash function. Always "SHA-256".
     * @type {string}
     * @memberof PasswordEncryptionInfo
     */
    hash: string;
    /**
     * RSA modulus size in bits. Always 4096.
     * @type {number}
     * @memberof PasswordEncryptionInfo
     */
    keySize: number;
    /**
     * Encoding of the password ciphertext field. Always "base64" (standard alphabet, not URL-safe).
     * @type {string}
     * @memberof PasswordEncryptionInfo
     */
    encoding: string;
}

/**
 * Check if a given object implements the PasswordEncryptionInfo interface.
 */
export function instanceOfPasswordEncryptionInfo(value: object): value is PasswordEncryptionInfo {
    if (!('algorithm' in value) || value['algorithm'] === undefined) return false;
    if (!('hash' in value) || value['hash'] === undefined) return false;
    if (!('keySize' in value) || value['keySize'] === undefined) return false;
    if (!('encoding' in value) || value['encoding'] === undefined) return false;
    return true;
}

export function PasswordEncryptionInfoFromJSON(json: any): PasswordEncryptionInfo {
    return PasswordEncryptionInfoFromJSONTyped(json, false);
}

export function PasswordEncryptionInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordEncryptionInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'algorithm': json['algorithm'],
        'hash': json['hash'],
        'keySize': json['keySize'],
        'encoding': json['encoding'],
    };
}

export function PasswordEncryptionInfoToJSON(json: any): PasswordEncryptionInfo {
    return PasswordEncryptionInfoToJSONTyped(json, false);
}

export function PasswordEncryptionInfoToJSONTyped(value?: PasswordEncryptionInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'algorithm': value['algorithm'],
        'hash': value['hash'],
        'keySize': value['keySize'],
        'encoding': value['encoding'],
    };
}

