/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Power task action enum
 * @export
 */
export const PowerTaskAction = {
    Start: 'start',
    Stop: 'stop',
    Restart: 'restart'
} as const;
export type PowerTaskAction = typeof PowerTaskAction[keyof typeof PowerTaskAction];


export function instanceOfPowerTaskAction(value: any): boolean {
    for (const key in PowerTaskAction) {
        if (Object.prototype.hasOwnProperty.call(PowerTaskAction, key)) {
            if (PowerTaskAction[key as keyof typeof PowerTaskAction] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PowerTaskActionFromJSON(json: any): PowerTaskAction {
    return PowerTaskActionFromJSONTyped(json, false);
}

export function PowerTaskActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PowerTaskAction {
    return json as PowerTaskAction;
}

export function PowerTaskActionToJSON(value?: PowerTaskAction | null): any {
    return value as any;
}

export function PowerTaskActionToJSONTyped(value: any, ignoreDiscriminator: boolean): PowerTaskAction {
    return value as PowerTaskAction;
}

