/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A PTR record owned by the client
 * @export
 * @interface RdnsRecord
 */
export interface RdnsRecord {
    /**
     * Record identifier — use as record_id in PUT/DELETE
     * @type {number}
     * @memberof RdnsRecord
     */
    id: number;
    /**
     * The IPv4/IPv6 address the PTR points from
     * @type {string}
     * @memberof RdnsRecord
     */
    ip: string;
    /**
     * Final concatenated PTR target (sub.from)
     * @type {string}
     * @memberof RdnsRecord
     */
    hostname: string;
    /**
     * Time-to-live in seconds
     * @type {number}
     * @memberof RdnsRecord
     */
    ttl?: number;
    /**
     * Zone type: 0=OTHER, 1=DOMAIN, 2=HOSTING, 3=ADDON
     * @type {number}
     * @memberof RdnsRecord
     */
    type?: number;
    /**
     * Related service id (tblhosting.id / tblhostingaddons.id / tbldomains.id)
     * @type {number}
     * @memberof RdnsRecord
     */
    relid?: number;
    /**
     * 
     * @type {number}
     * @memberof RdnsRecord
     */
    serverid: number;
    /**
     * 
     * @type {number}
     * @memberof RdnsRecord
     */
    clientid: number;
    /**
     * 
     * @type {number}
     * @memberof RdnsRecord
     */
    packageid: number;
    /**
     * Reverse-DNS zone name (e.g. 10.113.0.203.in-addr.arpa)
     * @type {string}
     * @memberof RdnsRecord
     */
    from?: string;
    /**
     * Sub-label component of the PTR
     * @type {string}
     * @memberof RdnsRecord
     */
    sub?: string;
    /**
     * Full PTR name (e.g. 10.113.0.203.in-addr.arpa)
     * @type {string}
     * @memberof RdnsRecord
     */
    name?: string;
}

/**
 * Check if a given object implements the RdnsRecord interface.
 */
export function instanceOfRdnsRecord(value: object): value is RdnsRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ip' in value) || value['ip'] === undefined) return false;
    if (!('hostname' in value) || value['hostname'] === undefined) return false;
    if (!('serverid' in value) || value['serverid'] === undefined) return false;
    if (!('clientid' in value) || value['clientid'] === undefined) return false;
    if (!('packageid' in value) || value['packageid'] === undefined) return false;
    return true;
}

export function RdnsRecordFromJSON(json: any): RdnsRecord {
    return RdnsRecordFromJSONTyped(json, false);
}

export function RdnsRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): RdnsRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ip': json['ip'],
        'hostname': json['hostname'],
        'ttl': json['ttl'] == null ? undefined : json['ttl'],
        'type': json['type'] == null ? undefined : json['type'],
        'relid': json['relid'] == null ? undefined : json['relid'],
        'serverid': json['serverid'],
        'clientid': json['clientid'],
        'packageid': json['packageid'],
        'from': json['from'] == null ? undefined : json['from'],
        'sub': json['sub'] == null ? undefined : json['sub'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function RdnsRecordToJSON(json: any): RdnsRecord {
    return RdnsRecordToJSONTyped(json, false);
}

export function RdnsRecordToJSONTyped(value?: RdnsRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'ip': value['ip'],
        'hostname': value['hostname'],
        'ttl': value['ttl'],
        'type': value['type'],
        'relid': value['relid'],
        'serverid': value['serverid'],
        'clientid': value['clientid'],
        'packageid': value['packageid'],
        'from': value['from'],
        'sub': value['sub'],
        'name': value['name'],
    };
}

