/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A subnet pool entry within an available rDNS item
 * @export
 * @interface RdnsPool
 */
export interface RdnsPool {
    /**
     * Network address of the pool
     * @type {string}
     * @memberof RdnsPool
     */
    pool: string;
    /**
     * CIDR prefix length
     * @type {number}
     * @memberof RdnsPool
     */
    mask: number;
}

/**
 * Check if a given object implements the RdnsPool interface.
 */
export function instanceOfRdnsPool(value: object): value is RdnsPool {
    if (!('pool' in value) || value['pool'] === undefined) return false;
    if (!('mask' in value) || value['mask'] === undefined) return false;
    return true;
}

export function RdnsPoolFromJSON(json: any): RdnsPool {
    return RdnsPoolFromJSONTyped(json, false);
}

export function RdnsPoolFromJSONTyped(json: any, ignoreDiscriminator: boolean): RdnsPool {
    if (json == null) {
        return json;
    }
    return {
        
        'pool': json['pool'],
        'mask': json['mask'],
    };
}

export function RdnsPoolToJSON(json: any): RdnsPool {
    return RdnsPoolToJSONTyped(json, false);
}

export function RdnsPoolToJSONTyped(value?: RdnsPool | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pool': value['pool'],
        'mask': value['mask'],
    };
}

