/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface RestoreBackupRequestContent
 */
export interface RestoreBackupRequestContent {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof RestoreBackupRequestContent
     */
    serviceId: string;
    /**
     * Backup identifier for the backup to restore
     * @type {string}
     * @memberof RestoreBackupRequestContent
     */
    backupId: string;
}

/**
 * Check if a given object implements the RestoreBackupRequestContent interface.
 */
export function instanceOfRestoreBackupRequestContent(value: object): value is RestoreBackupRequestContent {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('backupId' in value) || value['backupId'] === undefined) return false;
    return true;
}

export function RestoreBackupRequestContentFromJSON(json: any): RestoreBackupRequestContent {
    return RestoreBackupRequestContentFromJSONTyped(json, false);
}

export function RestoreBackupRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestoreBackupRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
        'backupId': json['backup_id'],
    };
}

export function RestoreBackupRequestContentToJSON(json: any): RestoreBackupRequestContent {
    return RestoreBackupRequestContentToJSONTyped(json, false);
}

export function RestoreBackupRequestContentToJSONTyped(value?: RestoreBackupRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
        'backup_id': value['backupId'],
    };
}

