/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface RetryPaymentRequestContent
 */
export interface RetryPaymentRequestContent {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof RetryPaymentRequestContent
     */
    serviceId: string;
    /**
     * The order identifier to retry payment for
     * @type {number}
     * @memberof RetryPaymentRequestContent
     */
    orderId: number;
}

/**
 * Check if a given object implements the RetryPaymentRequestContent interface.
 */
export function instanceOfRetryPaymentRequestContent(value: object): value is RetryPaymentRequestContent {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    return true;
}

export function RetryPaymentRequestContentFromJSON(json: any): RetryPaymentRequestContent {
    return RetryPaymentRequestContentFromJSONTyped(json, false);
}

export function RetryPaymentRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetryPaymentRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
        'orderId': json['order_id'],
    };
}

export function RetryPaymentRequestContentToJSON(json: any): RetryPaymentRequestContent {
    return RetryPaymentRequestContentToJSONTyped(json, false);
}

export function RetryPaymentRequestContentToJSONTyped(value?: RetryPaymentRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
        'order_id': value['orderId'],
    };
}

