/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RetryPaymentInput
 */
export interface RetryPaymentInput {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof RetryPaymentInput
     */
    serviceId: string;
    /**
     * The order identifier to retry payment for
     * @type {number}
     * @memberof RetryPaymentInput
     */
    orderId: number;
}

/**
 * Check if a given object implements the RetryPaymentInput interface.
 */
export function instanceOfRetryPaymentInput(value: object): value is RetryPaymentInput {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    return true;
}

export function RetryPaymentInputFromJSON(json: any): RetryPaymentInput {
    return RetryPaymentInputFromJSONTyped(json, false);
}

export function RetryPaymentInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetryPaymentInput {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
        'orderId': json['order_id'],
    };
}

export function RetryPaymentInputToJSON(json: any): RetryPaymentInput {
    return RetryPaymentInputToJSONTyped(json, false);
}

export function RetryPaymentInputToJSONTyped(value?: RetryPaymentInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
        'order_id': value['orderId'],
    };
}

