/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RetryPaymentResponseData } from './RetryPaymentResponseData';
import {
    RetryPaymentResponseDataFromJSON,
    RetryPaymentResponseDataFromJSONTyped,
    RetryPaymentResponseDataToJSON,
    RetryPaymentResponseDataToJSONTyped,
} from './RetryPaymentResponseData';
import type { OperationStatus } from './OperationStatus';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus';

/**
 * 
 * @export
 * @interface RetryPaymentResponseContent
 */
export interface RetryPaymentResponseContent {
    /**
     * 
     * @type {OperationStatus}
     * @memberof RetryPaymentResponseContent
     */
    status: OperationStatus;
    /**
     * 
     * @type {RetryPaymentResponseData}
     * @memberof RetryPaymentResponseContent
     */
    data: RetryPaymentResponseData;
}



/**
 * Check if a given object implements the RetryPaymentResponseContent interface.
 */
export function instanceOfRetryPaymentResponseContent(value: object): value is RetryPaymentResponseContent {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function RetryPaymentResponseContentFromJSON(json: any): RetryPaymentResponseContent {
    return RetryPaymentResponseContentFromJSONTyped(json, false);
}

export function RetryPaymentResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetryPaymentResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': RetryPaymentResponseDataFromJSON(json['data']),
    };
}

export function RetryPaymentResponseContentToJSON(json: any): RetryPaymentResponseContent {
    return RetryPaymentResponseContentToJSONTyped(json, false);
}

export function RetryPaymentResponseContentToJSONTyped(value?: RetryPaymentResponseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': RetryPaymentResponseDataToJSON(value['data']),
    };
}

