/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Total amount breakdown for a retry payment response
 * @export
 * @interface RetryPaymentTotal
 */
export interface RetryPaymentTotal {
    /**
     * Total amount charged
     * @type {string}
     * @memberof RetryPaymentTotal
     */
    amount: string;
    /**
     * Currency code (e.g. USD)
     * @type {string}
     * @memberof RetryPaymentTotal
     */
    currency: string;
    /**
     * Currency prefix symbol (e.g. US$)
     * @type {string}
     * @memberof RetryPaymentTotal
     */
    prefix: string;
}

/**
 * Check if a given object implements the RetryPaymentTotal interface.
 */
export function instanceOfRetryPaymentTotal(value: object): value is RetryPaymentTotal {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('prefix' in value) || value['prefix'] === undefined) return false;
    return true;
}

export function RetryPaymentTotalFromJSON(json: any): RetryPaymentTotal {
    return RetryPaymentTotalFromJSONTyped(json, false);
}

export function RetryPaymentTotalFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetryPaymentTotal {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'currency': json['currency'],
        'prefix': json['prefix'],
    };
}

export function RetryPaymentTotalToJSON(json: any): RetryPaymentTotal {
    return RetryPaymentTotalToJSONTyped(json, false);
}

export function RetryPaymentTotalToJSONTyped(value?: RetryPaymentTotal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'currency': value['currency'],
        'prefix': value['prefix'],
    };
}

