/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface RollbackSnapshotRequestContent
 */
export interface RollbackSnapshotRequestContent {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof RollbackSnapshotRequestContent
     */
    serviceId: string;
    /**
     * Snapshot name to rollback to
     * @type {string}
     * @memberof RollbackSnapshotRequestContent
     */
    snapshotName: string;
}

/**
 * Check if a given object implements the RollbackSnapshotRequestContent interface.
 */
export function instanceOfRollbackSnapshotRequestContent(value: object): value is RollbackSnapshotRequestContent {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('snapshotName' in value) || value['snapshotName'] === undefined) return false;
    return true;
}

export function RollbackSnapshotRequestContentFromJSON(json: any): RollbackSnapshotRequestContent {
    return RollbackSnapshotRequestContentFromJSONTyped(json, false);
}

export function RollbackSnapshotRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): RollbackSnapshotRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
        'snapshotName': json['snapshot_name'],
    };
}

export function RollbackSnapshotRequestContentToJSON(json: any): RollbackSnapshotRequestContent {
    return RollbackSnapshotRequestContentToJSONTyped(json, false);
}

export function RollbackSnapshotRequestContentToJSONTyped(value?: RollbackSnapshotRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
        'snapshot_name': value['snapshotName'],
    };
}

