/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VpsSimpleActionResponseData } from './VpsSimpleActionResponseData';
import {
    VpsSimpleActionResponseDataFromJSON,
    VpsSimpleActionResponseDataFromJSONTyped,
    VpsSimpleActionResponseDataToJSON,
    VpsSimpleActionResponseDataToJSONTyped,
} from './VpsSimpleActionResponseData';
import type { OperationStatus } from './OperationStatus';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus';

/**
 * 
 * @export
 * @interface RollbackSnapshotResponseContent
 */
export interface RollbackSnapshotResponseContent {
    /**
     * 
     * @type {OperationStatus}
     * @memberof RollbackSnapshotResponseContent
     */
    status: OperationStatus;
    /**
     * 
     * @type {VpsSimpleActionResponseData}
     * @memberof RollbackSnapshotResponseContent
     */
    data: VpsSimpleActionResponseData;
}



/**
 * Check if a given object implements the RollbackSnapshotResponseContent interface.
 */
export function instanceOfRollbackSnapshotResponseContent(value: object): value is RollbackSnapshotResponseContent {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function RollbackSnapshotResponseContentFromJSON(json: any): RollbackSnapshotResponseContent {
    return RollbackSnapshotResponseContentFromJSONTyped(json, false);
}

export function RollbackSnapshotResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): RollbackSnapshotResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': VpsSimpleActionResponseDataFromJSON(json['data']),
    };
}

export function RollbackSnapshotResponseContentToJSON(json: any): RollbackSnapshotResponseContent {
    return RollbackSnapshotResponseContentToJSONTyped(json, false);
}

export function RollbackSnapshotResponseContentToJSONTyped(value?: RollbackSnapshotResponseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': VpsSimpleActionResponseDataToJSON(value['data']),
    };
}

