/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SaveDomainRequiredDataData } from './SaveDomainRequiredDataData.js';
import {
    SaveDomainRequiredDataDataFromJSON,
    SaveDomainRequiredDataDataFromJSONTyped,
    SaveDomainRequiredDataDataToJSON,
    SaveDomainRequiredDataDataToJSONTyped,
} from './SaveDomainRequiredDataData.js';
import type { OperationStatus } from './OperationStatus.js';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus.js';

/**
 * 
 * @export
 * @interface SaveDomainRequiredDataResponseContent
 */
export interface SaveDomainRequiredDataResponseContent {
    /**
     * 
     * @type {OperationStatus}
     * @memberof SaveDomainRequiredDataResponseContent
     */
    status: OperationStatus;
    /**
     * 
     * @type {SaveDomainRequiredDataData}
     * @memberof SaveDomainRequiredDataResponseContent
     */
    data: SaveDomainRequiredDataData;
}



/**
 * Check if a given object implements the SaveDomainRequiredDataResponseContent interface.
 */
export function instanceOfSaveDomainRequiredDataResponseContent(value: object): value is SaveDomainRequiredDataResponseContent {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SaveDomainRequiredDataResponseContentFromJSON(json: any): SaveDomainRequiredDataResponseContent {
    return SaveDomainRequiredDataResponseContentFromJSONTyped(json, false);
}

export function SaveDomainRequiredDataResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveDomainRequiredDataResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': SaveDomainRequiredDataDataFromJSON(json['data']),
    };
}

export function SaveDomainRequiredDataResponseContentToJSON(json: any): SaveDomainRequiredDataResponseContent {
    return SaveDomainRequiredDataResponseContentToJSONTyped(json, false);
}

export function SaveDomainRequiredDataResponseContentToJSONTyped(value?: SaveDomainRequiredDataResponseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': SaveDomainRequiredDataDataToJSON(value['data']),
    };
}

