/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { BackupItem } from './BackupItem.js';
import {
    BackupItemFromJSON,
    BackupItemFromJSONTyped,
    BackupItemToJSON,
    BackupItemToJSONTyped,
} from './BackupItem.js';
import type { BackupMode } from './BackupMode.js';
import {
    BackupModeFromJSON,
    BackupModeFromJSONTyped,
    BackupModeToJSON,
    BackupModeToJSONTyped,
} from './BackupMode.js';
import type { BackupCreationInfo } from './BackupCreationInfo.js';
import {
    BackupCreationInfoFromJSON,
    BackupCreationInfoFromJSONTyped,
    BackupCreationInfoToJSON,
    BackupCreationInfoToJSONTyped,
} from './BackupCreationInfo.js';
import type { CompressionMethod } from './CompressionMethod.js';
import {
    CompressionMethodFromJSON,
    CompressionMethodFromJSONTyped,
    CompressionMethodToJSON,
    CompressionMethodToJSONTyped,
} from './CompressionMethod.js';

/**
 * Response data for service backups operation
 * @export
 * @interface ServiceBackupsResponseData
 */
export interface ServiceBackupsResponseData {
    /**
     * Status message indicating the result
     * @type {string}
     * @memberof ServiceBackupsResponseData
     */
    message: string;
    /**
     * List of backups for the service
     * @type {Array<BackupItem>}
     * @memberof ServiceBackupsResponseData
     */
    backups: Array<BackupItem>;
    /**
     * Total backup quota (null if unlimited)
     * @type {number}
     * @memberof ServiceBackupsResponseData
     */
    quotaTotal?: number;
    /**
     * Used backup quota
     * @type {number}
     * @memberof ServiceBackupsResponseData
     */
    quotaUsed: number;
    /**
     * Unit for quota measurements (e.g., GiB)
     * @type {string}
     * @memberof ServiceBackupsResponseData
     */
    quotaUnit: string;
    /**
     * Available compression methods for creating backups
     * @type {Array<CompressionMethod>}
     * @memberof ServiceBackupsResponseData
     */
    availableCompressMethods: Array<CompressionMethod>;
    /**
     * Available backup modes
     * @type {Array<BackupMode>}
     * @memberof ServiceBackupsResponseData
     */
    availableModes: Array<BackupMode>;
    /**
     * Whether a backup is currently being created
     * @type {boolean}
     * @memberof ServiceBackupsResponseData
     */
    backupIsCreating: boolean;
    /**
     * 
     * @type {BackupCreationInfo}
     * @memberof ServiceBackupsResponseData
     */
    backupCreation?: BackupCreationInfo;
}

/**
 * Check if a given object implements the ServiceBackupsResponseData interface.
 */
export function instanceOfServiceBackupsResponseData(value: object): value is ServiceBackupsResponseData {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('backups' in value) || value['backups'] === undefined) return false;
    if (!('quotaUsed' in value) || value['quotaUsed'] === undefined) return false;
    if (!('quotaUnit' in value) || value['quotaUnit'] === undefined) return false;
    if (!('availableCompressMethods' in value) || value['availableCompressMethods'] === undefined) return false;
    if (!('availableModes' in value) || value['availableModes'] === undefined) return false;
    if (!('backupIsCreating' in value) || value['backupIsCreating'] === undefined) return false;
    return true;
}

export function ServiceBackupsResponseDataFromJSON(json: any): ServiceBackupsResponseData {
    return ServiceBackupsResponseDataFromJSONTyped(json, false);
}

export function ServiceBackupsResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceBackupsResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'backups': ((json['backups'] as Array<any>).map(BackupItemFromJSON)),
        'quotaTotal': json['quota_total'] == null ? undefined : json['quota_total'],
        'quotaUsed': json['quota_used'],
        'quotaUnit': json['quota_unit'],
        'availableCompressMethods': ((json['available_compress_methods'] as Array<any>).map(CompressionMethodFromJSON)),
        'availableModes': ((json['available_modes'] as Array<any>).map(BackupModeFromJSON)),
        'backupIsCreating': json['backup_is_creating'],
        'backupCreation': json['backup_creation'] == null ? undefined : BackupCreationInfoFromJSON(json['backup_creation']),
    };
}

export function ServiceBackupsResponseDataToJSON(json: any): ServiceBackupsResponseData {
    return ServiceBackupsResponseDataToJSONTyped(json, false);
}

export function ServiceBackupsResponseDataToJSONTyped(value?: ServiceBackupsResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'backups': ((value['backups'] as Array<any>).map(BackupItemToJSON)),
        'quota_total': value['quotaTotal'],
        'quota_used': value['quotaUsed'],
        'quota_unit': value['quotaUnit'],
        'available_compress_methods': ((value['availableCompressMethods'] as Array<any>).map(CompressionMethodToJSON)),
        'available_modes': ((value['availableModes'] as Array<any>).map(BackupModeToJSON)),
        'backup_is_creating': value['backupIsCreating'],
        'backup_creation': BackupCreationInfoToJSON(value['backupCreation']),
    };
}

