/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShutdownVpsInput
 */
export interface ShutdownVpsInput {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof ShutdownVpsInput
     */
    serviceId: string;
}

/**
 * Check if a given object implements the ShutdownVpsInput interface.
 */
export function instanceOfShutdownVpsInput(value: object): value is ShutdownVpsInput {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    return true;
}

export function ShutdownVpsInputFromJSON(json: any): ShutdownVpsInput {
    return ShutdownVpsInputFromJSONTyped(json, false);
}

export function ShutdownVpsInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShutdownVpsInput {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
    };
}

export function ShutdownVpsInputToJSON(json: any): ShutdownVpsInput {
    return ShutdownVpsInputToJSONTyped(json, false);
}

export function ShutdownVpsInputToJSONTyped(value?: ShutdownVpsInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
    };
}

