/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { VpsSimpleActionResponseData } from './VpsSimpleActionResponseData.js';
import {
    VpsSimpleActionResponseDataFromJSON,
    VpsSimpleActionResponseDataFromJSONTyped,
    VpsSimpleActionResponseDataToJSON,
    VpsSimpleActionResponseDataToJSONTyped,
} from './VpsSimpleActionResponseData.js';
import type { OperationStatus } from './OperationStatus.js';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus.js';

/**
 * 
 * @export
 * @interface ShutdownVpsResponseContent
 */
export interface ShutdownVpsResponseContent {
    /**
     * 
     * @type {OperationStatus}
     * @memberof ShutdownVpsResponseContent
     */
    status: OperationStatus;
    /**
     * 
     * @type {VpsSimpleActionResponseData}
     * @memberof ShutdownVpsResponseContent
     */
    data: VpsSimpleActionResponseData;
}



/**
 * Check if a given object implements the ShutdownVpsResponseContent interface.
 */
export function instanceOfShutdownVpsResponseContent(value: object): value is ShutdownVpsResponseContent {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ShutdownVpsResponseContentFromJSON(json: any): ShutdownVpsResponseContent {
    return ShutdownVpsResponseContentFromJSONTyped(json, false);
}

export function ShutdownVpsResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShutdownVpsResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': VpsSimpleActionResponseDataFromJSON(json['data']),
    };
}

export function ShutdownVpsResponseContentToJSON(json: any): ShutdownVpsResponseContent {
    return ShutdownVpsResponseContentToJSONTyped(json, false);
}

export function ShutdownVpsResponseContentToJSONTyped(value?: ShutdownVpsResponseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': VpsSimpleActionResponseDataToJSON(value['data']),
    };
}

