/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShutdownVpsRequestContent
 */
export interface ShutdownVpsRequestContent {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof ShutdownVpsRequestContent
     */
    serviceId: string;
}

/**
 * Check if a given object implements the ShutdownVpsRequestContent interface.
 */
export function instanceOfShutdownVpsRequestContent(value: object): value is ShutdownVpsRequestContent {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    return true;
}

export function ShutdownVpsRequestContentFromJSON(json: any): ShutdownVpsRequestContent {
    return ShutdownVpsRequestContentFromJSONTyped(json, false);
}

export function ShutdownVpsRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShutdownVpsRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
    };
}

export function ShutdownVpsRequestContentToJSON(json: any): ShutdownVpsRequestContent {
    return ShutdownVpsRequestContentToJSONTyped(json, false);
}

export function ShutdownVpsRequestContentToJSONTyped(value?: ShutdownVpsRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
    };
}

