/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * SSH key details
 * @export
 * @interface SshKeyDetails
 */
export interface SshKeyDetails {
    /**
     * The public SSH key in OpenSSH format
     * @type {string}
     * @memberof SshKeyDetails
     */
    publicKey: string;
    /**
     * Type of SSH key configuration - 'sshkeys' for KVM cloud-init or 'keypair' for traditional SSH (LXC)
     * @type {string}
     * @memberof SshKeyDetails
     */
    type: string;
}

/**
 * Check if a given object implements the SshKeyDetails interface.
 */
export function instanceOfSshKeyDetails(value: object): value is SshKeyDetails {
    if (!('publicKey' in value) || value['publicKey'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function SshKeyDetailsFromJSON(json: any): SshKeyDetails {
    return SshKeyDetailsFromJSONTyped(json, false);
}

export function SshKeyDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SshKeyDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'publicKey': json['public_key'],
        'type': json['type'],
    };
}

export function SshKeyDetailsToJSON(json: any): SshKeyDetails {
    return SshKeyDetailsToJSONTyped(json, false);
}

export function SshKeyDetailsToJSONTyped(value?: SshKeyDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'public_key': value['publicKey'],
        'type': value['type'],
    };
}

