/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface StartVpsRequestContent
 */
export interface StartVpsRequestContent {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof StartVpsRequestContent
     */
    serviceId: string;
}

/**
 * Check if a given object implements the StartVpsRequestContent interface.
 */
export function instanceOfStartVpsRequestContent(value: object): value is StartVpsRequestContent {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    return true;
}

export function StartVpsRequestContentFromJSON(json: any): StartVpsRequestContent {
    return StartVpsRequestContentFromJSONTyped(json, false);
}

export function StartVpsRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartVpsRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
    };
}

export function StartVpsRequestContentToJSON(json: any): StartVpsRequestContent {
    return StartVpsRequestContentToJSONTyped(json, false);
}

export function StartVpsRequestContentToJSONTyped(value?: StartVpsRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
    };
}

