/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartVpsInput
 */
export interface StartVpsInput {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof StartVpsInput
     */
    serviceId: string;
}

/**
 * Check if a given object implements the StartVpsInput interface.
 */
export function instanceOfStartVpsInput(value: object): value is StartVpsInput {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    return true;
}

export function StartVpsInputFromJSON(json: any): StartVpsInput {
    return StartVpsInputFromJSONTyped(json, false);
}

export function StartVpsInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartVpsInput {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
    };
}

export function StartVpsInputToJSON(json: any): StartVpsInput {
    return StartVpsInputToJSONTyped(json, false);
}

export function StartVpsInputToJSONTyped(value?: StartVpsInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
    };
}

