/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { VpsSimpleActionResponseData } from './VpsSimpleActionResponseData.js';
import {
    VpsSimpleActionResponseDataFromJSON,
    VpsSimpleActionResponseDataFromJSONTyped,
    VpsSimpleActionResponseDataToJSON,
    VpsSimpleActionResponseDataToJSONTyped,
} from './VpsSimpleActionResponseData.js';
import type { OperationStatus } from './OperationStatus.js';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus.js';

/**
 * 
 * @export
 * @interface StopVpsResponseContent
 */
export interface StopVpsResponseContent {
    /**
     * 
     * @type {OperationStatus}
     * @memberof StopVpsResponseContent
     */
    status: OperationStatus;
    /**
     * 
     * @type {VpsSimpleActionResponseData}
     * @memberof StopVpsResponseContent
     */
    data: VpsSimpleActionResponseData;
}



/**
 * Check if a given object implements the StopVpsResponseContent interface.
 */
export function instanceOfStopVpsResponseContent(value: object): value is StopVpsResponseContent {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function StopVpsResponseContentFromJSON(json: any): StopVpsResponseContent {
    return StopVpsResponseContentFromJSONTyped(json, false);
}

export function StopVpsResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): StopVpsResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': VpsSimpleActionResponseDataFromJSON(json['data']),
    };
}

export function StopVpsResponseContentToJSON(json: any): StopVpsResponseContent {
    return StopVpsResponseContentToJSONTyped(json, false);
}

export function StopVpsResponseContentToJSONTyped(value?: StopVpsResponseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': VpsSimpleActionResponseDataToJSON(value['data']),
    };
}

