/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StopVpsRequestContent
 */
export interface StopVpsRequestContent {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof StopVpsRequestContent
     */
    serviceId: string;
}

/**
 * Check if a given object implements the StopVpsRequestContent interface.
 */
export function instanceOfStopVpsRequestContent(value: object): value is StopVpsRequestContent {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    return true;
}

export function StopVpsRequestContentFromJSON(json: any): StopVpsRequestContent {
    return StopVpsRequestContentFromJSONTyped(json, false);
}

export function StopVpsRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): StopVpsRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
    };
}

export function StopVpsRequestContentToJSON(json: any): StopVpsRequestContent {
    return StopVpsRequestContentToJSONTyped(json, false);
}

export function StopVpsRequestContentToJSONTyped(value?: StopVpsRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
    };
}

