/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SuggestDomainsRequestContent
 */
export interface SuggestDomainsRequestContent {
    /**
     * Natural-language description of the business or idea, e.g. "my coffee shop"
     * @type {string}
     * @memberof SuggestDomainsRequestContent
     */
    prompt: string;
    /**
     * Currency for pricing. Accepts ISO code, symbol, country name, or numeric ID. Defaults to ZAR.
     * @type {string}
     * @memberof SuggestDomainsRequestContent
     */
    currency?: string;
}

/**
 * Check if a given object implements the SuggestDomainsRequestContent interface.
 */
export function instanceOfSuggestDomainsRequestContent(value: object): value is SuggestDomainsRequestContent {
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function SuggestDomainsRequestContentFromJSON(json: any): SuggestDomainsRequestContent {
    return SuggestDomainsRequestContentFromJSONTyped(json, false);
}

export function SuggestDomainsRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuggestDomainsRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'],
        'currency': json['currency'] == null ? undefined : json['currency'],
    };
}

export function SuggestDomainsRequestContentToJSON(json: any): SuggestDomainsRequestContent {
    return SuggestDomainsRequestContentToJSONTyped(json, false);
}

export function SuggestDomainsRequestContentToJSONTyped(value?: SuggestDomainsRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
        'currency': value['currency'],
    };
}

