/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VpsSimpleActionResponseData } from './VpsSimpleActionResponseData';
import {
    VpsSimpleActionResponseDataFromJSON,
    VpsSimpleActionResponseDataFromJSONTyped,
    VpsSimpleActionResponseDataToJSON,
    VpsSimpleActionResponseDataToJSONTyped,
} from './VpsSimpleActionResponseData';
import type { OperationStatus } from './OperationStatus';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus';

/**
 * 
 * @export
 * @interface UnsuspendVpsResponseContent
 */
export interface UnsuspendVpsResponseContent {
    /**
     * 
     * @type {OperationStatus}
     * @memberof UnsuspendVpsResponseContent
     */
    status: OperationStatus;
    /**
     * 
     * @type {VpsSimpleActionResponseData}
     * @memberof UnsuspendVpsResponseContent
     */
    data: VpsSimpleActionResponseData;
}



/**
 * Check if a given object implements the UnsuspendVpsResponseContent interface.
 */
export function instanceOfUnsuspendVpsResponseContent(value: object): value is UnsuspendVpsResponseContent {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function UnsuspendVpsResponseContentFromJSON(json: any): UnsuspendVpsResponseContent {
    return UnsuspendVpsResponseContentFromJSONTyped(json, false);
}

export function UnsuspendVpsResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnsuspendVpsResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': VpsSimpleActionResponseDataFromJSON(json['data']),
    };
}

export function UnsuspendVpsResponseContentToJSON(json: any): UnsuspendVpsResponseContent {
    return UnsuspendVpsResponseContentToJSONTyped(json, false);
}

export function UnsuspendVpsResponseContentToJSONTyped(value?: UnsuspendVpsResponseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': VpsSimpleActionResponseDataToJSON(value['data']),
    };
}

