/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSnapshotRequestContent
 */
export interface UpdateSnapshotRequestContent {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof UpdateSnapshotRequestContent
     */
    serviceId: string;
    /**
     * Snapshot name to update
     * @type {string}
     * @memberof UpdateSnapshotRequestContent
     */
    snapshotName: string;
    /**
     * New description for the snapshot
     * @type {string}
     * @memberof UpdateSnapshotRequestContent
     */
    description?: string;
}

/**
 * Check if a given object implements the UpdateSnapshotRequestContent interface.
 */
export function instanceOfUpdateSnapshotRequestContent(value: object): value is UpdateSnapshotRequestContent {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('snapshotName' in value) || value['snapshotName'] === undefined) return false;
    return true;
}

export function UpdateSnapshotRequestContentFromJSON(json: any): UpdateSnapshotRequestContent {
    return UpdateSnapshotRequestContentFromJSONTyped(json, false);
}

export function UpdateSnapshotRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSnapshotRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
        'snapshotName': json['snapshot_name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function UpdateSnapshotRequestContentToJSON(json: any): UpdateSnapshotRequestContent {
    return UpdateSnapshotRequestContentToJSONTyped(json, false);
}

export function UpdateSnapshotRequestContentToJSONTyped(value?: UpdateSnapshotRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
        'snapshot_name': value['snapshotName'],
        'description': value['description'],
    };
}

