/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { UpdateDomainContactsData } from './UpdateDomainContactsData.js';
import {
    UpdateDomainContactsDataFromJSON,
    UpdateDomainContactsDataFromJSONTyped,
    UpdateDomainContactsDataToJSON,
    UpdateDomainContactsDataToJSONTyped,
} from './UpdateDomainContactsData.js';
import type { OperationStatus } from './OperationStatus.js';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus.js';

/**
 * 
 * @export
 * @interface UpdateDomainContactsResponseContent
 */
export interface UpdateDomainContactsResponseContent {
    /**
     * 
     * @type {OperationStatus}
     * @memberof UpdateDomainContactsResponseContent
     */
    status: OperationStatus;
    /**
     * 
     * @type {UpdateDomainContactsData}
     * @memberof UpdateDomainContactsResponseContent
     */
    data: UpdateDomainContactsData;
}



/**
 * Check if a given object implements the UpdateDomainContactsResponseContent interface.
 */
export function instanceOfUpdateDomainContactsResponseContent(value: object): value is UpdateDomainContactsResponseContent {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function UpdateDomainContactsResponseContentFromJSON(json: any): UpdateDomainContactsResponseContent {
    return UpdateDomainContactsResponseContentFromJSONTyped(json, false);
}

export function UpdateDomainContactsResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDomainContactsResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': UpdateDomainContactsDataFromJSON(json['data']),
    };
}

export function UpdateDomainContactsResponseContentToJSON(json: any): UpdateDomainContactsResponseContent {
    return UpdateDomainContactsResponseContentToJSONTyped(json, false);
}

export function UpdateDomainContactsResponseContentToJSONTyped(value?: UpdateDomainContactsResponseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': UpdateDomainContactsDataToJSON(value['data']),
    };
}

