/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationStatus } from './NotificationStatus';
import {
    NotificationStatusFromJSON,
    NotificationStatusFromJSONTyped,
    NotificationStatusToJSON,
    NotificationStatusToJSONTyped,
} from './NotificationStatus';

/**
 * 
 * @export
 * @interface UpdateNotificationRequestContent
 */
export interface UpdateNotificationRequestContent {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof UpdateNotificationRequestContent
     */
    serviceId: string;
    /**
     * Notification ID to update
     * @type {number}
     * @memberof UpdateNotificationRequestContent
     */
    notificationId: number;
    /**
     * Name/title for the notification
     * @type {string}
     * @memberof UpdateNotificationRequestContent
     */
    name?: string;
    /**
     * 
     * @type {NotificationStatus}
     * @memberof UpdateNotificationRequestContent
     */
    status?: NotificationStatus;
    /**
     * Notification interval in minutes (must be > 0)
     * @type {number}
     * @memberof UpdateNotificationRequestContent
     */
    notificationInterval?: number;
    /**
     * Data timeframe in minutes (must be > 0)
     * @type {number}
     * @memberof UpdateNotificationRequestContent
     */
    dataTimeframe?: number;
    /**
     * Whether all thresholds must be exceeded (true) or any one (false)
     * @type {boolean}
     * @memberof UpdateNotificationRequestContent
     */
    exceedAll?: boolean;
    /**
     * Email addresses for notifications (comma-separated string or array)
     * @type {Array<string>}
     * @memberof UpdateNotificationRequestContent
     */
    emailAddress?: Array<string>;
    /**
     * CPU usage threshold percentage (0-100)
     * @type {number}
     * @memberof UpdateNotificationRequestContent
     */
    cpuUsage?: number;
    /**
     * Memory usage threshold percentage (0-100)
     * @type {number}
     * @memberof UpdateNotificationRequestContent
     */
    memoryUsage?: number;
    /**
     * Network traffic threshold percentage (0-100)
     * @type {number}
     * @memberof UpdateNotificationRequestContent
     */
    networkTraffic?: number;
    /**
     * Disk read threshold percentage (0-100)
     * @type {number}
     * @memberof UpdateNotificationRequestContent
     */
    diskRead?: number;
    /**
     * Disk write threshold percentage (0-100)
     * @type {number}
     * @memberof UpdateNotificationRequestContent
     */
    diskWrite?: number;
}



/**
 * Check if a given object implements the UpdateNotificationRequestContent interface.
 */
export function instanceOfUpdateNotificationRequestContent(value: object): value is UpdateNotificationRequestContent {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('notificationId' in value) || value['notificationId'] === undefined) return false;
    return true;
}

export function UpdateNotificationRequestContentFromJSON(json: any): UpdateNotificationRequestContent {
    return UpdateNotificationRequestContentFromJSONTyped(json, false);
}

export function UpdateNotificationRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateNotificationRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
        'notificationId': json['notification_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'status': json['status'] == null ? undefined : NotificationStatusFromJSON(json['status']),
        'notificationInterval': json['notification_interval'] == null ? undefined : json['notification_interval'],
        'dataTimeframe': json['data_timeframe'] == null ? undefined : json['data_timeframe'],
        'exceedAll': json['exceed_all'] == null ? undefined : json['exceed_all'],
        'emailAddress': json['email_address'] == null ? undefined : json['email_address'],
        'cpuUsage': json['cpu_usage'] == null ? undefined : json['cpu_usage'],
        'memoryUsage': json['memory_usage'] == null ? undefined : json['memory_usage'],
        'networkTraffic': json['network_traffic'] == null ? undefined : json['network_traffic'],
        'diskRead': json['disk_read'] == null ? undefined : json['disk_read'],
        'diskWrite': json['disk_write'] == null ? undefined : json['disk_write'],
    };
}

export function UpdateNotificationRequestContentToJSON(json: any): UpdateNotificationRequestContent {
    return UpdateNotificationRequestContentToJSONTyped(json, false);
}

export function UpdateNotificationRequestContentToJSONTyped(value?: UpdateNotificationRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
        'notification_id': value['notificationId'],
        'name': value['name'],
        'status': NotificationStatusToJSON(value['status']),
        'notification_interval': value['notificationInterval'],
        'data_timeframe': value['dataTimeframe'],
        'exceed_all': value['exceedAll'],
        'email_address': value['emailAddress'],
        'cpu_usage': value['cpuUsage'],
        'memory_usage': value['memoryUsage'],
        'network_traffic': value['networkTraffic'],
        'disk_read': value['diskRead'],
        'disk_write': value['diskWrite'],
    };
}

