/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { OperationStatus } from './OperationStatus.js';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus.js';
import type { NotificationCreateResponseData } from './NotificationCreateResponseData.js';
import {
    NotificationCreateResponseDataFromJSON,
    NotificationCreateResponseDataFromJSONTyped,
    NotificationCreateResponseDataToJSON,
    NotificationCreateResponseDataToJSONTyped,
} from './NotificationCreateResponseData.js';

/**
 * 
 * @export
 * @interface UpdateNotificationResponseContent
 */
export interface UpdateNotificationResponseContent {
    /**
     * 
     * @type {OperationStatus}
     * @memberof UpdateNotificationResponseContent
     */
    status: OperationStatus;
    /**
     * 
     * @type {NotificationCreateResponseData}
     * @memberof UpdateNotificationResponseContent
     */
    data: NotificationCreateResponseData;
}



/**
 * Check if a given object implements the UpdateNotificationResponseContent interface.
 */
export function instanceOfUpdateNotificationResponseContent(value: object): value is UpdateNotificationResponseContent {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function UpdateNotificationResponseContentFromJSON(json: any): UpdateNotificationResponseContent {
    return UpdateNotificationResponseContentFromJSONTyped(json, false);
}

export function UpdateNotificationResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateNotificationResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': NotificationCreateResponseDataFromJSON(json['data']),
    };
}

export function UpdateNotificationResponseContentToJSON(json: any): UpdateNotificationResponseContent {
    return UpdateNotificationResponseContentToJSONTyped(json, false);
}

export function UpdateNotificationResponseContentToJSONTyped(value?: UpdateNotificationResponseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': NotificationCreateResponseDataToJSON(value['data']),
    };
}

