/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { DayOfWeek } from './DayOfWeek.js';
import {
    DayOfWeekFromJSON,
    DayOfWeekFromJSONTyped,
    DayOfWeekToJSON,
    DayOfWeekToJSONTyped,
} from './DayOfWeek.js';
import type { SnapshotJobPeriod } from './SnapshotJobPeriod.js';
import {
    SnapshotJobPeriodFromJSON,
    SnapshotJobPeriodFromJSONTyped,
    SnapshotJobPeriodToJSON,
    SnapshotJobPeriodToJSONTyped,
} from './SnapshotJobPeriod.js';

/**
 * 
 * @export
 * @interface UpdateSnapshotJobRequestContent
 */
export interface UpdateSnapshotJobRequestContent {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof UpdateSnapshotJobRequestContent
     */
    serviceId: string;
    /**
     * Snapshot job ID to update
     * @type {string}
     * @memberof UpdateSnapshotJobRequestContent
     */
    jobId: string;
    /**
     * New name for the snapshot job
     * @type {string}
     * @memberof UpdateSnapshotJobRequestContent
     */
    name?: string;
    /**
     * New description for the snapshot job
     * @type {string}
     * @memberof UpdateSnapshotJobRequestContent
     */
    description?: string;
    /**
     * Whether to include VM state in the snapshot
     * @type {boolean}
     * @memberof UpdateSnapshotJobRequestContent
     */
    vmstate?: boolean;
    /**
     * 
     * @type {SnapshotJobPeriod}
     * @memberof UpdateSnapshotJobRequestContent
     */
    period?: SnapshotJobPeriod;
    /**
     * For hourly jobs: run every N hours (e.g. 6 = every 6 hours)
     * @type {number}
     * @memberof UpdateSnapshotJobRequestContent
     */
    runEvery?: number;
    /**
     * For daily jobs: days of week when the job should run
     * @type {Array<DayOfWeek>}
     * @memberof UpdateSnapshotJobRequestContent
     */
    days?: Array<DayOfWeek>;
    /**
     * For daily jobs: start time in HH:MM format (e.g. '02:30')
     * @type {string}
     * @memberof UpdateSnapshotJobRequestContent
     */
    startTime?: string;
}



/**
 * Check if a given object implements the UpdateSnapshotJobRequestContent interface.
 */
export function instanceOfUpdateSnapshotJobRequestContent(value: object): value is UpdateSnapshotJobRequestContent {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    return true;
}

export function UpdateSnapshotJobRequestContentFromJSON(json: any): UpdateSnapshotJobRequestContent {
    return UpdateSnapshotJobRequestContentFromJSONTyped(json, false);
}

export function UpdateSnapshotJobRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSnapshotJobRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
        'jobId': json['job_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'vmstate': json['vmstate'] == null ? undefined : json['vmstate'],
        'period': json['period'] == null ? undefined : SnapshotJobPeriodFromJSON(json['period']),
        'runEvery': json['run_every'] == null ? undefined : json['run_every'],
        'days': json['days'] == null ? undefined : ((json['days'] as Array<any>).map(DayOfWeekFromJSON)),
        'startTime': json['start_time'] == null ? undefined : json['start_time'],
    };
}

export function UpdateSnapshotJobRequestContentToJSON(json: any): UpdateSnapshotJobRequestContent {
    return UpdateSnapshotJobRequestContentToJSONTyped(json, false);
}

export function UpdateSnapshotJobRequestContentToJSONTyped(value?: UpdateSnapshotJobRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
        'job_id': value['jobId'],
        'name': value['name'],
        'description': value['description'],
        'vmstate': value['vmstate'],
        'period': SnapshotJobPeriodToJSON(value['period']),
        'run_every': value['runEvery'],
        'days': value['days'] == null ? undefined : ((value['days'] as Array<any>).map(DayOfWeekToJSON)),
        'start_time': value['startTime'],
    };
}

