/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePowerTaskInput
 */
export interface UpdatePowerTaskInput {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof UpdatePowerTaskInput
     */
    serviceId: string;
    /**
     * Power task ID to update
     * @type {number}
     * @memberof UpdatePowerTaskInput
     */
    taskId: number;
    /**
     * Power action to perform (start, stop, restart)
     * @type {string}
     * @memberof UpdatePowerTaskInput
     */
    powerTaskAction?: string;
    /**
     * Start date in Y-m-d format (e.g., 2026-03-25)
     * @type {string}
     * @memberof UpdatePowerTaskInput
     */
    startDate?: string;
    /**
     * Description of the power task
     * @type {string}
     * @memberof UpdatePowerTaskInput
     */
    description?: string;
    /**
     * Start time in HH:MM or HH:MM:SS format
     * @type {string}
     * @memberof UpdatePowerTaskInput
     */
    startTime?: string;
    /**
     * End date in Y-m-d format (e.g., 2026-12-31)
     * @type {string}
     * @memberof UpdatePowerTaskInput
     */
    endDate?: string;
    /**
     * End time in HH:MM or HH:MM:SS format
     * @type {string}
     * @memberof UpdatePowerTaskInput
     */
    endTime?: string;
    /**
     * Job type: oneTime, daily, or weekly
     * @type {string}
     * @memberof UpdatePowerTaskInput
     */
    jobType?: string;
    /**
     * Job execution time in HH:MM or HH:MM:SS format
     * @type {string}
     * @memberof UpdatePowerTaskInput
     */
    jobTime?: string;
    /**
     * Job hour (alternative to job_time)
     * @type {number}
     * @memberof UpdatePowerTaskInput
     */
    jobHour?: number;
    /**
     * Job minutes (alternative to job_time)
     * @type {number}
     * @memberof UpdatePowerTaskInput
     */
    jobMinutes?: number;
    /**
     * Days of the week for weekly jobs (array of mon, tue, wed, thu, fri, sat, sun)
     * @type {Array<string>}
     * @memberof UpdatePowerTaskInput
     */
    days?: Array<string>;
}

/**
 * Check if a given object implements the UpdatePowerTaskInput interface.
 */
export function instanceOfUpdatePowerTaskInput(value: object): value is UpdatePowerTaskInput {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('taskId' in value) || value['taskId'] === undefined) return false;
    return true;
}

export function UpdatePowerTaskInputFromJSON(json: any): UpdatePowerTaskInput {
    return UpdatePowerTaskInputFromJSONTyped(json, false);
}

export function UpdatePowerTaskInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePowerTaskInput {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
        'taskId': json['task_id'],
        'powerTaskAction': json['power_task_action'] == null ? undefined : json['power_task_action'],
        'startDate': json['start_date'] == null ? undefined : json['start_date'],
        'description': json['description'] == null ? undefined : json['description'],
        'startTime': json['start_time'] == null ? undefined : json['start_time'],
        'endDate': json['end_date'] == null ? undefined : json['end_date'],
        'endTime': json['end_time'] == null ? undefined : json['end_time'],
        'jobType': json['job_type'] == null ? undefined : json['job_type'],
        'jobTime': json['job_time'] == null ? undefined : json['job_time'],
        'jobHour': json['job_hour'] == null ? undefined : json['job_hour'],
        'jobMinutes': json['job_minutes'] == null ? undefined : json['job_minutes'],
        'days': json['days'] == null ? undefined : json['days'],
    };
}

export function UpdatePowerTaskInputToJSON(json: any): UpdatePowerTaskInput {
    return UpdatePowerTaskInputToJSONTyped(json, false);
}

export function UpdatePowerTaskInputToJSONTyped(value?: UpdatePowerTaskInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
        'task_id': value['taskId'],
        'power_task_action': value['powerTaskAction'],
        'start_date': value['startDate'],
        'description': value['description'],
        'start_time': value['startTime'],
        'end_date': value['endDate'],
        'end_time': value['endTime'],
        'job_type': value['jobType'],
        'job_time': value['jobTime'],
        'job_hour': value['jobHour'],
        'job_minutes': value['jobMinutes'],
        'days': value['days'],
    };
}

