/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { DomainSettingKey } from './DomainSettingKey.js';
import {
    DomainSettingKeyFromJSON,
    DomainSettingKeyFromJSONTyped,
    DomainSettingKeyToJSON,
    DomainSettingKeyToJSONTyped,
} from './DomainSettingKey.js';

/**
 * 
 * @export
 * @interface UpdateDomainSettingsRequestContent
 */
export interface UpdateDomainSettingsRequestContent {
    /**
     * Domain service id - must be sent as a string
     * @type {string}
     * @memberof UpdateDomainSettingsRequestContent
     */
    domainId: string;
    /**
     * 
     * @type {DomainSettingKey}
     * @memberof UpdateDomainSettingsRequestContent
     */
    setting: DomainSettingKey;
    /**
     * New boolean value
     * @type {boolean}
     * @memberof UpdateDomainSettingsRequestContent
     */
    value: boolean;
    /**
     * Payment gateway slug when enabling a paid addon (e.g. stripe)
     * @type {string}
     * @memberof UpdateDomainSettingsRequestContent
     */
    gateway?: string;
}



/**
 * Check if a given object implements the UpdateDomainSettingsRequestContent interface.
 */
export function instanceOfUpdateDomainSettingsRequestContent(value: object): value is UpdateDomainSettingsRequestContent {
    if (!('domainId' in value) || value['domainId'] === undefined) return false;
    if (!('setting' in value) || value['setting'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function UpdateDomainSettingsRequestContentFromJSON(json: any): UpdateDomainSettingsRequestContent {
    return UpdateDomainSettingsRequestContentFromJSONTyped(json, false);
}

export function UpdateDomainSettingsRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDomainSettingsRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'domainId': json['domain_id'],
        'setting': DomainSettingKeyFromJSON(json['setting']),
        'value': json['value'],
        'gateway': json['gateway'] == null ? undefined : json['gateway'],
    };
}

export function UpdateDomainSettingsRequestContentToJSON(json: any): UpdateDomainSettingsRequestContent {
    return UpdateDomainSettingsRequestContentToJSONTyped(json, false);
}

export function UpdateDomainSettingsRequestContentToJSONTyped(value?: UpdateDomainSettingsRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domain_id': value['domainId'],
        'setting': DomainSettingKeyToJSON(value['setting']),
        'value': value['value'],
        'gateway': value['gateway'],
    };
}

