/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { DomainContactUpdates } from './DomainContactUpdates.js';
import {
    DomainContactUpdatesFromJSON,
    DomainContactUpdatesFromJSONTyped,
    DomainContactUpdatesToJSON,
    DomainContactUpdatesToJSONTyped,
} from './DomainContactUpdates.js';

/**
 * 
 * @export
 * @interface UpdateDomainContactsRequestContent
 */
export interface UpdateDomainContactsRequestContent {
    /**
     * Domain service id - must be sent as a string
     * @type {string}
     * @memberof UpdateDomainContactsRequestContent
     */
    domainId: string;
    /**
     * 
     * @type {DomainContactUpdates}
     * @memberof UpdateDomainContactsRequestContent
     */
    contacts: DomainContactUpdates;
}

/**
 * Check if a given object implements the UpdateDomainContactsRequestContent interface.
 */
export function instanceOfUpdateDomainContactsRequestContent(value: object): value is UpdateDomainContactsRequestContent {
    if (!('domainId' in value) || value['domainId'] === undefined) return false;
    if (!('contacts' in value) || value['contacts'] === undefined) return false;
    return true;
}

export function UpdateDomainContactsRequestContentFromJSON(json: any): UpdateDomainContactsRequestContent {
    return UpdateDomainContactsRequestContentFromJSONTyped(json, false);
}

export function UpdateDomainContactsRequestContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDomainContactsRequestContent {
    if (json == null) {
        return json;
    }
    return {
        
        'domainId': json['domain_id'],
        'contacts': DomainContactUpdatesFromJSON(json['contacts']),
    };
}

export function UpdateDomainContactsRequestContentToJSON(json: any): UpdateDomainContactsRequestContent {
    return UpdateDomainContactsRequestContentToJSONTyped(json, false);
}

export function UpdateDomainContactsRequestContentToJSONTyped(value?: UpdateDomainContactsRequestContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domain_id': value['domainId'],
        'contacts': DomainContactUpdatesToJSON(value['contacts']),
    };
}

