/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSshKeysInput
 */
export interface UpdateSshKeysInput {
    /**
     * Service ID - must be sent as a string
     * @type {string}
     * @memberof UpdateSshKeysInput
     */
    serviceId: string;
    /**
     * SSH public key in OpenSSH format (must start with ssh-rsa, ssh-dss, ssh-ed25519, or ssh-ecdsa)
     * @type {string}
     * @memberof UpdateSshKeysInput
     */
    sshKeys: string;
}

/**
 * Check if a given object implements the UpdateSshKeysInput interface.
 */
export function instanceOfUpdateSshKeysInput(value: object): value is UpdateSshKeysInput {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('sshKeys' in value) || value['sshKeys'] === undefined) return false;
    return true;
}

export function UpdateSshKeysInputFromJSON(json: any): UpdateSshKeysInput {
    return UpdateSshKeysInputFromJSONTyped(json, false);
}

export function UpdateSshKeysInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSshKeysInput {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['service_id'],
        'sshKeys': json['sshKeys'],
    };
}

export function UpdateSshKeysInputToJSON(json: any): UpdateSshKeysInput {
    return UpdateSshKeysInputToJSONTyped(json, false);
}

export function UpdateSshKeysInputToJSONTyped(value?: UpdateSshKeysInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service_id': value['serviceId'],
        'sshKeys': value['sshKeys'],
    };
}

