/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserChangePasswordResponseData } from './UserChangePasswordResponseData';
import {
    UserChangePasswordResponseDataFromJSON,
    UserChangePasswordResponseDataFromJSONTyped,
    UserChangePasswordResponseDataToJSON,
    UserChangePasswordResponseDataToJSONTyped,
} from './UserChangePasswordResponseData';
import type { OperationStatus } from './OperationStatus';
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from './OperationStatus';

/**
 * 
 * @export
 * @interface UserChangePasswordResponseContent
 */
export interface UserChangePasswordResponseContent {
    /**
     * 
     * @type {OperationStatus}
     * @memberof UserChangePasswordResponseContent
     */
    status: OperationStatus;
    /**
     * 
     * @type {UserChangePasswordResponseData}
     * @memberof UserChangePasswordResponseContent
     */
    data: UserChangePasswordResponseData;
}



/**
 * Check if a given object implements the UserChangePasswordResponseContent interface.
 */
export function instanceOfUserChangePasswordResponseContent(value: object): value is UserChangePasswordResponseContent {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function UserChangePasswordResponseContentFromJSON(json: any): UserChangePasswordResponseContent {
    return UserChangePasswordResponseContentFromJSONTyped(json, false);
}

export function UserChangePasswordResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserChangePasswordResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'status': OperationStatusFromJSON(json['status']),
        'data': UserChangePasswordResponseDataFromJSON(json['data']),
    };
}

export function UserChangePasswordResponseContentToJSON(json: any): UserChangePasswordResponseContent {
    return UserChangePasswordResponseContentToJSONTyped(json, false);
}

export function UserChangePasswordResponseContentToJSONTyped(value?: UserChangePasswordResponseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': OperationStatusToJSON(value['status']),
        'data': UserChangePasswordResponseDataToJSON(value['data']),
    };
}

