/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Recurring totals in the order summary
 * @export
 * @interface ValidatePricingSummaryRecurring
 */
export interface ValidatePricingSummaryRecurring {
    /**
     * 
     * @type {string}
     * @memberof ValidatePricingSummaryRecurring
     */
    beforeDiscount: string;
    /**
     * 
     * @type {string}
     * @memberof ValidatePricingSummaryRecurring
     */
    discount: string;
    /**
     * 
     * @type {string}
     * @memberof ValidatePricingSummaryRecurring
     */
    afterDiscount: string;
}

/**
 * Check if a given object implements the ValidatePricingSummaryRecurring interface.
 */
export function instanceOfValidatePricingSummaryRecurring(value: object): value is ValidatePricingSummaryRecurring {
    if (!('beforeDiscount' in value) || value['beforeDiscount'] === undefined) return false;
    if (!('discount' in value) || value['discount'] === undefined) return false;
    if (!('afterDiscount' in value) || value['afterDiscount'] === undefined) return false;
    return true;
}

export function ValidatePricingSummaryRecurringFromJSON(json: any): ValidatePricingSummaryRecurring {
    return ValidatePricingSummaryRecurringFromJSONTyped(json, false);
}

export function ValidatePricingSummaryRecurringFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidatePricingSummaryRecurring {
    if (json == null) {
        return json;
    }
    return {
        
        'beforeDiscount': json['before_discount'],
        'discount': json['discount'],
        'afterDiscount': json['after_discount'],
    };
}

export function ValidatePricingSummaryRecurringToJSON(json: any): ValidatePricingSummaryRecurring {
    return ValidatePricingSummaryRecurringToJSONTyped(json, false);
}

export function ValidatePricingSummaryRecurringToJSONTyped(value?: ValidatePricingSummaryRecurring | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'before_discount': value['beforeDiscount'],
        'discount': value['discount'],
        'after_discount': value['afterDiscount'],
    };
}

