/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidatePricingBase } from './ValidatePricingBase';
import {
    ValidatePricingBaseFromJSON,
    ValidatePricingBaseFromJSONTyped,
    ValidatePricingBaseToJSON,
    ValidatePricingBaseToJSONTyped,
} from './ValidatePricingBase';
import type { ValidatePricingConfigItem } from './ValidatePricingConfigItem';
import {
    ValidatePricingConfigItemFromJSON,
    ValidatePricingConfigItemFromJSONTyped,
    ValidatePricingConfigItemToJSON,
    ValidatePricingConfigItemToJSONTyped,
} from './ValidatePricingConfigItem';

/**
 * Full breakdown of a product's pricing
 * @export
 * @interface ValidatePricingBreakdown
 */
export interface ValidatePricingBreakdown {
    /**
     * 
     * @type {ValidatePricingBase}
     * @memberof ValidatePricingBreakdown
     */
    base: ValidatePricingBase;
    /**
     * 
     * @type {Array<ValidatePricingConfigItem>}
     * @memberof ValidatePricingBreakdown
     */
    _configuration: Array<ValidatePricingConfigItem>;
    /**
     * 
     * @type {string}
     * @memberof ValidatePricingBreakdown
     */
    setupTotal: string;
}

/**
 * Check if a given object implements the ValidatePricingBreakdown interface.
 */
export function instanceOfValidatePricingBreakdown(value: object): value is ValidatePricingBreakdown {
    if (!('base' in value) || value['base'] === undefined) return false;
    if (!('_configuration' in value) || value['_configuration'] === undefined) return false;
    if (!('setupTotal' in value) || value['setupTotal'] === undefined) return false;
    return true;
}

export function ValidatePricingBreakdownFromJSON(json: any): ValidatePricingBreakdown {
    return ValidatePricingBreakdownFromJSONTyped(json, false);
}

export function ValidatePricingBreakdownFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidatePricingBreakdown {
    if (json == null) {
        return json;
    }
    return {
        
        'base': ValidatePricingBaseFromJSON(json['base']),
        '_configuration': ((json['configuration'] as Array<any>).map(ValidatePricingConfigItemFromJSON)),
        'setupTotal': json['setup_total'],
    };
}

export function ValidatePricingBreakdownToJSON(json: any): ValidatePricingBreakdown {
    return ValidatePricingBreakdownToJSONTyped(json, false);
}

export function ValidatePricingBreakdownToJSONTyped(value?: ValidatePricingBreakdown | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base': ValidatePricingBaseToJSON(value['base']),
        'configuration': ((value['_configuration'] as Array<any>).map(ValidatePricingConfigItemToJSON)),
        'setup_total': value['setupTotal'],
    };
}

