/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Bandwidth usage information
 * @export
 * @interface VpsBandwidthInfo
 */
export interface VpsBandwidthInfo {
    /**
     * Bandwidth usage in MB
     * @type {number}
     * @memberof VpsBandwidthInfo
     */
    usageMb?: number;
    /**
     * Bandwidth limit in MB
     * @type {number}
     * @memberof VpsBandwidthInfo
     */
    limitMb?: number;
    /**
     * Whether bandwidth is unlimited
     * @type {boolean}
     * @memberof VpsBandwidthInfo
     */
    unlimited: boolean;
    /**
     * Bandwidth usage percentage
     * @type {number}
     * @memberof VpsBandwidthInfo
     */
    percent?: number;
}

/**
 * Check if a given object implements the VpsBandwidthInfo interface.
 */
export function instanceOfVpsBandwidthInfo(value: object): value is VpsBandwidthInfo {
    if (!('unlimited' in value) || value['unlimited'] === undefined) return false;
    return true;
}

export function VpsBandwidthInfoFromJSON(json: any): VpsBandwidthInfo {
    return VpsBandwidthInfoFromJSONTyped(json, false);
}

export function VpsBandwidthInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VpsBandwidthInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'usageMb': json['usage_mb'] == null ? undefined : json['usage_mb'],
        'limitMb': json['limit_mb'] == null ? undefined : json['limit_mb'],
        'unlimited': json['unlimited'],
        'percent': json['percent'] == null ? undefined : json['percent'],
    };
}

export function VpsBandwidthInfoToJSON(json: any): VpsBandwidthInfo {
    return VpsBandwidthInfoToJSONTyped(json, false);
}

export function VpsBandwidthInfoToJSONTyped(value?: VpsBandwidthInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'usage_mb': value['usageMb'],
        'limit_mb': value['limitMb'],
        'unlimited': value['unlimited'],
        'percent': value['percent'],
    };
}

