/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * CPU usage information
 * @export
 * @interface VpsCpuInfo
 */
export interface VpsCpuInfo {
    /**
     * CPU usage ratio (0.0 to 1.0)
     * @type {number}
     * @memberof VpsCpuInfo
     */
    usageRatio?: number;
    /**
     * CPU usage percentage
     * @type {number}
     * @memberof VpsCpuInfo
     */
    percent?: number;
    /**
     * Number of CPU cores
     * @type {number}
     * @memberof VpsCpuInfo
     */
    cores?: number;
}

/**
 * Check if a given object implements the VpsCpuInfo interface.
 */
export function instanceOfVpsCpuInfo(value: object): value is VpsCpuInfo {
    return true;
}

export function VpsCpuInfoFromJSON(json: any): VpsCpuInfo {
    return VpsCpuInfoFromJSONTyped(json, false);
}

export function VpsCpuInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VpsCpuInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'usageRatio': json['usage_ratio'] == null ? undefined : json['usage_ratio'],
        'percent': json['percent'] == null ? undefined : json['percent'],
        'cores': json['cores'] == null ? undefined : json['cores'],
    };
}

export function VpsCpuInfoToJSON(json: any): VpsCpuInfo {
    return VpsCpuInfoToJSONTyped(json, false);
}

export function VpsCpuInfoToJSONTyped(value?: VpsCpuInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'usage_ratio': value['usageRatio'],
        'percent': value['percent'],
        'cores': value['cores'],
    };
}

