/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Disk usage information
 * @export
 * @interface VpsDiskInfo
 */
export interface VpsDiskInfo {
    /**
     * Disk usage in bytes
     * @type {number}
     * @memberof VpsDiskInfo
     */
    usageBytes?: number;
    /**
     * Total disk space in bytes
     * @type {number}
     * @memberof VpsDiskInfo
     */
    totalBytes?: number;
    /**
     * Disk usage percentage
     * @type {number}
     * @memberof VpsDiskInfo
     */
    percent?: number;
    /**
     * Human-readable disk usage (e.g., '50 GB')
     * @type {string}
     * @memberof VpsDiskInfo
     */
    usageHuman?: string;
    /**
     * Human-readable total disk space (e.g., '100 GB')
     * @type {string}
     * @memberof VpsDiskInfo
     */
    totalHuman?: string;
}

/**
 * Check if a given object implements the VpsDiskInfo interface.
 */
export function instanceOfVpsDiskInfo(value: object): value is VpsDiskInfo {
    return true;
}

export function VpsDiskInfoFromJSON(json: any): VpsDiskInfo {
    return VpsDiskInfoFromJSONTyped(json, false);
}

export function VpsDiskInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VpsDiskInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'usageBytes': json['usage_bytes'] == null ? undefined : json['usage_bytes'],
        'totalBytes': json['total_bytes'] == null ? undefined : json['total_bytes'],
        'percent': json['percent'] == null ? undefined : json['percent'],
        'usageHuman': json['usage_human'] == null ? undefined : json['usage_human'],
        'totalHuman': json['total_human'] == null ? undefined : json['total_human'],
    };
}

export function VpsDiskInfoToJSON(json: any): VpsDiskInfo {
    return VpsDiskInfoToJSONTyped(json, false);
}

export function VpsDiskInfoToJSONTyped(value?: VpsDiskInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'usage_bytes': value['usageBytes'],
        'total_bytes': value['totalBytes'],
        'percent': value['percent'],
        'usage_human': value['usageHuman'],
        'total_human': value['totalHuman'],
    };
}

