/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 1.1.0 - 2026-07-16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Detailed IP address assignment for a VPS
 * @export
 * @interface VpsIpAddressDetail
 */
export interface VpsIpAddressDetail {
    /**
     * Primary IP address
     * @type {string}
     * @memberof VpsIpAddressDetail
     */
    ip: string;
    /**
     * IP address (may mirror ip)
     * @type {string}
     * @memberof VpsIpAddressDetail
     */
    address?: string;
    /**
     * Subnet mask
     * @type {string}
     * @memberof VpsIpAddressDetail
     */
    subnet?: string;
    /**
     * Gateway address
     * @type {string}
     * @memberof VpsIpAddressDetail
     */
    gateway?: string;
    /**
     * MAC address when available
     * @type {string}
     * @memberof VpsIpAddressDetail
     */
    mac?: string;
}

/**
 * Check if a given object implements the VpsIpAddressDetail interface.
 */
export function instanceOfVpsIpAddressDetail(value: object): value is VpsIpAddressDetail {
    if (!('ip' in value) || value['ip'] === undefined) return false;
    return true;
}

export function VpsIpAddressDetailFromJSON(json: any): VpsIpAddressDetail {
    return VpsIpAddressDetailFromJSONTyped(json, false);
}

export function VpsIpAddressDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): VpsIpAddressDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'ip': json['ip'],
        'address': json['address'] == null ? undefined : json['address'],
        'subnet': json['subnet'] == null ? undefined : json['subnet'],
        'gateway': json['gateway'] == null ? undefined : json['gateway'],
        'mac': json['mac'] == null ? undefined : json['mac'],
    };
}

export function VpsIpAddressDetailToJSON(json: any): VpsIpAddressDetail {
    return VpsIpAddressDetailToJSONTyped(json, false);
}

export function VpsIpAddressDetailToJSONTyped(value?: VpsIpAddressDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ip': value['ip'],
        'address': value['address'],
        'subnet': value['subnet'],
        'gateway': value['gateway'],
        'mac': value['mac'],
    };
}

