/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * VPS service information matching upstream API format
 * @export
 * @interface VpsServiceInfo
 */
export interface VpsServiceInfo {
    /**
     * Service ID (integer)
     * @type {number}
     * @memberof VpsServiceInfo
     */
    id: number;
    /**
     * Product name
     * @type {string}
     * @memberof VpsServiceInfo
     */
    product: string;
    /**
     * Hostname of the VPS
     * @type {string}
     * @memberof VpsServiceInfo
     */
    hostname: string;
    /**
     * Service status
     * @type {string}
     * @memberof VpsServiceInfo
     */
    status: string;
    /**
     * List of IP addresses assigned to this VPS
     * @type {Array<string>}
     * @memberof VpsServiceInfo
     */
    ips: Array<string>;
    /**
     * Service creation date (YYYY-MM-DD format)
     * @type {string}
     * @memberof VpsServiceInfo
     */
    createdAt: string;
}

/**
 * Check if a given object implements the VpsServiceInfo interface.
 */
export function instanceOfVpsServiceInfo(value: object): value is VpsServiceInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('product' in value) || value['product'] === undefined) return false;
    if (!('hostname' in value) || value['hostname'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('ips' in value) || value['ips'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function VpsServiceInfoFromJSON(json: any): VpsServiceInfo {
    return VpsServiceInfoFromJSONTyped(json, false);
}

export function VpsServiceInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VpsServiceInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'product': json['product'],
        'hostname': json['hostname'],
        'status': json['status'],
        'ips': json['ips'],
        'createdAt': json['created_at'],
    };
}

export function VpsServiceInfoToJSON(json: any): VpsServiceInfo {
    return VpsServiceInfoToJSONTyped(json, false);
}

export function VpsServiceInfoToJSONTyped(value?: VpsServiceInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'product': value['product'],
        'hostname': value['hostname'],
        'status': value['status'],
        'ips': value['ips'],
        'created_at': value['createdAt'],
    };
}

