/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Standard response data for VPS power management operations
 * @export
 * @interface VpsSimpleActionResponseData
 */
export interface VpsSimpleActionResponseData {
    /**
     * Status message indicating the result of the operation
     * @type {string}
     * @memberof VpsSimpleActionResponseData
     */
    message: string;
}

/**
 * Check if a given object implements the VpsSimpleActionResponseData interface.
 */
export function instanceOfVpsSimpleActionResponseData(value: object): value is VpsSimpleActionResponseData {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function VpsSimpleActionResponseDataFromJSON(json: any): VpsSimpleActionResponseData {
    return VpsSimpleActionResponseDataFromJSONTyped(json, false);
}

export function VpsSimpleActionResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): VpsSimpleActionResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function VpsSimpleActionResponseDataToJSON(json: any): VpsSimpleActionResponseData {
    return VpsSimpleActionResponseDataToJSONTyped(json, false);
}

export function VpsSimpleActionResponseDataToJSONTyped(value?: VpsSimpleActionResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

