/* tslint:disable */
/* eslint-disable */
/**
 * HostAfricaApi
 * HostAfrica API - Manages VPS instances and operations
 *
 * The version of the OpenAPI document: 2026-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * VM information
 * @export
 * @interface VpsVmInfo
 */
export interface VpsVmInfo {
    /**
     * VM status (e.g., running, stopped)
     * @type {string}
     * @memberof VpsVmInfo
     */
    status: string;
    /**
     * Uptime in human-readable format
     * @type {string}
     * @memberof VpsVmInfo
     */
    uptime?: string;
    /**
     * Uptime in seconds
     * @type {number}
     * @memberof VpsVmInfo
     */
    uptimeSeconds?: number;
    /**
     * Hostname of the VM
     * @type {string}
     * @memberof VpsVmInfo
     */
    hostname?: string;
    /**
     * Boot devices configuration
     * @type {string}
     * @memberof VpsVmInfo
     */
    bootDevices?: string;
    /**
     * Proxmox VM ID
     * @type {string}
     * @memberof VpsVmInfo
     */
    vmid: string;
    /**
     * Proxmox node name
     * @type {string}
     * @memberof VpsVmInfo
     */
    node: string;
    /**
     * Virtualization type (qemu or lxc)
     * @type {string}
     * @memberof VpsVmInfo
     */
    virtualization: string;
}

/**
 * Check if a given object implements the VpsVmInfo interface.
 */
export function instanceOfVpsVmInfo(value: object): value is VpsVmInfo {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('vmid' in value) || value['vmid'] === undefined) return false;
    if (!('node' in value) || value['node'] === undefined) return false;
    if (!('virtualization' in value) || value['virtualization'] === undefined) return false;
    return true;
}

export function VpsVmInfoFromJSON(json: any): VpsVmInfo {
    return VpsVmInfoFromJSONTyped(json, false);
}

export function VpsVmInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VpsVmInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'uptime': json['uptime'] == null ? undefined : json['uptime'],
        'uptimeSeconds': json['uptime_seconds'] == null ? undefined : json['uptime_seconds'],
        'hostname': json['hostname'] == null ? undefined : json['hostname'],
        'bootDevices': json['boot_devices'] == null ? undefined : json['boot_devices'],
        'vmid': json['vmid'],
        'node': json['node'],
        'virtualization': json['virtualization'],
    };
}

export function VpsVmInfoToJSON(json: any): VpsVmInfo {
    return VpsVmInfoToJSONTyped(json, false);
}

export function VpsVmInfoToJSONTyped(value?: VpsVmInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'uptime': value['uptime'],
        'uptime_seconds': value['uptimeSeconds'],
        'hostname': value['hostname'],
        'boot_devices': value['bootDevices'],
        'vmid': value['vmid'],
        'node': value['node'],
        'virtualization': value['virtualization'],
    };
}

